/* UTF-8 · Mermaid 四芯片图中的读数、选中状态和物理通信路径。 */
(function(root){
 'use strict';const M=root.GROQ_CLUSTER_MAP,C=root.GROQ_CLUSTER,ns='http://www.w3.org/2000/svg';
 function create({container,assets,onSelect}){
  container.innerHTML=assets.cluster6.svg;const svg=container.querySelector('svg'),elements={};svg.classList.add('cluster-atlas');svg.setAttribute('aria-label','四颗 TSP、各自片上硬件与直接 C2C 连接');svg.setAttribute('role','group');
  for(const n of svg.querySelectorAll('[data-hw-id]')){const id=n.dataset.hwId,b=M.nodes[id];elements[id]=n;if(!b)continue;const title=document.createElementNS(ns,'title');title.textContent=b.label;n.appendChild(title);if(!['frame','trace','tile','caption'].includes(b.kind)){n.setAttribute('tabindex','0');n.setAttribute('role','button');n.dataset.interactive='true';const select=()=>onSelect(id);n.addEventListener('click',select);n.addEventListener('keydown',e=>{if(['Enter',' '].includes(e.key)){e.preventDefault();e.stopPropagation();select();}});}}
  function text(id,lines){const n=elements[id],b=M.nodes[id];if(!n||!b)return;const t=n.querySelector('text');if(!t)return;let arr=Array.isArray(lines)?lines:[lines];const font=b.kind==='slice'?13:b.kind==='bus'?12:b.w<50?13:16,limit=b.w-8,clip=line=>{let w=0,out='';for(const ch of String(line)){w+=font*(/[\u0000-\u007f]/.test(ch)?.57:1);if(w>limit)return out+'…';out+=ch;}return out;};if(['frame','chip','trace'].includes(b.kind))arr=[];if(b.h<35)arr=[arr.join(' · ')];t.replaceChildren();t.style.fontSize=font+'px';t.setAttribute('x','0');t.setAttribute('y',String(5-(arr.length-1)*8));arr.forEach((line,i)=>{const span=document.createElementNS(ns,'tspan');span.setAttribute('x','0');if(i)span.setAttribute('dy','16');span.textContent=clip(line);t.appendChild(span);});n.querySelector('title').textContent=arr.join('；');n.setAttribute('aria-label',b.label+'：'+arr.join('；'));}
  function render(model,patch,selected){for(const[id,n]of Object.entries(elements)){for(const k of ['hw-data','hw-gold','hw-computed','hw-current','hw-active','hw-idle','hw-picked'])n.classList.remove(k);const b=M.nodes[id];text(id,b.label);if(/^C\d$/.test(b.owner)&&!model.chips[Number(b.owner[1])].active)n.classList.add('hw-idle');}for(const[id,v]of Object.entries(patch)){text(id,v.label);elements[id]?.classList.add(...v.classes);}for(const[a,b]of C.edges)text(C.edgeKey(a,b),[a+' ↔ '+b+' · C2C',(model.c.links*4)+' lanes']);if(selected)elements[selected]?.classList.add('hw-picked');}
  const point=id=>{const b=M.nodes[id];return b?{x:b.x+b.w/2,y:b.y+b.h/2}:null;};
  function route(p){if(p.wire)return M.packetPath(p,C.route).map(point).filter(Boolean);const a=point(p.from),b=point(p.to);if(!a||!b)return[];if(p.from.endsWith('_ICU'))return[a,{x:b.x,y:a.y},b];const owner=p.from.match(/^C\d_/);if(owner&&p.to.startsWith(owner[0])&&!p.from.endsWith('_SRF')&&!p.to.endsWith('_SRF')){const bus=point(owner[0]+'SRF');return[a,{x:a.x,y:bus.y},{x:b.x,y:bus.y},b];}return[a,b];}
  return{render,point,route,node:id=>elements[id]||null,svg,address:id=>{const b=M.nodes[id];return b?(/^C\d$/.test(b.owner)?'TSP '+b.owner[1]+' / ':b.owner==='HOST'?'芯片外 / ':'板上 / ')+b.label:'';}};
 }
 root.GROQ_CLUSTER_SCENE={create};
})(window);
