/* UTF-8 · 四芯片硬件、部署分片与通信账本联动。 */
(function(){
 'use strict';const RF=window.GROQ_REQUEST_FLOW;const O=window.GROQ_OPERATORS,C=window.GROQ_CLUSTER,L=window.GROQ_CLUSTER_LESSONS,P=window.GROQ_PERFORMANCE,M=window.GROQ_CLUSTER_MAP,G=window.HARDWARE_SVGS,E=window.HARDWARE_MOTION,$=id=>document.getElementById(id),reduced=window.matchMedia('(prefers-reduced-motion: reduce)');
 if(!C||!L||!G?.cluster6){$('cluster-title').textContent='多芯片图形未加载，请打开完整的独立 HTML。';return;}
 const S={course:true,courseIndex:0,courseHistory:[],config:{...C.defaults},index:0,phase:0,settled:false,vector:0,link:null,selected:null,operator:null,operatorChip:0,operatorParams:{...O.defaults},zoom:1,view:'follow',cameraChip:0,cameraLocal:0,auto:false,timer:null,valid:true};let model=C.build(window.GROQ_LAB.getModel(),S.config),motion,scene,softwareFlow,requestFlow,requestLesson=null,micro=null,currentCost={low:0,high:0},editTimer,applying=false;
 const txt=(id,value)=>{$(id).textContent=value;},esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),id=()=>S.course?RF.items[S.courseIndex].id:S.operator?'micro_'+S.operator:L.definitions[S.index][0],range=(a,b)=>Math.abs(a-b)<1e-9?P.time(a):P.time(a)+' — '+P.time(b),array=v=>'['+v.join(', ')+']';
 const table=(headers,rows)=>'<table class="ledger-table"><thead><tr>'+headers.map(h=>'<th>'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(v=>'<td>'+esc(v)+'</td>').join('')+'</tr>').join('')+'</tbody></table>';
 const modelFields=[['batch','每组批量 B',1,64,1],['seq','上下文 S（含新位置）',1,32768,1],['dim','隐藏维 D',8,16384,8],['heads','Q 头数 H',1,128,1],['kvHeads','KV 头数 G',1,128,1],['ffn','FFN 维度 F',8,65536,8],['layers','模型层数 L',1,128,1],['vocab','词表大小 V',16,262144,16]];
 const linkFields=[['laneGbps','每 lane 速率 Gbit/s',1,112,1],['links','每邻接使用的 ×4 链路',1,8,1],['linkUtil','有效率 %',1,100,1,.01],['hopUs','每跳传播预算 μs',0,1000,.05],['alignUs','接收 / 对齐预算 μs',0,1000,.05],['windowKiB','接收窗口 KiB',1,1024,1],['windowUs','窗口间等待预算 μs',0,1000,.01]];
 const inputs=(fields,attr,data)=>fields.map(([name,title,min,max,step,scale=1])=>`<label>${title}<input type="number" ${attr}="${name}" data-scale="${scale}" min="${min}" max="${max}" step="${step}" value="${data[name]/scale}"></label>`).join('');
 $('cluster-model-fields').innerHTML=inputs(modelFields,'data-cluster-model',model.p);$('cluster-link-fields').innerHTML=inputs(linkFields,'data-cluster-param',S.config);
 function fill(){for(const k of Object.keys(O.defaults))$('op-'+k).value=S.operatorParams[k];document.querySelectorAll('[data-cluster-model]').forEach(el=>el.value=model.p[el.dataset.clusterModel]);document.querySelectorAll('[data-cluster-param]').forEach(el=>el.value=model.c[el.dataset.clusterParam]/Number(el.dataset.scale||1));$('cluster-strategy').value=model.c.strategy;$('cluster-request').value=model.c.request;$('cluster-stage').innerHTML=model.groups.map((g,i)=>`<option value="${i}">第 ${i+1} 段 · TSP ${g.join(' / ')}</option>`).join('');$('cluster-stage').value=model.c.stage;}
 function stop(){S.auto=false;clearTimeout(S.timer);motion?.pause();txt('cluster-auto','连续演示');$('cluster-auto').setAttribute('aria-pressed','false');}
 const getPhases=()=>requestLesson?requestLesson.phases:micro?micro.phases:L.phases(model,id(),{vector:S.vector,link:S.link,settled:S.settled});
 const getPatch=()=>requestLesson?requestLesson.patch(S.phase,S.settled):micro?{...L.patch(model,'place',0),...micro.patch(S.phase,S.settled)}:L.patch(model,id(),S.phase,{vector:S.vector,link:S.link,settled:S.settled});

 function setCoursePosition(position){S.courseIndex=position.index;if(position.stage!==model.c.stage){S.config.stage=position.stage;model=C.build(window.GROQ_LAB.getModel(),S.config);fill();}}
 function pickRequest(key){const index=RF.position(key);if(index<0)return;stop();S.course=true;S.operator=null;S.courseHistory=[];let stage=model.c.stage;if(index<=RF.position('broadcast'))stage=0;if(index>=RF.position('finalnorm'))stage=model.PP-1;setCoursePosition({index,stage});go(S.index);}
 function requestCost(){const x=requestLesson,a=x.math,kind=a.kind,traffic=a.wireBytes??a.memoryBytes??0,bw=kind==='network'?model.base.effective.network:kind==='pcie'?model.base.effective.pcie:kind==='cpu'?0:model.base.effective.memory;currentCost={low:a.low,high:a.high};txt('cluster-cost-name',x.name);txt('cluster-cost',range(a.low,a.high));txt('cluster-cost-kind','完整流程的当前操作 · 参数化估算');txt('cluster-cost-scope',x.scope);['矩阵运算量','向量工作量','本步有效数据','对应有效带宽'].forEach((v,i)=>txt('metric-'+String.fromCharCode(97+i)+'-label',v));txt('cluster-link-bandwidth',a.repeat!==undefined?'重复 '+a.repeat+' 层':P.ops(a.flops||0)+' FLOPs');txt('cluster-message-bytes',a.repeat!==undefined?'已含 Attention / FFN':P.ops(a.vectorOps||0)+' 项');txt('cluster-all-bytes',a.repeat!==undefined?'见逐层预算':P.bytes(traffic));txt('cluster-rounds',bw?P.num(bw/1e9)+' GB/s':'CPU 固定 / 吞吐预算');$('cluster-formulas').innerHTML=[x.shape,...x.formulas].filter(Boolean).map(f=>'<div class="formula-line">'+esc(f)+'</div>').join('');$('cluster-budget').innerHTML=table(['成本项','数值'],[['当前操作下界',P.time(a.low)],['串行口径',P.time(a.high)],['范围',x.scope]]);txt('cluster-cost-note',x.note);txt('cluster-total',model.valid?range(model.pipelineLow,model.pipelineHigh):'分片 / 容量条件不满足');txt('cluster-interval',!model.valid?'未估算':model.c.inFlight<model.PP?'请求数少于流水段数':P.time(model.interval)+'（理想）');}
 function requestSample(){txt('cluster-sample-title',requestLesson.name+' · 指令和数据');txt('cluster-sample-explain',requestLesson.note);$('cluster-sample').innerHTML=table(['动作','指令 / 操作','数据状态'],requestLesson.phases.map((p,i)=>[p.title,p.instruction,i<S.phase||i===S.phase&&S.settled?p.dataLabel:'等待该动作完成']));}

 function familyNavigation(){$('operator-assumptions').open=Boolean(micro&&['shuffle','control'].includes(micro.family.id));
  $('operator-families').innerHTML='<button data-family="request" aria-pressed="'+String(S.course)+'">完整请求流程</button>'+O.families.map(f=>'<button data-family="'+f.id+'" aria-pressed="'+String(micro?.family.id===f.id)+'">'+f.name+'</button>').join('');
  $('software-operation').innerHTML=(micro?micro.family.ops:L.definitions).map((a,i)=>'<option value="'+(micro?a[0]:i)+'">'+(micro?'':String(i+1).padStart(2,'0')+' · ')+a[1]+'</option>').join('');$('software-operation').value=micro?S.operator:String(S.index);
  txt('operator-family-note',micro?micro.family.note:'副本是一套模型部署；段划分模型层；分片划分同层矩阵。它们是软件安排。下面并排显示指令与数据。');
  if(S.course){const group=RF.groups[RF.groupOf(id())];$('software-operation').innerHTML=group.keys.map(key=>'<option value="'+key+'">'+esc(RF.title(model,key))+'</option>').join('');$('software-operation').value=id();txt('operator-family-note',requestLesson.note);}
 }
 function operatorCost(){
  currentCost=micro;txt('cluster-cost-name',micro.op.name+' · TSP '+micro.chipId);txt('cluster-cost',range(micro.low,micro.high));txt('cluster-cost-kind','本片独立操作 · 重叠与串行估算');txt('cluster-cost-scope',micro.family.unit);
  ['矩阵计算量','向量等效工作量','本片 SRAM 读写','有效片上带宽'].forEach((v,i)=>txt('metric-'+String.fromCharCode(97+i)+'-label',v));
  txt('cluster-link-bandwidth',P.ops(micro.flops)+' FLOPs');txt('cluster-message-bytes',P.ops(micro.vector)+' 项');txt('cluster-all-bytes',P.bytes(micro.bytes));txt('cluster-rounds',P.num(model.base.effective.memory/1e12)+' TB/s');
  $('cluster-formulas').innerHTML=[micro.shape,...micro.formulas].map(t=>'<div class="formula-line">'+esc(t)+'</div>').join('');$('cluster-budget').innerHTML=table(['成本项','结果'],[['计算 / 重排',P.time(micro.compute)],['MEM 读写',P.time(micro.transport)],['固定算子开销',P.time(micro.fixed)],['指令时序预算',P.time(micro.clock)],['本步估算',range(micro.low,micro.high)]]);
  txt('cluster-cost-note','本卡只统计所选芯片的独立操作，不再叠加到完整层路径。矩阵 / 向量算子复用参数模型；SXM 吞吐和 ICU 周期为可修改的教学假设。');
  txt('cluster-total',model.valid?range(model.pipelineLow,model.pipelineHigh):'当前部署容量 / 分片不满足');txt('cluster-interval',!model.valid?'未估算':model.c.inFlight<model.PP?'当前请求数少于流水段数':P.time(model.interval)+'（理想）');
 }
 function operatorSample(){txt('cluster-sample-title',micro.op.name+'：逐段核对数值');txt('cluster-sample-explain',micro.description);$('cluster-sample').innerHTML=table(['软件动作','对应指令计划','已完成的数据状态'],micro.phases.map((p,i)=>[p.title,p.instruction,i<S.phase||i===S.phase&&S.settled?(p.values.length?array(p.values.map(v=>Number.isFinite(v)?Math.round(v*1000)/1000:'−∞')):p.dataLabel||'计划 / 地址就绪'):'等待该动作完成']));}
 function previous(){stop();if(S.course){const previous=S.courseHistory.pop()||RF.next(S.courseIndex,model.c.stage,model.PP,-1);setCoursePosition(previous);go(S.index);return;}if(micro){const list=micro.family.ops,i=list.findIndex(x=>x[0]===S.operator);S.operator=list[Math.max(0,i-1)][0];go(S.index);}else go(S.index-1);}
 function zoom(){
  if(!scene)return;const view=window.GROQ_VIEWPORT.cluster(M,{phase:getPhases()[S.phase],local:S.cameraLocal,chip:S.cameraChip,mode:S.view,zoom:S.zoom});
  const svg=$('cluster-canvas').querySelector('svg');svg.setAttribute('viewBox',window.GROQ_VIEWPORT.serialize(view.box));svg.setAttribute('preserveAspectRatio','xMidYMid meet');txt('cluster-camera-label',view.label);txt('cluster-zoom',Math.round(S.zoom*100)+'%');$('cluster-fit').setAttribute('aria-pressed',String(S.view==='board'));$('cluster-follow').setAttribute('aria-pressed',String(S.view==='follow'));document.querySelectorAll('[data-cluster-chip]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.clusterChip)===view.chip)));
 }
 function follow(phase){zoom();}
 function assignment(){
  $('cluster-assignment').innerHTML=table(['芯片 / 段','模型层','Q / KV 头','FFN 通道'],model.chips.map(ch=>['TSP '+ch.id+' / '+(ch.stage+1),ch.layerStart+1+'—'+ch.layerEnd,ch.headStart+'—'+(ch.headEnd-1)+' / '+ch.kvHeads.join(','),ch.ffStart+'—'+(ch.ffEnd-1)]));
  txt('hardware-validity',model.valid?'功能结构依据第一代 TSP；位置与比例为示意。MAC 位于 MXM 内，逐元素与归约 ALU 同属中央 VXM。':'当前模型分配超出 SRAM 容量或分片条件不满足：下面仅演示算子机制，不表示已成功装入设备。');$('hardware-validity').classList.toggle('capacity-invalid',!model.valid);
  txt('cluster-kv-rule',`当前请求 ${model.c.request} 绑定副本 ${model.replica}。本段 KV 总副本因子 ${P.num(model.kvReplicaFactor)}×；${model.kvReplicaFactor>1?'同一 KV 头在多个 Q 头分片中保留副本。':'每个 KV 头在本段只保存一份。'}`);
  $('cluster-chips').innerHTML=model.chips.map(ch=>`<button data-cluster-chip="${ch.id}" class="${ch.active?'active':'inactive'}"><b>TSP ${ch.id}</b><span>软件：段 ${ch.stage+1} / 分片 ${ch.rank}</span></button>`).join('');
  $('cluster-capacity').innerHTML=table(['芯片','权重 / KV','总占用 / 容量'],model.chips.map(ch=>['TSP '+ch.id,P.bytes(ch.weights)+' / '+P.bytes(ch.kv),P.bytes(ch.total)+' / '+P.bytes(ch.limit)]));
  txt('cluster-capacity-state',model.issues.length?'形状不适配当前分片':model.active.every(x=>x.fits)?'本副本容量下界可容纳':'本副本有芯片容量不足');$('cluster-capacity-state').closest('details').classList.toggle('over-capacity',!model.valid);
  txt('cluster-capacity-note',model.issues.length?model.issues.join('；'):`KV 按每副本 ${model.c.inFlight} 组常驻请求分别预留。总占用还含工作区与收发窗口。输入词嵌入在入口，输出词表在末段，必要的跨片副本逐片计入；容量通过不代表实际编译部署成功。`);
 }
 function cost(){
  if(requestLesson&&requestLesson.source!=='cluster'){requestCost();return;}if(micro){operatorCost();return;}['有效单向链路带宽','当前消息 / 归约块','全组发送有效字节','串行通信轮数 / 跳数'].forEach((v,i)=>txt('metric-'+String.fromCharCode(97+i)+'-label',v));
  const d=model.d,group=model.group,ch=group.map(i=>model.chips[i]),ar=model.reduction,k=id();let lo=0,hi=0,payload=0,total=0,rounds=0,formulas=[],budget=[],kind='本地说明，不重复计入热请求',display=null,note='公开硬件机制与本页选定部署分开；有效率、等待与软件预算都是可修改的教学假设。';
  if(k==='place'){display='4 颗 TSP';formulas=[`流水段 PP=${model.PP}，每段 TP=${model.TP}，副本数=${model.spec.groups.length}`,'先安排模型层、权重与 KV 的拥有者，再让请求进入模型副本。'];}
  else if(k==='bind'){display='副本 '+model.replica;formulas=[`请求 ${model.c.request} → ${model.groups.map(g=>'TSP '+g.join(' + ')).join(' → ')}`,'后续 Decode 保持绑定，缓存键包含请求、层、KV 头和位置。'];}
  else if(k==='input'){const list=model.base.steps.filter(s=>['pcie_in','landing','embedding'].includes(s.id));lo=list.reduce((a,s)=>a+s.low,0);hi=list.reduce((a,s)=>a+s.high,0);payload=d.B*d.T*4;total=payload;kind='入口 PCIe、落地与词嵌入预算';formulas=[`输入 ID：${d.B} × ${d.T} × 4 = ${P.num(payload)} B`,`激活 X：${d.B} × ${d.T} × ${d.D} × 2 = ${P.num(model.activation)} B`];budget=list.map(s=>[s.title,range(s.low,s.high)]);}
  else if(k==='broadcast'){const t=model.broadcast;lo=t.low;hi=t.high;payload=model.TP>1?model.activation:0;total=payload*(model.TP-1);rounds=model.TP-1;kind='依次转发完整激活的链路预算';formulas=[`每跳传 X = B×T×D×2 = ${P.bytes(model.activation)}`,`本段 ${model.TP} 片；本例依次传 ${rounds} 跳`,`全组发送有效字节 = ${rounds} × ${P.bytes(model.activation)} = ${P.bytes(total)}`];}
  else if(k==='attention'||k==='ffn'){const field=k==='attention'?'attention':'ffnCost';lo=Math.max(...ch.map(x=>x[field].low));hi=Math.max(...ch.map(x=>x[field].high));kind='一层本地算子预算；跨片归约在下一步';formulas=ch.map(x=>`TSP ${x.id}：${P.ops(x[field].flops)} FLOPs，${P.bytes(x[field].bytes)} 片上读写`);budget=ch.map(x=>['TSP '+x.id,range(x[field].low,x[field].high)]);note='每片分别按有效算力与片上带宽估算，本段按最慢一片计并行时间；本地预算包含归一化、残差与激活格式转换，C2C 另列。';}
  else if(['attn_reduce','ffn_reduce'].includes(k)){lo=ar.low;hi=ar.high;payload=ar.chunk;total=ar.totalSent;rounds=ar.rounds;kind='整次 All-reduce 的通信与接收端求和';formulas=[`每片 FP32 部分和 M = B×T×D×4 = ${P.bytes(model.partial)}`,`每轮每片发 M/P = ${P.bytes(payload)}`,`Reduce-scatter 与 All-gather 各 P−1 轮；合计 ${rounds} 轮`,`每片发送 2(P−1)M/P = ${P.bytes(ar.perRankSent)}`,`全组所有方向发送 = ${P.bytes(total)}；不把它当成一条链路的字节数`];budget=[['一轮通信关键路径',range(ar.round.low,ar.round.high)],['串行通信轮数',rounds],['每片累计归约加法',P.time(ar.additionMs)],['整次归约',range(lo,hi)]];note='同一轮各片同时发送，按每条链路的块大小计关键路径；接收端在 Reduce-scatter 做加法，All-gather 只复制。这里按 FP32 部分和计流量。';}
  else if(k==='link'){const t=model.transfer(model.activation),slot=Math.min(S.vector,t.slots-1),valid=Math.min(320,t.payload-slot*320);lo=t.low;hi=t.high;payload=t.payload;total=payload;rounds=1;kind='完整张量的一次直接 C2C 传输';formulas=[`激活 ${P.bytes(t.payload)} ÷ 320 B → ${t.slots} 个向量槽`,`槽位预算 ${P.num(t.padded)} B；末尾填充 ${t.padding} B`,`窗口 ${model.c.windowKiB} KiB 可容纳 ${t.windowSlots} 个槽，共 ${t.windows} 个窗口`,`当前槽 ${slot+1}：偏移 ${slot*320} B，有效 ${valid} B`,`有效单向带宽 = ${model.c.laneGbps} Gbit/s × 4 lanes × ${model.c.links} × ${P.num(model.c.linkUtil*100)}% ÷ 8 = ${P.num(model.bandwidth/1e9)} GB/s`];budget=[['发送 MEM 读取',P.time(t.readMs)],['链路序列化',P.time(t.wireMs)],['单跳传播预算',P.time(t.hopMs)],['Receive / 对齐预算',P.time(t.alignMs)],['接收 MEM 写入',P.time(t.writeMs)],['窗口之间等待',P.time(t.windowMs)],['重叠 — 串行',range(t.low,t.high)]];note='重叠口径取发送读取、链路、接收写入的最大值，再加传播与设定等待；串行口径相加。320 B 槽位不等于线上完整报文，FEC 和协议损耗用有效率近似。';}
  else if(k==='handoff'){lo=model.handoffLow;hi=model.handoffHigh;payload=model.handoffs.length?model.activation:0;total=model.handoffs.reduce((a,x)=>a+x.payload*x.hops,0);rounds=Math.max(0,...model.handoffs.map(x=>x.hops));kind='本次阶段交接：按最慢并发路径计';formulas=model.handoffs.map(x=>`TSP ${x.from} → ${x.to}：${P.bytes(x.payload)}，${x.hops} 跳`);if(!formulas.length)formulas=['当前已经是最后一段，跨阶段流量与时间为 0。'];budget=model.handoffs.map(x=>['TSP '+x.from+' → '+x.to,range(model.transfer(x.payload,x.hops).low,model.transfer(x.payload,x.hops).high)]);note='本段其余层重复同样的 Attention、FFN 与归约后才交接。KV 和权重保留在原阶段，发往下一阶段的是 FP16 隐藏激活。';}
  else if(k==='advance'){display=model.c.stage+1<model.PP?'准备第 '+(model.c.stage+2)+' 段':'全部阶段完成';formulas=model.stageCost.map(s=>`第 ${s.index+1} 段：${s.layers} 层，${range(s.low,s.high)}`);}
  else if(k==='head'){const s=model.headCost,size=model.groups.at(-1).length;lo=s.low;hi=s.high;payload=d.B*d.V*4/size;total=d.B*d.V*4;kind='词表矩阵分片的理想均分预算';formulas=[`每末段分片：2×B×D×(V/P) = ${P.ops(2*d.B*d.D*d.V/size)} FLOPs`,`每片候选 ${d.V/size} 个，FP32 logits ${P.bytes(payload)}`,'候选在主机按词表索引汇合，此处不做跨片求和。'];note='此项只给出词表矩阵均分的估算，不含最终归一化、多个 PCIe 接口争用与主机采样；不纳入上面的 L 层路径预算。';}
  else if(k==='return'){lo=hi=model.p.samplingUs/1000;kind='主机采样 / 增量解码的设定预算';formulas=[`采样 / 解码 = ${model.p.samplingUs} μs`,`Token ID = 608；输出片段“芯片”为预设示例`];}
  else if(k==='feedback'){payload=d.B*4;total=payload;display='只提交新 ID';formulas=[`下一轮 ID 输入 ${d.B} × 1 × 4 = ${P.bytes(payload)}`,`入口重新查嵌入，后续芯片得到新的激活；已有 KV 不重新传遍全部芯片。`];}
  else if(k==='overlap'){display=model.c.inFlight+' 组独立请求';kind='教学调度槽与设备时间分开';formulas=[`${model.PP} 段、${model.c.inFlight} 组就绪请求 → ${model.PP+model.c.inFlight-1} 个示意调度槽`,'单请求路径按各段相加，理想满流水间隔按最慢阶段决定。','同一请求的下一枚 Token 必须等上一枚采样结果。'];}
  currentCost={low:lo,high:hi};txt('cluster-cost-name',L.definitions[S.index][1]);txt('cluster-cost',display||range(lo,hi));txt('cluster-cost-kind',kind);txt('cluster-cost-scope',['place','bind','overlap'].includes(k)?'所选模型副本':k==='input'?'入口 TSP '+model.groups[0][0]:k==='head'?model.groups.at(-1).map(i=>'TSP '+i).join(' / '):k==='return'?'主机 CPU / 用户':k==='feedback'?'主机 → TSP '+model.groups[0][0]:k==='link'&&S.link?S.link.map(i=>'TSP '+i).join(' → '):model.group.map(i=>'TSP '+i).join(' / '));txt('cluster-link-bandwidth',P.num(model.bandwidth/1e9)+' GB/s');txt('cluster-message-bytes',P.bytes(payload));txt('cluster-all-bytes',P.bytes(total));txt('cluster-rounds',String(rounds));$('cluster-formulas').innerHTML=formulas.map(f=>'<div class="formula-line">'+esc(f)+'</div>').join('');$('cluster-budget').innerHTML=budget.length?table(['成本项','结果'],budget):'';txt('cluster-cost-note',note);
  txt('cluster-total',model.valid?range(model.pipelineLow,model.pipelineHigh):'当前分片 / 容量条件不满足');txt('cluster-interval',!model.valid?'未估算':model.c.inFlight<model.PP?'当前请求数少于流水段数':P.time(model.interval)+'（理想）');
 }
 function sample(){
  if(requestLesson){requestSample();return;}if(micro){operatorSample();return;}const k=id();let title='分片决定谁保存、谁计算',explain='芯片分工来自右侧模型形状；这里显示当前步骤实际传递的数据类型。',html='';
  if(['attn_reduce','ffn_reduce'].includes(k)){const current=model.ring[S.phase],t=!S.settled&&['reduce','gather'].includes(current.kind)?model.ring[S.phase-1]:current;title='4 个数，检查每一轮归约';explain='独立的归约数值例子：第 r 片贡献 (r+1)×[1,2,3,4]。真实性能计算使用右侧 B、T、D；小例子不代表实际模型输出。传输到达后才更新表内结果。';html=table(['芯片','当前 4 个数','完整求和块'],model.group.map((i,r)=>['TSP '+i,array(t.values[r]),t.known[r].map((v,k)=>v?'块 '+k:'').filter(Boolean).join('、')||'尚无']));if(current.moves.length)html+=table(['物理发送','数据块','接收方操作'],current.moves.map(x=>['TSP '+x.from+' → '+x.to,array(x.values),x.add?'与本地同块相加':'覆盖该块，不再次相加']));}
  else if(k==='overlap'){title='独立请求如何填入流水线';explain='列是教学调度槽，格子表示该阶段正在处理哪个请求。此表不把不同阶段的真实耗时强行画成相等。';const headers=['流水段',...model.pipelineSlots.map(x=>'槽 '+(x.slot+1))],data=model.groups.map((g,stage)=>['第 '+(stage+1)+' 段 / '+g.join('+'),...model.pipelineSlots.map(t=>t.jobs.find(j=>j.stage===stage)?.request||'空闲')]);html=table(headers,data);}
  else if(k==='link'){const t=model.transfer(model.activation),v=Math.min(S.vector,t.slots-1),a=S.link?.[0]??model.group[0],b=S.link?.[1]??model.group[1]??model.groups[model.c.stage+1]?.[0]??C.edges.find(e=>e.includes(a)).find(i=>i!==a);title='这个向量在收发两端的状态';explain='发送缓冲、SerDes、Receive / Deskew 和目的 MEM 都在芯片图里。选择最后一个向量，可看到有效数据与填充的区别。';html=table(['项目','当前值'],[['物理连接','TSP '+a+' → '+b],['输入张量',`[${model.d.B},${model.d.T},${model.d.D}] FP16`],['本向量字节范围',v*320+'—'+Math.min(t.payload-1,(v+1)*320-1)],['有效数据 / 槽位',Math.min(320,t.payload-v*320)+' B / 320 B'],['当前硬件状态',(S.settled?['源 MEM 已读出','本向量已抵达接收端','接收已对齐','本向量已写入目的 MEM']:['源 MEM 读取中','发送 / 链路传播','接收对齐中','目的 MEM 写入中'])[S.phase]],['接收窗口',Math.floor(v/t.windowSlots)+1+' / '+t.windows]]);}
  else if(k==='attention'||k==='ffn'){title=k==='attention'?'头与 KV 的拥有者':'Gate / Up 列与 Down 行的拥有者';explain=k==='attention'?'GQA 头可能由多个查询分片共享；左侧软件部署表列出所需 KV 头，右侧计入复制后的容量。':'每片 Gate / Up 只产生自己的 FFN 通道，Down 的本地结果仍是完整 D 维部分和。';html=table(['芯片','本地分工','缓存 / 矩阵'],model.group.map(i=>{const ch=model.chips[i];return['TSP '+i,k==='attention'?'Q 头 '+ch.headStart+'—'+(ch.headEnd-1):'F 通道 '+ch.ffStart+'—'+(ch.ffEnd-1),k==='attention'?'KV 头 '+ch.kvHeads.join(','):`Wg/Wu [D,${ch.ff}]；Wd [${ch.ff},D]`];}));}
  else html=table(['对象','本页采用的处理'],[['输入 Token ID','只先提交到所选副本的入口芯片'],['模型权重','按照层与矩阵分片保留在各片 MEM'],['激活','同层输入分发，或交接给后续模型层'],['FP32 部分和','沿 C2C 交换，在接收方 VXM 归约'],['KV 历史','按请求、模型层与 KV 头留在拥有者'],['下一枚 Token','采样后再进入同一副本的下一轮']]);
  txt('cluster-sample-title',title);txt('cluster-sample-explain',explain);$('cluster-sample').innerHTML=html;
 }
 function navigation(){familyNavigation();requestFlow.render({mode:model.p.mode,key:S.course?id():S.operator||L.definitions[S.index][0]});txt('request-flow-title',(model.p.mode==='decode'?'Decode':'Prefill')+' 完整流程');txt('request-flow-summary',RF.summary(model.p.mode,model.d.S,model.d.T));txt('request-loop-note',model.p.mode==='decode'?'返回下一枚 Token；继续本轮循环，直到停止':'末位生成首个 Token，然后进入 Decode 循环');
  $('request-all-steps').innerHTML=RF.groups.map((group,g)=>'<div class="request-group-label">'+(g+1)+' · '+group.title+'</div>'+group.keys.map(key=>'<button data-request-step="'+key+'"'+(S.course&&key===id()?' aria-current="step"':'')+'>'+esc(RF.title(model,key))+'</button>').join('')).join('');
  $('cluster-steps').innerHTML=L.definitions.map((a,i)=>'<button data-cluster-step="'+i+'"><span>'+String(i+1).padStart(2,'0')+'</span>'+a[1]+'</button>').join('');
  if(S.course){txt('cluster-kicker',(S.courseIndex+1)+' / '+RF.items.length+' · '+(model.p.mode==='decode'?'Decode':'Prefill')+' · 第 '+(model.c.stage+1)+' 段');txt('cluster-title',requestLesson.name);txt('cluster-question',requestLesson.note);txt('cluster-intro',RF.summary(model.p.mode,model.d.S,model.d.T));txt('cluster-badge','PP '+model.PP+' × TP '+model.TP);txt('cluster-progress',(S.courseIndex+1)+' / '+RF.items.length);txt('cluster-next',id()==='advance'&&model.c.stage+1<model.PP?'进入下一流水段 →':'下一操作 →');$('cluster-prev').disabled=S.courseIndex===0&&!S.courseHistory.length;$('cluster-next').disabled=S.courseIndex===RF.items.length-1;$('cluster-vector-controls').hidden=true;return;}$('cluster-next').disabled=false;if(micro){txt('cluster-kicker','六类算子 · '+micro.family.name+' · TSP '+micro.chipId);txt('cluster-title',micro.op.name);txt('cluster-question',micro.shape);txt('cluster-badge',micro.family.unit);txt('cluster-progress',(micro.family.ops.findIndex(x=>x[0]===S.operator)+1)+' / '+micro.family.ops.length);txt('cluster-next','下一个算子 →');$('cluster-prev').disabled=micro.family.ops[0][0]===S.operator;$('cluster-vector-controls').hidden=true;return;}const def=L.definitions[S.index];$('cluster-steps').innerHTML=L.definitions.map((a,i)=>`<button data-cluster-step="${i}"${i===S.index?' aria-current="step"':''}><span>${String(i+1).padStart(2,'0')}</span>${a[1]}</button>`).join('');txt('cluster-intro',model.spec.detail);txt('cluster-kicker',(S.index+1)+' / '+L.definitions.length+' · 请求 '+model.c.request+' · 第 '+(model.c.stage+1)+' 段');txt('cluster-title',def[1]);txt('cluster-question',def[2]);txt('cluster-badge','PP '+model.PP+' × TP '+model.TP);txt('cluster-progress',(S.index+1)+' / '+L.definitions.length);$('cluster-prev').disabled=S.index===0;txt('cluster-next',id()==='advance'&&model.c.stage+1<model.PP?'进入下一阶段 →':S.index===14?'重看部署 →':'下一步 →');$('cluster-vector-controls').hidden=id()!=='link';const t=model.transfer(model.activation);S.vector=Math.min(S.vector,t.slots-1);$('cluster-vector').max=t.slots;$('cluster-vector').value=S.vector+1;txt('cluster-vector-count','/ '+t.slots+' 个向量槽');}
 function go(index,{autoplay=true,phase=null,keepSelection=false}={}){S.index=Math.max(0,Math.min(L.definitions.length-1,index));if(!model.active.some(c=>c.id===S.operatorChip))S.operatorChip=model.group[0];requestLesson=S.course?RF.build(model,id()):null;if(requestLesson?.source==='cluster')S.index=L.definitions.findIndex(v=>v[0]===id());micro=!S.course&&S.operator?O.build(model,S.operator,S.operatorChip,S.operatorParams):null;if(!keepSelection){S.selected=null;if(S.view==='chip')S.view='follow';}navigation();assignment();cost();const list=getPhases();$('cluster-phases').innerHTML=list.map((p,i)=>`<button data-cluster-phase="${i}"><span>${String(i+1).padStart(2,'0')}</span>${esc(p.title)}</button>`).join('');motion.load(list,{milliseconds:Number($('cluster-speed').value)*(list.length/4),autoplay,reduce:reduced.matches});if(phase!==null)motion.seek((Math.min(phase,list.length-1)+.01)/list.length);if(autoplay&&window.scrollY>$('cluster-main').offsetTop+220)$('cluster-main').scrollIntoView({block:'start',behavior:reduced.matches?'auto':'smooth'});}
 function rebuild(raw=S.config,patch=null,{reset=false}={}){stop();try{const base=patch?P.build({...window.GROQ_LAB.getModel().p,...patch}):window.GROQ_LAB.getModel(),next=C.build(base,raw);applying=true;if(patch)window.GROQ_LAB.apply(patch);applying=false;model=next;S.config={...model.c};if(S.course)S.courseHistory=[];if(reset&&S.course){S.courseHistory=[];setCoursePosition({index:0,stage:0});}S.valid=true;$('cluster-error').hidden=true;fill();go(reset?0:S.index,{autoplay:false,phase:0});}catch(e){applying=false;S.valid=false;txt('cluster-error',e.message+'。保留上次有效结果，请修正输入。');$('cluster-error').hidden=false;}}
 function advance(auto=false){if(!auto)stop();if(S.course){if(S.courseIndex===RF.items.length-1){stop();return;}S.courseHistory.push({index:S.courseIndex,stage:model.c.stage});setCoursePosition(RF.next(S.courseIndex,model.c.stage,model.PP));go(S.index);return;}if(micro){const ops=micro.family.ops,index=ops.findIndex(x=>x[0]===S.operator);S.operator=ops[(index+1)%ops.length][0];go(S.index);return;}if(id()==='advance'&&model.c.stage+1<model.PP){S.config.stage++;model=C.build(window.GROQ_LAB.getModel(),S.config);fill();go(4);}else go(S.index===14?0:S.index+1);}
 function canNextToken(){if(S.course)return S.valid&&model.valid&&model.d.S<32768&&['send','feedback'].includes(id())&&S.phase===getPhases().length-1&&S.settled;return !micro&&S.valid&&L.canNextToken(model,id(),S.phase,S.settled);}
 function status(){if(S.course){txt('cluster-answer',model.c.request+' · '+(canNextToken()?'已收到：芯片':model.p.mode==='decode'?'单个新位置计算中':'整段输入计算中'));$('cluster-next-token').disabled=!canNextToken();return;}txt('cluster-answer',micro?'本片算子机制演示':model.c.request+' · '+(id()==='feedback'||id()==='return'&&S.phase===3&&S.settled?'已收到：芯片':'当前轮计算中'));$('cluster-next-token').disabled=!canNextToken();}
 function nextToken(){if(!canNextToken())return;stop();S.config.stage=0;applying=true;window.GROQ_LAB.apply({mode:'decode',seq:model.d.S+1});applying=false;model=C.build(window.GROQ_LAB.getModel(),S.config);fill();if(S.course){S.courseIndex=0;S.courseHistory=[];go(0);}else go(2);}
 function inspect(key){stop();const b=M.nodes[key];if(!b)return;S.selected=key;const owner=/^C\d$/.test(b.owner)?model.chips[Number(b.owner[1])]:null;if(owner){S.cameraChip=owner.id;S.view='chip';S.zoom=1;}txt('cluster-probe-title',scene.address(key));txt('cluster-probe-body',owner?`此芯片属于副本 ${owner.replica}、第 ${owner.stage+1} 段，负责模型层 ${owner.layerStart+1}—${owner.layerEnd}、Q 头 ${owner.headStart}—${owner.headEnd-1}、KV 头 ${owner.kvHeads.join(',')}、FFN 通道 ${owner.ffStart}—${owner.ffEnd-1}。权重 ${P.bytes(owner.weights)}；已为独立请求预留 KV ${P.bytes(owner.kv)}。`:'该链路直接连接两颗 TSP。发送端准备数据，经 SerDes、物理线路、接收与对齐，最后由 Receive 写入目的 MEM。');if(b.kind==='wire'){S.view='follow';S.course=false;S.operator=null;const a=Number(key[4]),z=Number(key[5]);S.link=[a,z];go(8,{autoplay:false,phase:0,keepSelection:true});}else if(micro&&owner?.active){S.operatorChip=owner.id;go(S.index);}else{scene.render(model,getPatch(),S.selected);follow(getPhases()[S.phase]);}txt('cluster-address',scene.address(key));}
 function dialog(title,html){stop();window.GROQ_LAB.stop();txt('dialog-kicker','多芯片课堂');$('lab-dialog-content').innerHTML='<h2>'+esc(title)+'</h2>'+html;$('lab-dialog').showModal();$('lab-dialog-close').focus();}
 function sources(){dialog('分工、硬件与通信预算的依据','<div class="lab-dialog-links"><a href="http://pkamath.com/publications/papers/tsp-isca20.pdf" target="_blank" rel="noopener">ISCA 2020：Send / Receive、320 B 向量、16 条 ×4 C2C 链路</a><a href="https://hc34.hotchips.org/assets/program/conference/day2/Machine%20Learning/HotChips34%20-%20Groq%20-%20Abts%20-%20final.pdf" target="_blank" rel="noopener">Hot Chips 34：片间同步、HAC / SAC、Deskew、模型并行与 All-reduce</a></div><p class="lab-dialog-note">四片布线、PP / TP / 副本划分、主机采样和词表分片是本页明确选定的教学方案。公开资料支持硬件机制；不宣称这是 GroqCloud 当前某个模型的私有部署。</p><p class="lab-dialog-note">有效单向 C2C 带宽按每 lane 速率 × 4 lanes × 使用链路数 × 有效率 ÷ 8 计算。每邻接最多使用 8 条 ×4 链路，图中每片最多两个邻接；不把全部 16 个接口总带宽重复分给每条传输。</p><p class="lab-dialog-note">320 B 是向量指令粒度。槽位填充、接收窗口、传播和对齐开销为教学预算。没有模拟真实线码、FEC 报文、动态路由与编译器分块。性能数字为参数化估算。</p><p class="lab-dialog-note">KV 容量按常驻请求组分别计算，GQA 必要复制会增加占用。权重、KV、缓冲和工作区逐片检查；超出容量或分片形状不适配时不显示完整层路径性能。硬件机制依据公开论文与官方讲稿，资料入口均为网上链接。</p>');}
 function compare(){const a=C.build({...model.p,mode:'prefill'},model.c),b=C.build({...model.p,mode:'decode'},model.c);dialog('同一分工下，Prefill 与 Decode 的片间流量',table(['项目','Prefill','Decode'],[['本轮位置 T',a.d.T,b.d.T],['阶段激活 FP16',P.bytes(a.activation),P.bytes(b.activation)],['每片输出部分和 FP32',P.bytes(a.partial),P.bytes(b.partial)],['一次 All-reduce 全组发送',P.bytes(a.reduction.totalSent),P.bytes(b.reduction.totalSent)],['一次 All-reduce 时间',range(a.reduction.low,a.reduction.high),range(b.reduction.low,b.reduction.high)],['L 层设备路径',a.valid?range(a.pipelineLow,a.pipelineHigh):'条件不满足',b.valid?range(b.pipelineLow,b.pipelineHigh):'条件不满足']])+'<p class="lab-dialog-note">相同上下文 S 下，Decode 的激活只含一个新位置；历史 KV 仍留在各片。短消息的传播、对齐和固定开销可能比序列化时间更显著。这里未把片间预算当成完整网络服务延迟。</p>');}
 requestFlow=RF.create({container:$('cluster-request-overview'),assets:G,onSelect:group=>pickRequest(RF.groups[group].keys[0])});
 softwareFlow=window.GROQ_SOFTWARE_FLOW.create({container:$('cluster-software-flow'),assets:G,compact:true,onSelect:index=>{stop();S.selected=null;motion.seek((index+.01)/getPhases().length);motion.play();}});
 scene=window.GROQ_CLUSTER_SCENE.create({container:$('cluster-canvas'),assets:G,onSelect:inspect});
 motion=E.create({container:$('cluster-canvas'),assets:G,graph:()=> 'cluster6',resolveNode:scene.node,resolvePoint:scene.point,route:scene.route,paint:(p,index)=>{S.phase=index;S.cameraLocal=0;S.settled=false;scene.render(model,getPatch(),S.selected);softwareFlow.render(getPhases(),index,false);zoom();follow(p);txt('cluster-phase-count',(index+1)+' / '+getPhases().length);txt('cluster-phase-title',p.title);txt('cluster-explain',p.explain);txt('cluster-route',p.focus.map(scene.address).slice(0,3).join('；'));txt('cluster-address',S.selected?scene.address(S.selected):p.focus.map(scene.address).slice(0,2).join('；'));document.querySelectorAll('[data-cluster-phase]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.clusterPhase)===index)));sample();status();},onTime:({ratio,local})=>{S.cameraLocal=local;zoom();document.querySelector('#cluster-main .live-progress').value=ratio*100;txt('flow-latency',range(currentCost.low*ratio,currentCost.high*ratio));$('cluster-range').value=Math.round(ratio*1000);txt('cluster-percent',Math.round(ratio*100)+'%');const settled=local>=.9;if(S.settled!==settled){S.settled=settled;scene.render(model,getPatch(),S.selected);softwareFlow.render(getPhases(),S.phase,settled);sample();status();}},onStatus:running=>{txt('cluster-play',running?'暂停动画':'继续动画');$('cluster-play').setAttribute('aria-pressed',String(running));if(document.body.dataset.workspace==='cluster')document.body.classList.toggle('motion-paused',!running);},onEnd:()=>{if(!S.auto)return;if(S.course){if(id()==='feedback'){stop();return;}S.timer=setTimeout(()=>advance(true),500);return;}if(micro&&micro.family.ops.at(-1)[0]===S.operator){stop();return;}if(['feedback','overlap'].includes(id())){stop();return;}S.timer=setTimeout(()=>advance(true),500);}});
 $('show-cluster').addEventListener('click',()=>{window.GROQ_LAB.stop();document.body.dataset.workspace='cluster';document.querySelector('.skip').href='#cluster-main';$('show-cluster').setAttribute('aria-pressed','true');$('show-single').setAttribute('aria-pressed','false');model=C.build(window.GROQ_LAB.getModel(),S.config);fill();go(S.index,{autoplay:false,phase:S.phase});});
 function single(target){stop();window.GROQ_LAB.showSingle(target);document.querySelector('.skip').href='#lab-main';$('show-cluster').setAttribute('aria-pressed','false');$('show-single').setAttribute('aria-pressed','true');}
 $('show-single').addEventListener('click',()=>single());$('cluster-single-detail').addEventListener('click',()=>single(S.course&&model.base.steps.some(s=>s.id===id())?id():micro&&model.base.steps.some(s=>s.id===S.operator)?S.operator:id().includes('ffn')?'ffn_gate':id()==='input'?'pcie_in':'qk'));
 $('cluster-steps').addEventListener('click',e=>{const b=e.target.closest('[data-cluster-step]');if(b){stop();S.course=false;S.operator=null;if(S.valid)go(Number(b.dataset.clusterStep));}});$('cluster-phases').addEventListener('click',e=>{const b=e.target.closest('[data-cluster-phase]');if(b){stop();S.selected=null;motion.seek((Number(b.dataset.clusterPhase)+.01)/getPhases().length);}});$('cluster-chips').addEventListener('click',e=>{const b=e.target.closest('[data-cluster-chip]');if(b)inspect('C'+b.dataset.clusterChip+'_TITLE');});
 $('cluster-range').addEventListener('input',e=>{stop();S.selected=null;motion.seek(Number(e.target.value)/1000);});$('cluster-play').addEventListener('click',()=>{if(motion.running)stop();else if(S.valid)motion.play();});$('cluster-replay').addEventListener('click',()=>{stop();S.selected=null;if(S.valid)motion.restart();});$('cluster-speed').addEventListener('change',()=>motion.setDuration(Number($('cluster-speed').value)*getPhases().length/4));
 $('cluster-prev').addEventListener('click',()=>{if(S.valid)previous();});$('cluster-next').addEventListener('click',()=>{if(S.valid)advance();});$('cluster-next-token').addEventListener('click',nextToken);$('cluster-auto').addEventListener('click',()=>{if(S.auto){stop();return;}if(!S.valid)return;S.auto=true;S.selected=null;txt('cluster-auto','停止连续演示');$('cluster-auto').setAttribute('aria-pressed','true');motion.restart();});
 $('cluster-fit').addEventListener('click',()=>{S.view='board';S.zoom=1;zoom();});$('cluster-follow').addEventListener('click',()=>{S.view='follow';S.zoom=1;zoom();});$('cluster-minus').addEventListener('click',()=>{if(S.view==='board')S.view='follow';S.zoom=Math.max(.6,S.zoom-.2);zoom();});$('cluster-plus').addEventListener('click',()=>{if(S.view==='board')S.view='follow';S.zoom=Math.min(2.2,S.zoom+.2);zoom();});window.addEventListener('resize',()=>{if(document.body.dataset.workspace==='cluster')zoom();});
 for(const name of ['strategy','request','stage'])$('cluster-'+name).addEventListener('change',()=>{S.link=null;rebuild({...S.config,[name]:name==='stage'?Number($('cluster-stage').value):$('cluster-'+name).value},{},{reset:name==='strategy'});});
 $('cluster-form').addEventListener('submit',e=>e.preventDefault());$('cluster-form').addEventListener('input',()=>{stop();clearTimeout(editTimer);editTimer=setTimeout(()=>{const config={...S.config},patch={};for(const key of Object.keys(O.defaults))S.operatorParams[key]=Number($('op-'+key).value);document.querySelectorAll('[data-cluster-param]').forEach(el=>config[el.dataset.clusterParam]=Number(el.value)*Number(el.dataset.scale||1));document.querySelectorAll('[data-cluster-model]').forEach(el=>patch[el.dataset.clusterModel]=Number(el.value));rebuild(config,patch);},350);});
 $('cluster-vector').addEventListener('input',()=>{const v=Number($('cluster-vector').value);if(!Number.isInteger(v)||v<1||v>model.transfer(model.activation).slots)return;stop();S.vector=v-1;go(8,{autoplay:false,phase:S.phase});});$('cluster-vector-last').addEventListener('click',()=>{stop();S.vector=model.transfer(model.activation).slots-1;go(8,{autoplay:false,phase:0});});
 window.addEventListener('groq:pause',stop);$('cluster-restore').addEventListener('click',()=>{S.operator=null;S.operatorParams={...O.defaults};S.link=null;S.vector=0;rebuild(C.defaults,P.defaults,{reset:true});});$('cluster-sources').addEventListener('click',sources);window.addEventListener('groq:cluster-sources',sources);window.addEventListener('groq:cluster-compare',compare);window.addEventListener('groq:cluster-reset',()=>{stop();if(S.course){S.courseHistory=[];setCoursePosition({index:0,stage:0});}go(0);});window.addEventListener('groq:model',()=>{if(applying)return;stop();try{const previousMode=model.p.mode;model=C.build(window.GROQ_LAB.getModel(),S.config);S.config={...model.c};if(S.course&&previousMode!==model.p.mode){S.courseIndex=0;S.courseHistory=[];S.config.stage=0;model=C.build(window.GROQ_LAB.getModel(),S.config);}S.valid=true;$('cluster-error').hidden=true;fill();if(document.body.dataset.workspace==='cluster')go(S.index,{autoplay:false,phase:0});}catch(e){S.valid=false;txt('cluster-error',e.message);$('cluster-error').hidden=false;}});
 document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});document.addEventListener('keydown',e=>{if(document.body.dataset.workspace!=='cluster'||$('lab-dialog').open||$('detail-drawer').open||e.ctrlKey||e.metaKey||e.altKey||e.target.closest('input,textarea,select,button,a,[data-interactive=true]'))return;if(e.key==='ArrowRight'){e.preventDefault();if(S.valid)advance();}if(e.key==='ArrowLeft'){e.preventDefault();if(S.valid)previous();}if(e.code==='Space'){e.preventDefault();if(motion.running)stop();else if(S.valid)motion.play();}});
 $('operator-families').addEventListener('click',e=>{const b=e.target.closest('[data-family]');if(!b)return;stop();const f=O.families.find(x=>x.id===b.dataset.family);S.course=!f;if(S.course){S.courseHistory=[];setCoursePosition({index:0,stage:0});}S.operator=f?f.ops[0][0]:null;S.operatorChip=model.group[0];go(S.index);});
 $('software-operation').addEventListener('change',e=>{stop();if(S.course){pickRequest(e.target.value);return;}if(S.operator){S.operator=e.target.value;go(S.index);}else go(Number(e.target.value));});
 window.GROQ_REQUEST_COURSE={pick:pickRequest,getState:()=>({active:S.course,key:id(),index:S.courseIndex,stage:model.c.stage,mode:model.p.mode,S:model.d.S,T:model.d.T,request:model.c.request,replica:model.replica})};
 $('request-all-steps').addEventListener('click',e=>{const b=e.target.closest('[data-request-step]');if(b)pickRequest(b.dataset.requestStep);});
 fill();go(0,{autoplay:document.body.dataset.workspace==='cluster'});
})();
