/* UTF-8 · 指令、硬件与性能共享同一个整数时钟；原有完整请求课堂仍可切换。 */
(function(){
 'use strict';const C=window.GROQ_CYCLE,$=id=>document.getElementById(id),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),txt=(id,v)=>$(id).textContent=v,list=a=>'['+a.map(C.fmt).join(', ')+']',n=v=>Number(v.toFixed(3)).toLocaleString('en-US'),bytes=v=>v>=1024?n(v/1024)+' KiB':v+' B';
 const state={key:'q',params:{...C.defaults},sl:0,focus:'all',tracked:null};let model=C.build(state.key,state.params),snap,scene,clock;
 const unitLabel=u=>u.replace('MEM_','MEM '),table=(heads,rows)=>'<table><thead><tr>'+heads.map(h=>'<th>'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+rows.map(r=>'<tr>'+r.map(v=>'<td>'+v+'</td>').join('')+'</tr>').join('')+'</tbody></table>';
 function renderInstructions(s){$('cycle-live-instructions').innerHTML=s.units.map(u=>{
   const item=u.done.at(-1)||u.running[0]||u.waiting[0]||u.instruction,waiting=item&&s.cycle<item.consume+s.superlane,done=item&&s.cycle===item.ready+s.superlane;
   let value='—',note='本拍无操作数消费';if(item){if(waiting){value='valid = 0';note='c'+(item.consume+s.superlane)+' 消费操作数';}else if(done){value=list(item.values);note=item.kind==='write'?'已写入 a'+item.address:item.kind==='read'?'读出数据，本拍注入 SR':'功能结果产生';}else{value=item.inputs.map(i=>list(i.values.length>4?i.values.slice(0,4):i.values)).join(' / ')||'控制信号';note=item.inputs.map(i=>i.label).join(' / ')||'无数值操作数';}}
   const physical=s.physicalIssued.filter(i=>i.unit.startsWith(u.unit)),issue=physical.length?'发射 '+physical.map(i=>(u.unit.startsWith('MEM')?i.plane+':':'')+i.op.split(' ')[0]).join(' / '):'ICU 本拍 NOP',label=item?item.op:'NOP';return'<article class="cycle-lane"><header><b>'+unitLabel(u.unit)+'</b><span title="'+esc(issue)+'">'+esc(issue)+'</span></header><div class="cycle-pair"><button class="'+(item?'':'idle')+'" '+(item?'data-cycle-instruction="'+item.id+'"':'disabled')+' title="'+esc(item?item.stage+'；发射 c'+item.issue+'，本 SL 消费 c'+(item.consume+s.superlane)+'，输出 c'+(item.ready+s.superlane):'此 SL 没有活跃指令')+'">'+esc(label)+'</button><div class="cycle-data '+(done?'complete':'')+'">'+esc(value)+'<small>'+esc(note)+'</small></div></div></article>';
  }).join('');
  const start=Math.max(0,Math.min(model.lastEnd-4,s.cycle-2)),cycles=Array.from({length:5},(_,i)=>start+i);$('cycle-trace').innerHTML='<table><thead><tr><th>切片</th>'+cycles.map(c=>'<th class="'+(c===s.cycle?'current':'')+'">c'+c+'</th>').join('')+'</tr></thead><tbody>'+C.units.map(u=>'<tr><th>'+unitLabel(u).replace('MEM ','M')+'</th>'+cycles.map(c=>{const all=model.physicalProgram.filter(i=>i.unit.startsWith(u)&&i.issue===c),i=all[0];return'<td class="'+(c===s.cycle?'current':c>s.cycle?'future':'')+'"><button data-cycle-jump="'+c+'" title="'+esc(all.length?all.map(v=>v.unit+' '+v.op).join('；'):'NOP：无新指令')+'">'+esc(i?(all.length>1?all.length+'×':'')+i.op.split(/[ ·]/)[0]:'·')+'</button></td>';}).join('')+'</tr>').join('')+'</tbody></table>';
 }
 function render(c){snap=C.snapshot(model,c,state.sl);const s=snap;renderInstructions(s);scene.render(model,s,state.tracked);scene.focus(state.focus);txt('cycle-left-clock','C '+String(c).padStart(3,'0'));txt('cycle-clock','C '+String(c).padStart(3,'0'));txt('cycle-ns',n(s.ns)+' ns');txt('cycle-frequency',n(model.p.ghz)+' GHz');txt('cycle-first-latency',n(s.firstEnd/model.p.ghz)+' ns · c'+s.firstEnd);txt('cycle-total-latency',n(model.lastEnd/model.p.ghz)+' ns · c'+model.lastEnd);txt('cycle-edge-bytes',s.nowBytes+' B');txt('cycle-edge-bandwidth',n(s.bandwidth)+' GB/s');txt('cycle-total-bytes',bytes(s.bytes));txt('cycle-average','平均 '+n(s.averageGBs)+' GB/s · 不含指令取指');txt('cycle-completion',s.completed+' / 20 个 SL 写回完成');$('cycle-progress').value=c/model.lastEnd*100;txt('cycle-result',s.result?list(s.result):'尚未写回');txt('cycle-progress-label','C '+c+' / '+model.lastEnd);$('cycle-range').value=c;$('cycle-prev').disabled=c===0;$('cycle-next').disabled=c===model.lastEnd;$('cycle-prev-event').disabled=c===0;$('cycle-next-event').disabled=c===model.lastEnd;
  txt('cycle-edge-label','SL '+state.sl+' · C '+c);txt('cycle-stage-title',s.stage?.name||'等待所选 SL 的指令');const arrivals=s.streams.map(r=>'s'+r.bus+' 在 SR '+r.hop),complete=s.committed.map(i=>unitLabel(i.unit)+' '+i.op),consuming=s.consuming.map(i=>unitLabel(i.unit)+' '+i.op);txt('cycle-stage-explain',complete.length?'本拍完成：'+complete.join('；')+'。'+(s.result?'输出已写入 SRAM。':'结果才可供后续指令消费。'):consuming.length?'本拍消费：'+consuming.join('；')+'。操作数已在对应位置就绪。':arrivals.length?'传输中：'+arrivals.join('；')+'。下一拍前进一个 SR，原位置有效位清零。':'本拍没有新的数值结果。按计划推进指令或等待功能延迟；可点击“下一事件”。');
 }
 function rebuild({play=false}={}){clock?.stop();model=C.build(state.key,state.params);state.tracked=null;$('cycle-range').max=model.lastEnd;txt('cycle-title',model.lesson.name);txt('cycle-format',model.dtype);clock.seek(0);if(play)clock.play();}
 function status(running){txt('cycle-play',running?'暂停':clock?.cycle>=model.lastEnd?'重播':'播放');txt('cycle-play-state',running?'逐拍执行':clock?.cycle>=model.lastEnd?'已完成':'已暂停');$('cycle-play').setAttribute('aria-pressed',String(running));}
 function pause(){clock.stop();}
 function switchState(){const mode=document.body.dataset.workspace;['cycle','cluster','single'].forEach(k=>$('show-'+k).setAttribute('aria-pressed',String(mode===k)));if(mode!=='cycle')pause();}
 function currentDetail(){const s=snap;return '<h3>时钟边沿 C '+s.cycle+' · superlane '+s.superlane+'</h3><p>界面显示边沿之后的状态：本拍完成的数据先到达，随后按既定计划消费。消费者不能读取尚未产生的结果；流寄存器的有效值只在所处那一拍可用。</p>'+table(['切片','本拍 ICU 发射','所选 SL 的活动指令','操作数消费 / 输出'],s.units.map(u=>[esc(unitLabel(u.unit)),esc(u.dispatch?.op||'NOP'),u.running.concat(u.waiting,u.done).map(i=>esc(i.op)).join('<br>')||'—',u.running.concat(u.waiting,u.done).map(i=>'c'+(i.consume+s.superlane)+' / c'+(i.ready+s.superlane)).join('<br>')||'—']))+'<h3>本拍数据流</h3>'+table(['流 / 位置','发送者 / 接收者','当前数值','生存期'],s.streams.map(r=>['s'+r.bus+' / SR '+r.hop,esc(unitLabel(r.from)+' → '+unitLabel(r.to)),esc(list(r.values)),'仅 C '+s.cycle+' 有效；源发出于 C '+(r.start+s.superlane)]))+'<p>'+esc(model.lesson.note)+'</p><div class="cycle-callout">'+esc(model.scope)+'</div>';}
 function formulas(){return '<h3>本页的时间来自整数周期</h3><p>当前 C = '+snap.cycle+'，频率 f = '+n(model.p.ghz)+' GHz，所以 t = C / f = '+n(snap.ns)+' ns。观看速度只影响相邻画面相隔多久，不影响模拟时钟。</p>'+table(['关系','本页含义'],[['消费周期','发射周期 + superlane 编号 + d_skew'],['结果产生周期','消费周期 + d_func'],['数据到达周期','组内字节平面对齐后，再走所选公共路径的 '+model.p.hops+' 跳'],['SG4 组内对齐','各物理切片的 d_func 不变；四条指令的发射 / 写回错开 0—3 拍。界面 Read×4 / Write×4 是折叠的四条指令'],['相邻 SL 偏移','SL 0 到 SL 19 相差 19 拍；不是所有算子固定执行 20 拍'],['所选 SL 写回','c'+snap.firstEnd+' / '+n(model.p.ghz)+' = '+n(snap.firstEnd/model.p.ghz)+' ns'],['整个微程序写回','c'+model.lastEnd+' / '+n(model.p.ghz)+' = '+n(model.lastEnd/model.p.ghz)+' ns']])+'<h3>数据 SRAM 带宽</h3><p>每个物理 MEM 切片、每个 superlane 的一次字节流读写按 16 B 计。FP16 使用 SG2（两个流，32 B / SL），FP32 使用 SG4（四个流，64 B / SL）；四个数值仅是 16 个逻辑 lane 的可见窗口。四个独立切片按一拍错开发射，在组边界对齐。带宽按展开后的每条物理 Read / Write 分别记账。当前拍对所有 SL 的数据读出和写回相加为 '+snap.nowBytes+' B；所以本拍吞吐 = '+snap.nowBytes+' × '+n(model.p.ghz)+' = '+n(snap.bandwidth)+' GB/s。累计 '+snap.bytes+' B / '+n(snap.ns)+' ns = '+n(snap.averageGBs)+' GB/s（C = 0 时显示 0）。这里是本微程序的实际安排量，没有乘上全芯片峰值。</p><div class="cycle-callout">这是教学微程序的 latency，不是完整 Attention、FFN、单个输出 token 或请求 TTFT。复杂向量步骤显式存取中间结果以便学习，真实编译通常会融合并改变此计划。</div>';}
 const paramDefs=[['ghz','时钟 GHz',.1,3,.1],['hops','SR 距离（跳）',1,6,1],['skew','消费偏移 d_skew',0,2,1],['read','MEM 读取 d_func',1,8,1],['write','MEM 写回 d_func',1,8,1],['vector','VXM 功能延迟',1,8,1],['shuffle','SXM 功能延迟',1,8,1],['install','IW 安装延迟',1,8,1],['matrix','四项 MAC 窗口延迟',4,16,1]];
 function assumptions(){return '<div class="cycle-callout">公开机制 + 可核对的教学参数。这里没有真实编译器生成的指令 trace，不能据此声称某一 Groq 产品的硅片精确时序。</div><h3>修改参数，重新生成静态计划</h3><div class="cycle-param-grid">'+paramDefs.map(([k,label,min,max,step])=>'<label>'+label+'<input data-cycle-param="'+k+'" type="number" min="'+min+'" max="'+max+'" step="'+step+'" value="'+model.p[k]+'"></label>').join('')+'</div><p id="cycle-param-error" class="cycle-param-error" role="alert"></p><button class="primary-button" id="cycle-apply">应用并回到 C 0</button> <button id="cycle-defaults">恢复教学参数</button><h3>哪些有原始资料依据</h3>'+table(['内容','依据 / 口径'],[['相邻横向 SR 一周期一跳','ISCA 2020 流执行机制；Hot Chips 34 流寄存器示例。'],['20 个 tile / superlane，指令每拍北移一个','ISCA 2020 的指令 / 数据交错时序。SL 19 比 SL 0 晚 19 拍。'],['MEM 与独立 ICU','两个半区各 44 个 MEM 切片、每切片 20 个 tile；每个切片有自己的 ICU。图中 A0—A3、B0—B3 是两组各四个独立 MEM 切片；Bank 0 / 1 框折叠显示各片对应 bank，数值按字节流重组。'],['MXM 的 LW / IW / ABC / ACC','公开 ISA 分类。这里的寄存器、地址和微指令序列是符号化的教学分配；不是二进制反汇编。'],['VXM / SXM','VXM 做算术，SXM 做重排，MEM 做读写。VXM 的可见槽 0 只是本例安排，其他 ALU 并未消失。'],['频率 / d_func / d_skew / 距离','0.9 GHz 是论文中的频率背景；其余默认数值为教学选择，不能从屏幕图框距离推断真实路由。MXM 的四项例子不是实际 320×320 阵列的完整时序。'],['初始状态 / 数据格式','输入和指令已经部署；ICU 已预取计划。一个 FP32 lane 来自四个字节流 SG4；FP16 使用 SG2。显示 16 个 lane 中的前四项，其余 lane 仅初始化为零，后续数值不模拟、不参加四项归约。每个 SL 独立重复此例。'],['地址、bank、寄存器与算术','A / B 两组的字节平面按相邻 MEM 切片分配；组内发射偏移 0—3 拍，读出后走 3—0 跳，在共同 SR 边界对齐；写回反向展开。组边界之间再走界面设置的 h 跳。这是教学空间分配。地址按 bank 奇偶教学交错。向量计算以 JavaScript 数学函数 + FP32 舍入模拟，不复现硬件近似函数。中间结果显式存 SRAM，避免虚构无限 VXM 寄存器。'],['多芯片时钟','TSP 之间不能假设精确共享全局时钟。本逐周期模式限定单片；C2C 转到“多芯片与算子”学习。']])+'<p><a href="http://pkamath.com/publications/papers/tsp-isca20.pdf" target="_blank" rel="noopener">ISCA 2020 原论文</a> · <a href="https://hc34.hotchips.org/assets/program/conference/day2/Machine%20Learning/HotChips34%20-%20Groq%20-%20Abts%20-%20final.pdf" target="_blank" rel="noopener">Hot Chips 34 官方讲稿</a></p><p class="cycle-small">动画、源码和图形已内嵌，可离线使用；参考资料通过网上链接打开，需要联网。</p>';}
 function values(){return '<h3>当前硬件状态 · C '+snap.cycle+' / SL '+state.sl+'</h3>'+table(['切片 / 教学地址','数据','当前有效值'],Object.values(snap.store).map(v=>[unitLabel(v.unit)+' / a'+v.address,esc(v.label),v.valid?esc(list(v.values)):'尚未写入']))+'<h3>最终参考答案（不代表已执行）</h3><p>'+esc(model.lesson.formula)+'</p><p>输入 X = '+esc(list(model.input))+'；参考结果 = '+esc(list(model.expected))+'。</p><p>当前结果：'+(snap.result?esc(list(snap.result)):'尚未写回')+'。'+esc(model.scope)+'</p>'+(model.lesson.family==='matrix'?'<p>W 的四行分别为 [2,1,0,−1]、[0,1,2,0]、[−1,0,1,1]、[3,−1,0,2]。输出第一项 1×2 + 2×0 + 3×(−1) + 4×3 = 11。一个 MAC 格显示一个乘法项，ACC 显示沿该输出列累计的结果。</p>':'');}
 function program(){return '<h3>符号化静态指令计划</h3><p>PC# 是各 ICU 指令队列的序号，不是机器码地址。未发射的计划项仍然可查；下表中的输入 / 输出是计划依赖。点击周期可返回对应时钟边沿。</p>'+table(['发射','切片 / 指令','SL '+state.sl+' 消费','SL '+state.sl+' 输出','数据 / 依赖'],model.program.map(i=>['<button data-cycle-plan-jump="'+i.issue+'">c'+i.issue+'</button>',esc(unitLabel(i.unit))+'<br><code>'+esc(i.op)+'</code>','c'+(i.consume+state.sl),'c'+(i.ready+state.sl),esc(i.inputs.map(x=>x.label).join('，')||'控制')+'<br>'+esc(i.stage)]))+'<h3>逐个物理切片展开（含 SG2 / SG4）</h3>'+table(['切片','指令','发射','SL '+state.sl+' 消费 / 完成'],model.physicalProgram.map(i=>[esc(i.unit),esc(i.op),'c'+i.issue,'c'+(i.consume+state.sl)+' / c'+(i.ready+state.sl)]))+'<button id="cycle-export" class="cycle-export">导出当前教学计划 JSON</button>';}
 function open(section='explain'){
  pause();window.GROQ_LAB.stop();window.dispatchEvent(new Event('groq:pause'));const names={explain:'当前周期 · 指令与数据',formulas:'周期、latency 与带宽',values:'SRAM 地址与数值',parameters:'时序参数与原始依据',sources:'时序参数与原始依据',steps:'完整静态计划',deploy:'硬件和软件映射'};
  txt('cycle-dialog-title',names[section]||names.explain);$('cycle-dialog-body').innerHTML=section==='formulas'?formulas():section==='values'?values():['parameters','sources','deploy'].includes(section)?assumptions():section==='steps'?program():currentDetail();if(!$('cycle-dialog').open)$('cycle-dialog').showModal();$('cycle-dialog-body').scrollTop=0;$('cycle-dialog-close').focus();
 }
 scene=window.GROQ_CYCLE_SCENE.create({container:$('cycle-canvas'),assets:window.HARDWARE_SVGS,map:window.GROQ_CYCLE_MAP,onInspect:id=>{pause();if(/^SL\d+$/.test(id)){state.sl=Number(id.slice(2));$('cycle-sl').value=state.sl;}else{const owner=window.GROQ_CYCLE_MAP.nodes[id]?.owner;state.focus=id.startsWith('ICU_')?'icu':owner==='SR'?'stream':owner?.startsWith('MEM')?'memory':owner==='MXM'?'mxm':owner==='SXM'?'sxm':owner==='VXM'?'vxm':'all';$('cycle-focus').value=state.focus;}render(clock.cycle);}});
 clock=C.createClock({end:()=>model.lastEnd,onTick:render,onStatus:status,requestFrame:fn=>requestAnimationFrame(fn),cancelFrame:id=>cancelAnimationFrame(id),interval:()=>Number($('cycle-speed').value)});
 $('cycle-lesson').innerHTML=C.lessons.map(l=>'<option value="'+l.id+'">'+esc(l.name)+'</option>').join('');$('cycle-sl').innerHTML=Array.from({length:20},(_,s)=>'<option value="'+s+'">SL '+s+(s===0?' · 底部':s===19?' · 顶部':'')+'</option>').join('');
 $('cycle-lesson').addEventListener('change',()=>{state.key=$('cycle-lesson').value;rebuild({play:true});});$('cycle-sl').addEventListener('change',()=>{pause();state.sl=Number($('cycle-sl').value);render(clock.cycle);});$('cycle-focus').addEventListener('change',()=>{state.focus=$('cycle-focus').value;scene.focus(state.focus);});$('cycle-fit').addEventListener('click',()=>{state.focus='all';$('cycle-focus').value='all';scene.focus('all');});
 $('cycle-play').addEventListener('click',()=>clock.running?pause():clock.play());$('cycle-prev').addEventListener('click',()=>clock.seek(clock.cycle-1));$('cycle-next').addEventListener('click',()=>clock.seek(clock.cycle+1));$('cycle-range').addEventListener('input',()=>clock.seek(Number($('cycle-range').value)));$('cycle-prev-event').addEventListener('click',()=>clock.seek(C.nextEvent(model,clock.cycle,state.sl,-1)));$('cycle-next-event').addEventListener('click',()=>clock.seek(C.nextEvent(model,clock.cycle,state.sl,1)));$('cycle-restart').addEventListener('click',()=>{clock.seek(0);clock.play();});
 for(const [id,section]of [['cycle-assumptions','parameters'],['cycle-program','steps'],['cycle-values-button','values'],['cycle-formulas','formulas'],['cycle-stage-detail','explain']])$(id).addEventListener('click',()=>open(section));
 $('cycle-live-instructions').addEventListener('click',e=>{const b=e.target.closest('[data-cycle-instruction]');if(!b)return;pause();state.tracked=b.dataset.cycleInstruction;render(clock.cycle);const i=model.program.find(i=>i.id===state.tracked);txt('cycle-stage-explain','追踪 '+unitLabel(i.unit)+' 的 '+i.op+'：c'+i.issue+' 发射；c'+(i.consume+state.sl)+' 消费；c'+(i.ready+state.sl)+' 产生结果。左侧紫色 SL 格跟踪此项的第一条物理指令；Read×4 / Write×4 的时间是组边界对齐时间。');});
 $('cycle-trace').addEventListener('click',e=>{const b=e.target.closest('[data-cycle-jump]');if(b)clock.seek(Number(b.dataset.cycleJump));});
 $('cycle-dialog-close').addEventListener('click',()=>$('cycle-dialog').close());$('cycle-dialog').addEventListener('click',e=>{if(e.target===$('cycle-dialog'))$('cycle-dialog').close();});
 $('cycle-dialog-body').addEventListener('click',e=>{
  const b=e.target.closest('button');if(!b)return;if(b.dataset.cyclePlanJump!==undefined){$('cycle-dialog').close();clock.seek(Number(b.dataset.cyclePlanJump));}
  if(b.id==='cycle-apply'||b.id==='cycle-defaults'){try{const raw=b.id==='cycle-defaults'?{...C.defaults}:Object.fromEntries(Array.from($('cycle-dialog-body').querySelectorAll('[data-cycle-param]')).map(el=>[el.dataset.cycleParam,Number(el.value)]));C.build(state.key,raw);state.params=raw;rebuild();$('cycle-dialog').close();}catch(error){txt('cycle-param-error',error.message+'。保留上次有效计划。');}}
  if(b.id==='cycle-export'){const data={说明:model.kind,范围:model.scope,参数:model.p,课程:model.lesson,指令:model.program,物理切片指令:model.physicalProgram,数据路径:model.routes,最后周期:model.lastEnd};const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:'application/json;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='Groq_逐周期教学计划_'+state.key+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 });
 $('show-cycle').addEventListener('click',()=>{window.GROQ_LAB.stop();window.dispatchEvent(new Event('groq:pause'));document.body.dataset.workspace='cycle';document.querySelector('.skip').href='#cycle-main';switchState();render(clock.cycle);});for(const id of ['show-cluster','show-single','cluster-single-detail'])$(id).addEventListener('click',switchState);
 window.addEventListener('groq:pause',pause);window.addEventListener('groq:cycle-reset',()=>{clock.seek(0);clock.play();});window.addEventListener('groq:cycle-sources',()=>open('sources'));
 document.addEventListener('visibilitychange',()=>{if(document.hidden)pause();});document.addEventListener('keydown',e=>{if(document.body.dataset.workspace!=='cycle'||$('cycle-dialog').open||$('detail-drawer').open||$('lab-dialog').open||e.ctrlKey||e.metaKey||e.altKey||e.target.closest('input,textarea,select,button,a,[data-interactive=true]'))return;if(e.key==='ArrowRight'){e.preventDefault();clock.seek(clock.cycle+1);}if(e.key==='ArrowLeft'){e.preventDefault();clock.seek(clock.cycle-1);}if(e.code==='Space'){e.preventDefault();clock.running?pause():clock.play();}});
 window.GROQ_CYCLE_APP={open,pause,getModel:()=>model,getSnapshot:()=>snap,seek:c=>clock.seek(c)};rebuild({play:document.body.dataset.workspace==='cycle'});switchState();
})();
