/* UTF-8 · LPX 分层结构、公开模型配置与可复算的情景参数。 */
(function(root){
'use strict';
const sources={article:'https://developer.nvidia.com/blog/inside-nvidia-groq-3-lpx-the-low-latency-inference-accelerator-for-the-nvidia-vera-rubin-platform/',rack:'https://developer-blogs.nvidia.com/wp-content/uploads/2026/03/Groq-3-LPX.webp',tray:'https://developer-blogs.nvidia.com/wp-content/uploads/2026/03/LPX02-Groq3LPX_Compute_Tray.webp',chip:'https://developer-blogs.nvidia.com/wp-content/uploads/2026/03/Groq-3-Architecture.webp',afd:'https://developer-blogs.nvidia.com/wp-content/uploads/2026/03/Decode-Loop.webp',qwen:'https://huggingface.co/Qwen/Qwen3.8-27B/blob/main/config.json'};
const hardware={trays:32,chipsPerTray:8,chips:256,sramPerChip:500e6,sramBandwidth:150e12,fp8Flops:1.2e15,ethernetBits:400e9,c2cBits:112e9,c2cLinks:96};
sources.flash='https://huggingface.co/Qwen/Qwen3.8-Flash-Next/blob/main/config.json';sources.flashCard='https://huggingface.co/Qwen/Qwen3.8-Flash-Next';
const models={q27:{id:'q27',name:'Qwen3.8-27B',parameters:27e9,verified:true,layers:64,hidden:5120,intermediate:17408,heads:24,kvHeads:4,headDim:256,fullLayers:16,linearLayers:48,tp:2},flash:{id:'flash',name:'Qwen3.8-Flash-Next',parameters:125e9,ngramParameters:51e9,mtpParameters:4e9,activeParameters:6e9,verified:true,moe:true,layers:48,hidden:2560,intermediate:640,heads:24,kvHeads:2,headDim:256,fullLayers:12,linearLayers:36,experts:512,topK:10,sharedExperts:1,tp:1}};
const exampleExperts=[3,67,126,139,198,257,321,389,450,507];
const levels=[{id:'external',name:'外部系统',title:'Prompt 从用户侧进入',hint:'服务接入 → Rubin GPU → Ethernet → LPX',source:'afd'},{id:'rack',name:'LPX 机架',title:'32 个槽位，256 颗 LPU',hint:'选择任意槽位，再打开对应的 1U 计算托盘',source:'rack'},{id:'tray',name:'1U 计算托盘',title:'沿接口进入刀片内部',hint:'前部网络接口 · Host CPU · Fabric 扩展逻辑 · 8 颗 LPU',source:'tray'},{id:'fabric',name:'8 芯片互联',title:'同一 Token，分发给 FFN 分片',hint:'激活复制到 TP 两片；返回的是部分和与 FFN 输出',source:'tray'},{id:'chip',name:'芯片内部',title:'指令与数据进入功能区',hint:'MEM → SXM → MXM → VXM；芯片布局依据图 3',source:'chip'}];
const steps=[
{id:'request',title:'提交 Prompt',level:'external',from:'CLIENT',to:'SERVICE',instruction:'HTTP 请求 / 服务接入',data:'UTF-8 Prompt',kind:'prompt',note:'原始文本首先到达接入服务，尚未进入 LPU。'},
{id:'tokens',title:'分词与 GPU Prefill',level:'external',from:'SERVICE',to:'RUBIN',instruction:'分词、提交 Prefill',data:'Token IDs / 输入上下文',kind:'tokens',note:'输入 Token 数是情景参数，页面不伪造真实 tokenizer 的 ID。Prefill 由 Rubin GPU 执行。'},
{id:'attention',title:'GPU Decode Attention',level:'external',from:'RUBIN',to:'ETH',instruction:'GPU Attention / 状态更新',data:'本层 Decode 激活',kind:'activation',note:'27B 的 64 层由 48 个 Gated DeltaNet 和 16 个完整 Attention 层组成；这些状态保留在 GPU 一侧。'},
{id:'rack',title:'激活进入 LPX 机架',level:'rack',from:'UPLINK',to:'SLOT',instruction:'AFD 路由到承载本层 FFN 的托盘',data:'BF16 中间激活',kind:'ethernet',note:'网络传入的是 Attention 之后的激活。机架不是把原始 Prompt 直接交给 MXM。'},
{id:'ingress',title:'托盘网络接收',level:'tray',from:'ETH_PORT',to:'NIC',instruction:'400 Gb/s Ethernet / 网络接收',data:'接收激活',kind:'ethernet',note:'图 2 标注前部 Ethernet、BlueField-4 DPU 或 ConnectX-9 NIC；两者是配置选项。'},
{id:'fabric',title:'Fabric 交给 LPU',level:'tray',from:'NIC',to:'CHIP_ROOT',route:['NIC','FE','CHIP_ROOT'],instruction:'网络 → Fabric 扩展逻辑 → 根片',data:'LPU 输入激活',kind:'handoff',note:'Host CPU 负责运行时控制；动画沿网络、Fabric 与根片的功能关系展开，未公开的具体 DMA 路线不作物理布线推定。'},
{id:'broadcast',title:'TP 两片共享输入',level:'fabric',from:'CHIP_ROOT',to:'CHIP_PEER',instruction:'C2C 发送 / 接收输入副本',data:'同一 Token 的相同激活',kind:'broadcast',note:'示例将每层 FFN 沿中间通道切成两份。Token 没有被切成两半，两片都接收相同的隐藏激活。'},
{id:'load',title:'C2C → MEM',level:'chip',chipPhase:0,instruction:'C2C Receive / MEM 写入',data:'输入 x，形状 [1, D]',kind:'c2c',note:'进入选中的 LPU 后，激活写入片上 SRAM。权重已在部署时分配，不随每个 Token 重新下发。'},
{id:'weights',title:'MEM / VXM / SXM 准备',level:'chip',chipPhase:2,instruction:'MEM 读权重 / VXM 格式转换 / SXM 重排',data:'Wgate、Wup 与输入 x',kind:'weight',note:'每片有 8704 个中间通道。读出 Gate / Up 权重；VXM 准备计算格式，SXM 重排。FP8 峰值下界假设输入也转换为 FP8，未模拟量化误差与元数据。'},
{id:'gateup',title:'MXM：Gate / Up',level:'chip',chipPhase:3,instruction:'MXM：g = xWgate；u = xWup',data:'两路 FFN 中间结果',kind:'gateup',note:'本片分别计算 Gate 与 Up 投影，矩阵尺寸 [1,5120] × [5120,8704]。两片分别拥有不同权重列。'},
{id:'silu',title:'VXM：SiLU 与门控',level:'chip',chipPhase:4,instruction:'VXM：h = SiLU(g) ⊙ u',data:'本片 FFN 中间激活',kind:'vector',note:'SiLU(g)=g/(1+exp(−g))，再逐元素乘 u。公开文章未提供该向量序列的延迟。'},
{id:'down',title:'MXM：Down 部分和',level:'chip',chipPhase:3,instruction:'MXM：y_partial = hWdown',data:'FP32 隐藏维度部分和',kind:'down',note:'每片用 [1,8704] × [8704,5120] 生成 D 维部分和，尚不能当作完整 FFN 输出。'},
{id:'reduce',title:'C2C 传回部分和',level:'fabric',from:'CHIP_PEER',to:'CHIP_ROOT',instruction:'C2C 发送部分和 / 根片 VXM 求和',data:'FP32 部分和 → 完整 FFN 结果',kind:'reduce',note:'示例将另一分片的部分和传回根片。根片求和后转换为 BF16；没有把两个部分和当作两个输出 Token。'},
{id:'return',title:'FFN 输出返回 GPU',level:'tray',from:'CHIP_ROOT',to:'ETH_PORT',route:['CHIP_ROOT','FE','NIC','ETH_PORT'],instruction:'根片 → Fabric → 网络接口 → GPU',data:'BF16 FFN 输出激活',kind:'ethernet',note:'完整隐藏激活经 Fabric 与网络接口返回 Rubin GPU，继续残差及后续层；下一层 Attention 仍由 GPU 执行。右侧时间仅对应 Ethernet 序列化，板内交接延迟未公开。'},
{id:'output',title:'后续层、采样与返回',level:'external',from:'RUBIN',to:'CLIENT',instruction:'重复各层 AFD / 采样 / 反分词',data:'输出 Token → 文本片段',kind:'output',note:'后续层重复 GPU Attention ↔ LPX FFN。最终词表头与采样后才产生输出 Token；本页不执行真实模型推理。'}
];
function configuration(id='q27',weightBytes=1){const m=models[id]||models.q27,w=(m.parameters+(m.ngramParameters||0)+(m.mtpParameters||0))*weightBytes,minChips=Math.ceil(w/hardware.sramPerChip),base={...m,weightBytes,totalWeightBytes:w,minChips,minTrays:Math.ceil(minChips/8),minRacks:Math.ceil(minChips/256)};if(m.moe){const ep=weightBytes===1?8:16,expertsPerChip=m.experts/ep,expertWeightBytes=3*m.hidden*m.intermediate*weightBytes,routerWeightBytes=m.hidden*m.experts*weightBytes,shardWeightBytes=expertsPerChip*expertWeightBytes,rootWeightBytes=shardWeightBytes+expertWeightBytes+routerWeightBytes,assignedChips=m.layers*ep;return{...base,ep,expertsPerChip,expertWeightBytes,routerWeightBytes,shardWeightBytes,rootWeightBytes,ffnWeightBytes:(expertWeightBytes*(m.experts+1)+routerWeightBytes)*m.layers,assignedChips,assignedTrays:assignedChips/8,assignedRacks:Math.ceil(assignedChips/256)};}const ffnWeightBytes=3*m.hidden*m.intermediate*m.layers*weightBytes;return{...base,ffnWeightBytes,shardWeightBytes:ffnWeightBytes/(m.layers*m.tp),assignedChips:m.layers*m.tp,assignedTrays:Math.ceil(m.layers*m.tp/8),assignedRacks:1};}
function assignment(id,layer=1,weightBytes=1,expert=67){const m=models[id]||models.q27;layer=Math.max(1,Math.min(m.layers,Math.trunc(layer)));if(m.moe){const cfg=configuration(id,weightBytes),base=(layer-1)*cfg.ep,globalPeer=base+Math.floor(expert/cfg.expertsPerChip),rootSlot=Math.floor(base/8),peerSlot=Math.floor(globalPeer/8);return{layer,expert,ep:cfg.ep,expertsPerChip:cfg.expertsPerChip,rack:Math.floor(peerSlot/32),slot:peerSlot%32,rootRack:Math.floor(rootSlot/32),rootSlot:rootSlot%32,root:0,peer:globalPeer%8,globalRoot:base,globalPeer,channels:m.intermediate,activeChips:[...new Set([base,...exampleExperts.map(e=>base+Math.floor(e/cfg.expertsPerChip))])],participantSlots:Array.from({length:cfg.ep/8},(_,i)=>rootSlot+i)};}const first=(layer-1)*m.tp;return{layer,rack:0,slot:Math.floor(first/8),rootRack:0,rootSlot:Math.floor(first/8),root:first%8,peer:first%8+1,globalRoot:first,globalPeer:first+1,channels:m.intermediate/m.tp};}
function chipInfo(state,rack=state.rack||0,slot=state.slot,chip=state.chip){const m=models[state.model],cfg=configuration(state.model,state.weightBytes),global=rack*256+slot*8+chip,layer=Math.floor(global/(m.moe?cfg.ep:m.tp))+1;if(layer>m.layers)return{global,assigned:false,label:'备用'};if(!m.moe)return{global,layer,assigned:true,label:'层 '+layer+' · 分片 '+global%2};const owner=global%cfg.ep,start=owner*cfg.expertsPerChip,end=start+cfg.expertsPerChip-1,activeExperts=exampleExperts.filter(e=>e>=start&&e<=end);return{global,layer,assigned:true,start,end,owner,shared:owner===0,activeExperts,label:'层 '+layer+' · E'+start+'–'+end+(owner===0?' +共享':'')};}
function location(state,step){const a=assignment(state.model,state.layer,state.weightBytes,state.expert),moe=models[state.model].moe,useRoot=moe&&['rack','ingress','fabric','router','return'].includes(step.id);return useRoot?{rack:a.rootRack,slot:a.rootSlot,chip:a.root}:{rack:a.rack,slot:a.slot,chip:moe?a.peer:a.root};}
function metric(state,step){if(models[state.model].moe)return moeMetric(state,step);const cfg=configuration(state.model,state.weightBytes),m=models[state.model],a=assignment(state.model,state.layer),x=m.hidden*2,y=m.hidden*4;let bytes=null,bandwidth=null,flops=null,computeNs=null,memoryNs=null,ns=null,rule='此段固定延迟与效率未公开。',scope='当前动作';
if(step.kind==='prompt'){bytes=new TextEncoder().encode(state.prompt).length;rule='实际输入文本的 UTF-8 字节；不含 HTTP、TLS 与网络封装。';}
if(step.kind==='tokens'){bytes=state.tokens*4;rule='情景 Token 数 × 4 B / ID；不是本页实际分词结果。';}
if(['activation','handoff'].includes(step.kind))bytes=x;
if(['ethernet','broadcast','c2c'].includes(step.kind)){bytes=x;bandwidth=step.kind==='ethernet'?hardware.ethernetBits/8:hardware.c2cBits/8;rule=step.kind==='ethernet'?'激活字节 ÷ (400 Gb/s ÷ 8)，单个端口裸数据序列化下界。':'激活字节 ÷ (112 Gb/s ÷ 8)，采用一条 C2C 链路的裸数据下界。';}
if(step.kind==='reduce'){bytes=y;bandwidth=hardware.c2cBits/8;rule='单个 FP32 部分和的传输下界；根片求和与转换另计，未计为零。';}
if(['weight','gateup','down'].includes(step.kind)&&m.verified){const weights=m.hidden*(m.intermediate/m.tp)*(step.kind==='down'?1:2);bytes=weights*state.weightBytes;memoryNs=bytes/hardware.sramBandwidth*1e9;if(step.kind!=='weight'){flops=2*weights;computeNs=state.weightBytes===1?flops/hardware.fp8Flops*1e9:null;}ns=state.weightBytes===1?Math.max(memoryNs,computeNs||0):memoryNs;scope='本片权重与算量';rule=step.kind==='weight'?'本片 Gate / Up 权重 ÷ 全芯片 150 TB/s；不代表单次 SRAM 访问延迟。':state.weightBytes===1?'max(权重 ÷ 150 TB/s, FLOPs ÷ 1.2 PFLOPS FP8)，仅为理想资源下界。':'BF16 峰值未在本文给出，只列权重读取下界，不使用 FP8 峰值推算 BF16。';}
if(step.kind==='vector'&&m.verified){bytes=m.intermediate/m.tp*2;rule='本片 BF16 中间激活；SiLU 与门控延迟未公开。';}
if(bytes!==null&&bandwidth)ns=bytes/bandwidth*1e9;
let payloadBytes=bytes;if(m.verified&&step.kind==='gateup')payloadBytes=2*(m.intermediate/m.tp)*2;if(m.verified&&step.kind==='down')payloadBytes=y;
return{cfg,a,bytes,payloadBytes,bandwidth,ns,flops,computeNs,memoryNs,scope,rule,activationBytes:x,partialBytes:y};}
function stepsFor(id){if(!models[id].moe)return steps;const overrides={attention:{title:'GPU DeltaNet / QSA',instruction:'GPU DeltaNet / QSA / Gated Residual',note:'Flash-Next 的 48 层包含 36 层 Gated DeltaNet 和 12 层 QSA；Attention 状态、n-gram embedding 与残差留在 GPU。本页展开语言 Decode 的 MoE 分支。'},fabric:{note:'激活交给本层 MoE 根片，先计算路由。这里的网络 / Fabric 路径是功能展开，未宣称实际 DMA 布线。'},broadcast:{title:'EP 派发至命中专家',instruction:'按专家所在 LPU 派发 x',data:'所选专家的输入 x',note:'示例命中 E3、67、126、139、198、257、321、389、450、507，另有根片共享专家；这些编号为演示选择，不是实际 Prompt 的 Top-10。画面跟踪所选专家，并标记其他参与芯片。'},weights:{title:'读取所选专家权重',instruction:'MEM 读专家权重 / VXM 转换 / SXM 重排',data:'专家 Wgate / Wup',note:'只读取当前命中专家的权重；各专家维度为 D=2560、F=640。其余常驻专家仍占 SRAM，但不参与此 Token 的矩阵计算。FP8 下界假设输入转换为 FP8。'},gateup:{title:'MXM：专家 Gate / Up',instruction:'MXM：gₑ = xWgateₑ；uₑ = xWupₑ',data:'专家两路中间结果',note:'当前专家执行 [1,2560] × [2560,640] 的两个投影。右侧算量属于单个专家，不是 125B 参数全部参与一次计算。'},silu:{title:'VXM：专家 SiLU / 门控',instruction:'VXM：hₑ = SiLU(gₑ) ⊙ uₑ',data:'专家中间激活',note:'当前专家的 640 个中间元素逐项完成 SiLU 与门控；向量序列延迟未公开。'},down:{title:'MXM：专家 Down',instruction:'MXM：yₑ = hₑWdownₑ',data:'FP32 专家输出',note:'[1,640] × [640,2560] 产生本专家的完整 D 维输出。不同专家的输出需要按路由权重加权，不是 Dense TP 的无权部分和。'},reduce:{title:'专家回传与加权汇总',instruction:'根片 VXM：Σ pₑyₑ + 共享专家门控输出',data:'专家输出 → 加权汇总',note:'所选专家输出返回根片，根片按路由系数合并十个专家，再加共享专家的门控输出。只演示所选专家路径；同片输出无需 C2C，远端路径经 C2C spine。'},return:{data:'BF16 MoE 输出激活',note:'根片汇总后的 MoE 输出经 Fabric / 网络返回 GPU；Gated Residual 与下一层继续在 GPU。右侧只计单个 Ethernet 端口的序列化下界。'},output:{note:'重复 48 层 GPU Attention ↔ LPX MoE 后再经过词表头、采样与反分词。n-gram / MTP 权重容量另列；本页没有执行真实推理或 MTP 推测解码。'}};const out=steps.map(s=>({...s,...overrides[s.id]}));out.splice(6,0,{id:'router',title:'MXM 路由 / VXM Top-10',level:'chip',chipPhase:3,instruction:'MXM：xWrouter / VXM：Top-10',data:'512 个路由分数',kind:'router',note:'路由矩阵为 [2560,512]。MXM 产生 512 个分数，VXM 选择十个路由专家；一个共享专家始终参与。给出的资源下界仅含矩阵部分，Top-10 的向量延迟未公开。'});return out;}
function moeMetric(state,step){const cfg=configuration('flash',state.weightBytes),m=models.flash,a=assignment('flash',state.layer,state.weightBytes,state.expert),x=m.hidden*2,y=m.hidden*4;let bytes=null,payloadBytes=null,bandwidth=null,flops=null,computeNs=null,memoryNs=null,ns=null,scope='当前动作',rule='此段固定延迟与效率未公开。';
 if(step.kind==='prompt'){bytes=new TextEncoder().encode(state.prompt).length;rule='实际输入文本的 UTF-8 字节，不含网络封装。';}
 if(step.kind==='tokens'){bytes=state.tokens*4;rule='情景 Token 数 × 4 B / ID，不是实际 tokenizer 结果。';}
 if(['activation','handoff'].includes(step.kind))bytes=x;
 if(['ethernet','broadcast','c2c','reduce'].includes(step.kind)){bytes=step.kind==='reduce'?y:x;bandwidth=(step.kind==='ethernet'?hardware.ethernetBits:hardware.c2cBits)/8;scope=step.kind==='ethernet'?'单个网络端口':'所选专家的一条链路';rule='当前数据 ÷ '+(step.kind==='ethernet'?'400 Gb/s 单口':'112 Gb/s 单条 C2C')+'，裸数据序列化下界；协议与等待另计。';if(['broadcast','reduce'].includes(step.kind)&&a.globalPeer===a.globalRoot){bytes=0;rule='所选专家与根片同片，本段不经过 C2C。片内移动与向量汇总延迟未公开。';}}
 if(['weight','gateup','down','router'].includes(step.kind)){const count=step.kind==='router'?m.hidden*m.experts:m.hidden*m.intermediate*(step.kind==='down'?1:2);bytes=count*state.weightBytes;memoryNs=bytes/hardware.sramBandwidth*1e9;if(step.kind!=='weight'){flops=2*count;computeNs=state.weightBytes===1?flops/hardware.fp8Flops*1e9:null;}ns=Math.max(memoryNs,computeNs||0);scope=step.kind==='router'?'路由矩阵，不含 Top-10':'当前一个专家';rule=state.weightBytes===1?'max(本次权重 ÷ 150 TB/s, FLOPs ÷ 1.2 PFLOPS FP8)，资源下界。':'BF16 仅给权重读取下界，未使用 FP8 计算峰值。';}
 if(step.kind==='vector'){bytes=m.intermediate*2;scope='当前一个专家';rule='640 个 BF16 中间元素，SiLU 与门控延迟未公开。';}
 if(bytes!==null&&bandwidth)ns=bytes/bandwidth*1e9;payloadBytes=bytes;
 if(step.kind==='router')payloadBytes=m.experts*4;
 if(step.kind==='gateup')payloadBytes=2*m.intermediate*2;
 if(step.kind==='down'||step.kind==='reduce')payloadBytes=y;
 return{cfg,a,bytes,payloadBytes,bandwidth,ns,flops,computeNs,memoryNs,scope,rule,activationBytes:x,partialBytes:y};
}
const maps={};function make(id,w,h){return maps[id]={width:w,height:h,boxes:{},links:[]};}function box(m,id,label,x,y,w,h,z=0,depth=10,color='frame',kind='part',extra={}){return m.boxes[id]={id,label,x,y,w,h,z,depth,color,kind,...extra};}
let n=make('external',1120,760);
box(n,'CLIENT','用户终端',35,260,185,145,20,16,'host','device');box(n,'KEYBOARD','',25,417,205,48,0,8,'host');box(n,'SERVICE','接入服务 / 分词',310,280,190,200,0,38,'host','device');box(n,'SERVICE_PORT','HTTP / Dynamo',328,414,154,35,42,4,'port');box(n,'RUBIN','Vera Rubin NVL72',605,145,185,365,0,68,'mem','device');for(let i=0;i<9;i++)box(n,'GPU'+i,'',620,207+i*28,155,20,69,3,'mem');box(n,'ETH','Spectrum-X Ethernet',330,585,440,53,0,25,'port','device');box(n,'LPX','Groq 3 LPX',915,145,160,365,0,68,'mxm','device');for(let i=0;i<16;i++)box(n,'LPX_ROW'+i,'',929,206+i*16,132,12,69,3,'mxm');
n.links=[['CLIENT','SERVICE'],['SERVICE','RUBIN'],['RUBIN','ETH'],['ETH','LPX']];
n=make('rack',1080,890);box(n,'RACK_BASE','',308,18,410,837,0,95,'host','base');box(n,'RAIL_L','',295,18,20,837,92,20,'wire');box(n,'RAIL_R','',711,18,20,837,92,20,'wire');box(n,'RACK_TOP','LPX · 32 × 1U',315,35,396,72,100,17,'host');box(n,'POWER_TOP','配电 / 机柜设施',318,111,390,59,100,12,'host');
for(let i=0;i<32;i++){box(n,'SLOT'+i,'槽位 '+String(i).padStart(2,'0'),320,182+i*17,385,14,100,16,'mxm','slot',{slot:i});box(n,'HANDLE'+i,'',616,186+i*17,64,5,117,5,'wire','handle',{slot:i});}
box(n,'POWER_BOTTOM','配电 / 机柜设施',318,735,390,80,100,16,'host');box(n,'SPINE','后部 C2C spine',820,167,100,573,0,34,'port','device');box(n,'UPLINK','Ethernet 接入',64,352,184,75,0,20,'port','device');box(n,'RUBIN_PEER','Rubin GPU',64,215,184,93,0,28,'mem','device');n.links=[['RUBIN_PEER','UPLINK']];
n=make('tray',1120,790);box(n,'TRAY_BASE','',80,57,960,662,0,18,'host','base');box(n,'TRAY_RAIL_L','',80,58,16,655,18,34,'wire');box(n,'TRAY_RAIL_R','',1024,58,16,655,18,34,'wire');box(n,'SPINE_L','C2C spine',180,78,260,35,20,15,'port','device');box(n,'SPINE_R','C2C spine',656,78,260,35,20,15,'port','device');
for(let i=0;i<8;i++){const x=177+(i%4)*195,y=143+Math.floor(i/4)*99;box(n,'CHIP'+i,'LPU '+i,x,y,160,78,28,19,'mxm','chip',{chip:i});box(n,'DIE'+i,'',x+27,y+21,106,35,48,3,'mem');}
box(n,'FE','Fabric 扩展逻辑',211,372,346,97,25,28,'vxm','device');box(n,'FDRAM','扩展 DRAM ≤256GB',587,374,320,79,22,16,'mem');box(n,'HOST','Host CPU',404,519,204,112,25,32,'icu','device');box(n,'HDRAM','Host DRAM ≤128GB',160,501,200,133,20,18,'mem');box(n,'NIC','BlueField-4 / CX-9',726,500,200,125,22,26,'port','device');box(n,'ETH_PORT','400 Gb/s Ethernet',135,670,183,37,24,12,'port','device');box(n,'OPTICAL','32 路 C2C 光连接',352,670,356,37,24,12,'port','device');box(n,'FRONT_IO','前面板 I/O',798,670,196,37,24,12,'port');n.links=[['ETH_PORT','NIC'],['NIC','FE'],['FE','CHIP0'],['FE','HOST']];
n=make('fabric',1140,800);box(n,'BOARD','托盘内功能连接',60,70,1020,665,0,14,'host','base');box(n,'SPINE','跨托盘 C2C spine',240,89,660,44,17,18,'port','device');box(n,'FE','Fabric 扩展逻辑 / 网络侧',330,655,480,45,20,22,'vxm','device');for(let i=0;i<8;i++){const x=100+(i%4)*250,y=197+Math.floor(i/4)*236;box(n,'CHIP'+i,'LPU '+i,x,y,190,160,22,22,'mxm','chip',{chip:i});box(n,'MEM'+i,'MEM',x+15,y+44,92,82,45,3,'mem');box(n,'MXM'+i,'MXM',x+117,y+44,58,36,45,3,'mxm');box(n,'VXM'+i,'VXM',x+117,y+90,58,36,45,3,'vxm');}n.links=[];
const api={sources,hardware,models,levels,steps,stepsFor,exampleExperts,configuration,assignment,chipInfo,location,metric,maps};root.LPX_MODEL=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window==='undefined'?globalThis:window);
