/* UTF-8 · 外部系统、32 槽位机架、1U 托盘与八片互联。实体表面与连线取自 Mermaid。 */
(function(root){
'use strict';
function create({container,assets,onSelect=()=>{},onEnter=()=>{},onCameraChange=()=>{}}){
 const M=root.LPX_MODEL,ns='http://www.w3.org/2000/svg',stage=document.createElement('div'),source=document.createElement('div'),packetSource=document.createElement('div');
 stage.className='spatial-stage lpx-world';container.classList.add('spatial-scene','lpx-canvas');container.replaceChildren(stage);source.innerHTML=assets.lpx.svg;packetSource.innerHTML=assets.packet.svg;
 const templates={};for(const n of source.querySelectorAll('[data-hw-id]'))templates[n.dataset.hwId]=n;const packet=packetSource.querySelector('[data-hw-id="PACKET"]');
 const camera=root.GROQ_SPATIAL_CAMERA.create({container,stage,onChange:onCameraChange});container.addEventListener('keydown',e=>{if(e.target===container&&e.key==='Home'){e.preventDefault();e.stopImmediatePropagation();reset();}},true);let level='external',map=M.maps[level],boxes={},wires=[],markers=[],state=null,step=M.steps[0],progress=0,frame={s:1,x:0,y:0},open=0;
 const mul=(a,b)=>[a[3]*b[0]+a[0]*b[3]+a[1]*b[2]-a[2]*b[1],a[3]*b[1]-a[0]*b[2]+a[1]*b[3]+a[2]*b[0],a[3]*b[2]+a[0]*b[1]-a[1]*b[0]+a[2]*b[3],a[3]*b[3]-a[0]*b[0]-a[1]*b[1]-a[2]*b[2]];
 function rotation(x,y,z){const ax=(i,d)=>{const q=[0,0,0,Math.cos(d*Math.PI/360)];q[i]=Math.sin(d*Math.PI/360);return q;};return mul(mul(ax(0,x),ax(1,y)),ax(2,z));}
 function reset(plan=false){const e={external:[15,-10,0],rack:[7,-18,0],tray:[37,-6,-3],fabric:[24,-7,-2]}[level];camera.set({rotation:plan?[0,0,0,1]:rotation(...e),zoom:1,panX:0,panY:0});}
 function face(template,w,h,side=false){const svg=document.createElementNS(ns,'svg'),node=template.cloneNode(true);svg.setAttribute('viewBox',[-w/2,-h/2,w,h].join(' '));svg.setAttribute('preserveAspectRatio','none');svg.classList.add('lpx-face');node.removeAttribute('id');node.setAttribute('transform','translate(0,0)');node.removeAttribute('data-hw-id');for(const e of node.querySelectorAll('[style]'))e.setAttribute('style',e.getAttribute('style').replace(/!important/g,''));if(side){node.querySelector('.label')?.remove();svg.classList.add('lpx-side');}svg.appendChild(node);return svg;}
 function text(svg,lines,size=16){const el=svg.querySelector('text');if(!el)return;el.replaceChildren();el.style.fontSize=size+'px';el.setAttribute('x',0);el.setAttribute('y',lines.length>1?-4:5);el.setAttribute('text-anchor','middle');for(const [i,line]of lines.entries()){const t=document.createElementNS(ns,'tspan');t.setAttribute('x',0);if(i)t.setAttribute('dy',21);t.textContent=line;el.appendChild(t);}}
 function build(){stage.replaceChildren();boxes={};wires=[];markers=[];for(const b of Object.values(map.boxes)){const host=document.createElement('div');host.className='lpx-solid '+b.kind;host.dataset.part=b.id;host.dataset.color=b.color;const surfaces={};for(const name of ['top','bottom','north','south','west','east']){const svg=face(templates[level+'_'+b.id],b.w,b.h,name!=='top');svg.classList.add('lpx-'+name);host.appendChild(svg);surfaces[name]=svg;}stage.appendChild(host);boxes[b.id]={b,host,faces:surfaces};const top=surfaces.top;
 const font=b.kind==='slot'?11:b.kind==='chip'?19:Math.min(18,b.h<45?14:18);text(top,b.label?[b.label]:[],font);if((b.kind==='device'&&b.h>100)||b.kind==='chip')top.querySelector('text')?.setAttribute('y',-b.h/2+22);if(b.kind==='device'||b.kind==='chip'||b.kind==='slot'){top.setAttribute('tabindex','0');top.setAttribute('role','button');top.setAttribute('aria-label',b.label);const select=()=>onSelect({level,part:b.id,slot:b.slot,chip:b.chip});top.addEventListener('click',select);top.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();e.stopPropagation();select();}});top.addEventListener('dblclick',()=>{select();if(b.kind==='slot')onEnter('tray');if(b.kind==='chip')onEnter(level==='tray'?'fabric':'chip');if(b.id==='LPX')onEnter('rack');});}}
 for(let i=0;i<26;i++){const wire=face(packet,180,62,true),r=wire.querySelector('rect');r.setAttribute('x',-90);r.setAttribute('y',-31);r.setAttribute('width',180);r.setAttribute('height',62);wire.classList.add('lpx-wire');stage.appendChild(wire);wires.push(wire);}
 for(const kind of ['data','control']){const node=document.createElement('div'),svg=face(packet,180,62);node.className='lpx-packet '+kind;const r=svg.querySelector('rect');for(const[k,v]of Object.entries({x:-90,y:-31,width:180,height:62,rx:5}))r.setAttribute(k,v);node.appendChild(svg);stage.appendChild(node);markers.push({node,svg});}resize();}
 function point(id){const b=boxes[id]?.b;return b?{x:b.x+b.w/2,y:b.y+b.h/2,z:b.z+b.depth+5+((level==='rack'&&b.slot===state?.slot)?open*100/frame.s:(level==='tray'&&(['chip','device'].includes(b.kind)||/^DIE\d/.test(id)))?open*38/frame.s:0)}:null;}
 function slotPoint(){return point('SLOT'+(state?.slot||0));}
 function wire(index,a,b,active=false){const el=wires[index];if(!el||!a||!b)return;const dx=(b.x-a.x)*frame.s,dy=(b.y-a.y)*frame.s;el.style.display='block';el.style.left=frame.x+a.x*frame.s+'px';el.style.top=frame.y+a.y*frame.s+'px';el.style.width=Math.hypot(dx,dy)+'px';el.style.height=active?'3px':'2px';el.style.transform='translateZ('+Math.max(a.z,b.z)*frame.s+'px) rotateZ('+Math.atan2(dy,dx)+'rad)';el.classList.toggle('active',active);}
 function float(marker,at,lines,z=62){if(!at){marker.node.hidden=true;return;}marker.node.hidden=false;text(marker.svg,lines,13);marker.node.style.left=frame.x+at.x*frame.s+'px';marker.node.style.top=frame.y+at.y*frame.s+'px';marker.node.style.transform='translateZ('+(at.z*frame.s+z)+'px) var(--space-inverse)';}
 let controlAnchor=0;
 function floatControl(){const anchors=[[.88,.18],[.12,.18],[.88,.76],[.12,.76],[.5,.88],[.5,.12]],canvas=container.getBoundingClientRect(),data=markers[0].svg.getBoundingClientRect();let best=controlAnchor,bestScore=Infinity;
  for(const i of [controlAnchor,...anchors.map((_,i)=>i).filter(i=>i!==controlAnchor)]){const[x,y]=anchors[i];float(markers[1],{x:map.width*x,y:map.height*y,z:0},['当前操作',step.title],40);const c=markers[1].svg.getBoundingClientRect(),overlap=Math.max(0,Math.min(c.right+8,data.right)-Math.max(c.left-8,data.left))*Math.max(0,Math.min(c.bottom+8,data.bottom)-Math.max(c.top-8,data.top)),outside=Math.max(0,canvas.left+6-c.left)+Math.max(0,c.right-canvas.right+6)+Math.max(0,canvas.top+6-c.top)+Math.max(0,c.bottom-canvas.bottom+6),score=overlap+outside*1000;if(score<bestScore){bestScore=score;best=i;}if(score===0){controlAnchor=i;return;}}
  controlAnchor=best;const[x,y]=anchors[best];float(markers[1],{x:map.width*x,y:map.height*y,z:0},['当前操作',step.title],40);
 }
 function draw(nextState,nextStep,t=0){if(nextState)state=nextState;if(nextStep)step=nextStep;progress=t;if(!state)return;const assign=M.assignment(state.model,state.layer,state.weightBytes,state.expert),cfg=M.configuration(state.model,state.weightBytes),target=M.location(state,step),sameSlot=state.slot===target.slot&&(state.rack||0)===target.rack,rootChip=assign.root,peer=assign.peer,rootHere=(state.rack||0)===assign.rootRack&&state.slot===assign.rootSlot,rootID=rootHere?'CHIP'+rootChip:level==='tray'?'SPINE_L':'SPINE',resolve=id=>({SLOT:'SLOT'+state.slot,CHIP_ROOT:rootID,CHIP_PEER:'CHIP'+peer}[id]||id),route=(step.route||[step.from,step.to]).map(resolve),u=Math.max(0,Math.min(1,t)),edge=Math.min(route.length-2,Math.floor(u*(route.length-1))),local=u*(route.length-1)-edge;let from=route[edge],to=route[edge+1];
 for(const [id,s]of Object.entries(boxes)){const selected=s.b.kind==='slot'&&s.b.slot===state.slot||s.b.kind==='chip'&&s.b.chip===state.chip;s.host.classList.toggle('picked',selected);s.host.classList.toggle('flow-active',step.level===level&&sameSlot&&(id===(t>=1?to:from)));if(s.b.kind==='slot'){const assigned=((state.rack||0)*32+s.b.slot)*8<cfg.assignedChips;s.host.classList.toggle('assigned',assigned);s.host.classList.toggle('reserve',!assigned);}if(s.b.kind==='chip'){const info=M.chipInfo(state,state.rack||0,state.slot,s.b.chip),label='LPU '+String(info.global).padStart(3,'0');if(s.faces.top.querySelector('text')?.textContent!==label)text(s.faces.top,[label],19);s.faces.top.querySelector('text')?.setAttribute('y',-s.b.h/2+22);s.faces.top.setAttribute('aria-label',label);s.host.dataset.assignment=info.label;s.host.classList.toggle('participating',!!cfg.moe&&info.layer===state.layer&&(info.activeExperts?.length>0||info.shared));}}
 for(const el of wires)el.style.display='none';let wi=0;for(const [a,b]of map.links)wire(wi++,point(a),point(level==='tray'&&b==='CHIP0'?rootID:b));
 if(level==='rack'){const p=slotPoint(),sp=point('SPINE');wire(wi++,point('UPLINK'),p,step.id==='rack'&&sameSlot);wire(wi++,{...p,x:705},{...sp,y:p.y},false);}
 if(level==='fabric'){if(cfg.moe){for(let c=0;c<8;c++){const info=M.chipInfo(state,state.rack||0,state.slot,c);if(info.layer===state.layer&&(info.activeExperts?.length>0||info.shared))wire(wi++,point(rootID),point('CHIP'+c),sameSlot);}}else for(let pair=0;pair<4;pair++)wire(wi++,point('CHIP'+pair*2),point('CHIP'+(pair*2+1)),sameSlot&&pair===Math.floor(rootChip/2));wire(wi++,point('FE'),point(rootID),sameSlot);wire(wi++,point('SPINE'),point(rootID),false);}
 if(level==='tray')wire(wi++,point('FE'),point(rootID),step.id==='fabric'&&sameSlot);
 const show=step.level===level&&sameSlot,pa=point(from),pb=point(to);if(show&&pa&&pb){wire(wi++,pa,pb,true);const v=local*local*(3-2*local),at={x:pa.x+(pb.x-pa.x)*v,y:pa.y+(pb.y-pa.y)*v,z:pa.z+(pb.z-pa.z)*v},context=step.id==='request'?'请求 A · 原始文本':step.id==='tokens'?'请求 A · 输入上下文':'Token t · 层 '+state.layer+(cfg.moe?' · E'+state.expert:'');markers[0].node.dataset.from=from;markers[0].node.dataset.to=to;float(markers[0],at,[step.data,context],55);floatControl();}else for(const m of markers)m.node.hidden=true;
 }
 function resize(){const w=stage.clientWidth,h=stage.clientHeight;if(!w||!h)return;const pitch={external:15,rack:7,tray:37,fabric:24}[level]*Math.PI/180;frame.s=Math.min((w-54)/(map.width*.96),(h-60)/(map.height*Math.cos(pitch)));frame.x=(w-map.width*frame.s)/2;frame.y=(h-map.height*frame.s)/2+20;for(const {b,host,faces:f}of Object.values(boxes)){const s=frame.s,bw=b.w*s,bh=b.h*s,d=b.depth*s;host.style.width=bw+'px';host.style.height=bh+'px';host.style.transform='translate3d('+(frame.x+b.x*s)+'px,'+(frame.y+b.y*s)+'px,'+b.z*s+'px)';for(const n of [f.top,f.bottom]){n.style.width=bw+'px';n.style.height=bh+'px';}f.top.style.transform='translateZ('+d+'px)';for(const n of [f.north,f.south]){n.style.width=bw+'px';n.style.height=d+'px';}f.north.style.transform='rotateX(90deg)';f.south.style.transform='translateY('+bh+'px) rotateX(90deg)';for(const n of [f.west,f.east]){n.style.width=d+'px';n.style.height=bh+'px';}f.west.style.transform='rotateY(-90deg)';f.east.style.transform='translateX('+bw+'px) rotateY(-90deg)';}draw(state,step,progress);}
 function show(next,animate=true){if(!M.maps[next])return;if(next!==level||!Object.keys(boxes).length){level=next;map=M.maps[level];open=0;controlAnchor=0;build();reset();if(animate&&!matchMedia('(prefers-reduced-motion: reduce)').matches)container.animate([{opacity:.15},{opacity:1}],{duration:360,easing:'ease-out'});}else resize();}
 function explode(value){open=value;for(const s of Object.values(boxes)){let z=0;if(level==='rack'&&(s.b.slot===state.slot))z=value*100;if(level==='tray'&&(['chip','device'].includes(s.b.kind)||/^DIE\d/.test(s.b.id)))z=value*38;s.host.style.translate='0 0 '+z+'px';}draw(state,step,progress);return open;}
 const observer=new ResizeObserver(resize);observer.observe(container);show('external',false);return{camera,show,draw,resize,reset,explode,get level(){return level;},get boxes(){return boxes;}};
}
root.LPX_SCENE={create};
})(window);
