/* UTF-8 · 左侧固定硬件与右侧性能账本联动。 */
(function(){
 'use strict';const P=window.GROQ_PERFORMANCE,L=window.GROQ_PERFORMANCE_LESSONS,A=window.HARDWARE_ATLAS_MAP,G=window.HARDWARE_SVGS,E=window.HARDWARE_MOTION,$=id=>document.getElementById(id);
 if(!P||!L||!A||!G||!E){$('operation-title').textContent='本地资源未加载，请打开独立 HTML。';return;}
 const S={params:{...P.defaults},index:0,phase:0,flowSettled:false,plane:'ME0',focus:null,collapsed:false,selected:null,mac:null,sl:3,slice:0,zoom:1,overview:false,auto:false,timer:null,valid:true};let requestFlow;let model=P.build(S.params),motion,atlas,softwareFlow,editTimer;
 const reduced=window.matchMedia('(prefers-reduced-motion: reduce)');
 const text=(id,value)=>{$(id).textContent=value;},esc=value=>String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),step=()=>model.steps[S.index],fmt=L.format,range=(a,b)=>Math.abs(a-b)<1e-10?P.time(a):P.time(a)+' — '+P.time(b);
 const rows=(data,headers=['项目','结果'])=>'<table class="ledger-table"><thead><tr>'+headers.map(h=>'<th>'+esc(h)+'</th>').join('')+'</tr></thead><tbody>'+data.map(r=>'<tr>'+r.map(c=>'<td>'+c+'</td>').join('')+'</tr>').join('')+'</tbody></table>';
 const fields={
  shape:[['batch','批量 B',1,64,1],['seq','上下文 S（含新位置）',1,32768,1],['dim','隐藏维 D',8,16384,8],['heads','查询头数 H',1,128,1],['kvHeads','KV 头数 G',1,128,1],['ffn','FFN 中间维 F',8,65536,8],['layers','层数 L',1,128,1],['vocab','词表大小 V',16,262144,16]],
  hardware:[['peakTflops','矩阵峰值 TFLOP/s',.01,10000,.1],['matrixUtil','矩阵有效率 %',.1,100,1,.01],['sramTBs','SRAM 上限 TB/s',.001,1000,.1],['memoryUtil','片上带宽有效率 %',.1,100,1,.01],['pcieGBs','PCIe 单向 GB/s',.001,1000,.1],['pcieUtil','PCIe 有效率 %',.1,100,1,.01],['vectorGops','向量等效 GOP/s',.001,100000,100],['capacityMiB','片上容量 MiB',1,100000,1],['operatorUs','每算子固定开销 μs',0,10000,.1],['dmaUs','每次 DMA 固定开销 μs',0,100000,1],['runtimeUs','运行时提交 μs',0,100000,1]],
  service:[['rttMs','网络往返 RTT ms',0,10000,1],['networkMbps','外部链路 Mbit/s',.01,1000000,10],['nicGbps','服务器 NIC Gbit/s',.01,10000,1],['cpuTokensPerSec','分词 token/s（假设）',1,100000000,10000],['cpuFixedMs','CPU 固定开销 ms',0,10000,.1],['samplingUs','采样 / 解码预算 μs',0,100000,1],['queueMs','请求排队 ms',0,10000,1]]
 };
 for(const[group,list]of Object.entries(fields))$(group+'-inputs').innerHTML=list.map(([name,title,min,max,increment,scale=1])=>`<label>${esc(title)}<input type="number" data-param="${name}" data-scale="${scale}" min="${min}" max="${max}" step="${increment}" value="${S.params[name]/scale}" aria-label="${esc(title)}"></label>`).join('');
 function fillInputs(){document.querySelectorAll('[data-param]').forEach(el=>{const k=el.dataset.param;if(el.type==='checkbox')el.checked=S.params[k];else el.value=el.type==='number'?S.params[k]/Number(el.dataset.scale||1):S.params[k];});}
 function remap(id){return id.replace(/^ME0(?=__|CIRCUIT|HEAD|R|$)/,S.plane).replace(/^MEME(?=__|HEAD|R|$)/,S.plane.startsWith('MW')?'MEMW':'MEME').replace(/^SE(?=__|HEAD|R|$)/,S.plane.startsWith('MW')?'SW':'SE');}
 function physicalName(id){const p=A.specs[id];if(!p)return id;const name=A.zones.find(z=>z[0]===p.owner)?.[1];return(name?name+' / ':p.owner==='HOST'?'芯片外 / ':'')+p.label;}
 function nameList(ids){return[...new Set(ids.map(remap).map(physicalName))].slice(0,2).join('；');}
 function getPhases(){return L.phases(model,step()).map(p=>({...p,focus:p.focus.map(remap),packets:p.packets.map(k=>({...k,from:remap(k.from),to:remap(k.to)}))}));}
 function stop(){S.auto=false;clearTimeout(S.timer);motion?.pause();text('auto-operations','自动运行本章节');$('auto-operations').setAttribute('aria-pressed','false');}
 function zoom(){
  if(!atlas)return;const phase=getPhases()[S.phase]||{focus:[]},view=window.GROQ_VIEWPORT.single(A.layout(atlas.context),{focus:S.selected?[S.selected]:phase.focus,overview:S.overview,zoom:S.zoom,external:atlas.context.external});const svg=$('lab-canvas').querySelector('svg');svg.setAttribute('viewBox',window.GROQ_VIEWPORT.serialize(view));svg.setAttribute('preserveAspectRatio','xMidYMid meet');text('lab-zoom-label',Math.round(S.zoom*100)+'%');$('fit-hardware').setAttribute('aria-pressed',String(S.overview));$('follow-hardware').setAttribute('aria-pressed',String(!S.overview));
 }
 function followViewport(phase){zoom();}
 function paintHardware(phase){
  const current=step(),owners=phase.focus.map(id=>A.specs[id]?.owner).filter(o=>A.group(o)),focus=S.focus||owners[0]||S.plane;
  const ctx=A.context({zone:S.plane,kind:'lab',focusZone:focus,expanded:!S.collapsed&&(owners.length>0||Boolean(S.focus)),sl:S.sl,slice:S.slice,mac:S.mac,external:current.section==='接入'||['pcie_out','sample','decode_text','send'].includes(current.id),lab:true});
  const patch=Object.fromEntries(Object.entries(L.patch(model,current,S.phase)).map(([id,p])=>[remap(id),p]));
  atlas.render({state:window.HARDWARE_DATA.snapshot({chapter:5,step:4}),kind:'lab',context:ctx,patch,selected:S.selected,macPatch:S.mac?L.macro(model,current,S.phase,S.mac):null});text('hardware-address',atlas.address(S.selected||phase.focus[0]||current.where));zoom();followViewport(phase);
 }
 function trafficTable(s){
  if(s.traffic.length)return rows(s.traffic.map(r=>[esc(r.name)+'<small>'+esc(r.formula)+'</small>',esc(P.bytes(r.bytes))]));
  if(s.wireBytes!==undefined)return rows([[s.kind==='pcie'?'PCIe 本次传输':'本步缓冲 / 网络数据',esc(P.bytes(s.wireBytes))],['每请求重新传输模型权重','0 B']]);
  return '<p class="calculation-note">本步按固定软件时间计，没有额外登记一项片上张量读写。相关数据传输在相邻步骤中分别统计。</p>';
 }
 function ledger(){
  const s=step(),p=model.p,d=model.dimensions,e=model.effective;const wire=['network','pcie'].includes(s.kind),cpu=s.kind==='cpu';
  text('ledger-op-name',s.title);text('operator-time',range(s.low,s.high));text('operator-time-kind',wire||cpu?'本步骤的参数化时间':s.kind==='repeat'?'其余层的逐算子时间之和':'乐观下界 — 搬运与计算串行');text('operator-bound',s.bound);text('operator-intensity',s.flops&&s.memoryBytes?P.num(s.intensity)+' FLOP/B':'');
  text('operator-flops',s.flops?P.ops(s.flops)+' FLOPs':'0');text('operator-vector',s.vectorOps?P.ops(s.vectorOps)+' 等效项':'0');text('traffic-label',s.traffic.length?'片上读写总量':'本步缓冲 / 边界数据');text('operator-bytes',P.bytes(s.traffic.length?s.memoryBytes:s.wireBytes||0));text('bandwidth-label',s.kind==='pcie'?'有效 PCIe 单向带宽':s.kind==='network'?'链路与 NIC 的较小值':cpu?'软件时间口径':'有效片上带宽');text('operator-bandwidth',s.kind==='pcie'?P.num(e.pcie/1e9)+' GB/s':s.kind==='network'?P.num(e.network/1e6)+' MB/s':cpu?'可编辑预算':P.num(e.memory/1e12)+' TB/s');
  const formulas=s.formulas.slice();let times=[];
  if(!wire&&!cpu&&s.kind!=='repeat'){
   if(s.flops)formulas.push(`矩阵时间 = ${P.num(s.flops)} ÷ (${p.peakTflops} × 10¹² × ${P.num(p.matrixUtil*100)}%) = ${P.time(s.flops/e.matrix*1000)}`);
   if(s.vectorOps)formulas.push(`向量时间 = ${P.num(s.vectorOps)} ÷ (${p.vectorGops} × 10⁹) = ${P.time(s.vectorOps/e.vector*1000)}`);
   formulas.push(`搬运时间 = ${P.num(s.memoryBytes)} B ÷ (${p.sramTBs} × 10¹² × ${P.num(p.memoryUtil*100)}%) = ${P.time(s.memoryMs)}`);
   times=[['计算',P.time(s.computeMs)],['片上搬运',P.time(s.memoryMs)],['设定固定开销',P.time(s.fixedMs)],['max(计算, 搬运) + 开销',P.time(s.low)],['计算 + 搬运 + 开销',P.time(s.high)]];
  }else if(s.kind==='pcie'){times=[['传输字节',P.bytes(s.wireBytes)],['PCIe 数据序列化',P.time(s.wireBytes/e.pcie*1000)]];if(s.memoryBytes)times.push(['DMA 从片上读取',P.time(s.memoryMs)]);times.push(['提交 / 完成预算',P.time(p.dmaUs/1000)],['合计（重叠 — 串行）',range(s.low,s.high)]);}
  else if(s.kind==='network')times=[['数据序列化',P.time((s.wireBytes||0)/e.network*1000)],['固定单程传播',P.time(s.id==='request'&&p.mode==='decode'?0:p.rttMs/2)],['请求排队',P.time(s.id==='request'&&p.mode==='prefill'?p.queueMs:0)],['合计',P.time(s.low)]];
  else times=[['本步骤时间',range(s.low,s.high)]];
  $('formula-list').innerHTML=formulas.filter(Boolean).map(f=>'<div class="formula-line">'+esc(f)+'</div>').join('');$('time-breakdown').innerHTML=rows(times.map(r=>r.map(esc)));$('traffic-table').innerHTML=trafficTable(s);
  text('calculation-note',s.flops&&s.memoryBytes?`算术强度 ${P.num(s.intensity)} FLOP/B；有效算力 / 带宽 = ${P.num(e.matrix/e.memory)} FLOP/B。访存按张量最低读写量计，真实分块可能重读，实际延迟也可能超过串行估算。`:'等效向量速度、固定开销和有效率都是演算参数。不同算子在本账本中顺序累计；实际融合、重叠、精度转换与编译调度会改变结果。');
  text('layer-time',range(model.layer.low,model.layer.high));text('end-time-label',p.mode==='prefill'?'首片段 TTFT · 热请求':'连续输出 TPOT · 稳态模型');text('end-time',model.total.valid?range(p.mode==='prefill'?model.total.low:model.total.tpLow,p.mode==='prefill'?model.total.high:model.total.tpHigh):'容量不足，未给出单片估算');
  text('token-rate',!model.total.valid?'容量不足，未估算':p.mode==='prefill'?'切换 Decode 查看连续输出速率':P.num(1000/model.total.tpHigh,1)+' — '+P.num(1000/model.total.tpLow,1)+' token/s / 请求');
  text('total-explain',!model.total.valid?'本配置超出单片容量，只保留算子形状与成本教学；未输出整模型延迟或连续输出速率。':p.mode==='prefill'?`TTFT 包含请求网络、CPU、PCIe、${d.L} 层、词表头和首次返回；不含冷部署。中间算子的顺序累计只是估算口径。`:`TPOT 为一轮新位置处理和片段序列化时间，固定单程传播不反复加入。若从本轮起点量用户收到，时间为 ${range(model.total.low,model.total.high)}；主机采样为本页接入示例。`);
  const c=model.capacity;text('capacity-status',c.fits?'容量下界可容纳':'超出单片容量');$('capacity-status').closest('details').classList.toggle('over-capacity',!c.fits);$('capacity-table').innerHTML=rows([['权重（词嵌入与输出共享）',P.bytes(c.weights)],['所有层的 KV',P.bytes(c.kv)],['估计工作区',P.bytes(c.workspace)],['需要 / 片上容量',P.bytes(c.total)+' / '+P.bytes(c.limit)]].map(r=>r.map(esc)));text('capacity-explain',c.fits?'这里只通过容量下界检查，尚未验证实际切片分配、碎片、指令存储与编译可部署性。':`容量下界至少相当于 ${c.minimumChips} 颗此规格芯片；这不是部署方案，也不能直接把吞吐乘以芯片数。当前仍可学习单算子的形状和成本。`);text('deployment-time',P.time(model.deployment.low));
 }
 function sampleTable(values,title,{pending=false,output=false,positions=true}={}){
  if(!values?.length)return'';return'<div class="matrix-sample '+(output?'sample-output':'')+'"><h3>'+esc(title)+' <small>'+values.length+' × '+values[0].length+'</small></h3><table class="sample-table"><thead><tr><th></th>'+values[0].map((_,i)=>'<th>'+i+'</th>').join('')+'</tr></thead><tbody>'+values.map((r,i)=>'<tr><th>'+(positions?'t':'k')+(positions&&(model.p.mode==='decode'||step().id==='finalnorm')&&values.length===1?2:i)+'</th>'+r.map(n=>'<td class="'+(n===-Infinity?'masked':'')+'">'+(pending?'·':esc(fmt(n)))+'</td>').join('')+'</tr>').join('')+'</tbody></table></div>';
 }
 function sample(){
  const s=step(),toy=P.sample(model.p.mode)[s.sample];text('sample-title',toy?.title||'这一段传输的到底是什么');text('sample-explain',toy?'固定数值例子：3 个位置、D=4、H=2、G=1、F=6；与右侧完整模型的参数分开。Decode 只展示最后一行查询，K/V 仍含三行历史。':'接入示例采用主机分词与采样。模型权重冷部署一次，热请求主要提交本次输入。');
  if(!toy){
   if(!['network','cpu','pcie'].includes(s.kind)){text('sample-title','把当前张量对应到硬件');text('sample-explain','这里按右侧模型的完整形状说明，不再套用接入阶段的数据大小。');$('sample-content').innerHTML=rows([['当前形状',s.shape],['读取位置',nameList(s.from)],['执行 / 输出位置',nameList(s.to)],['矩阵 FLOPs',P.ops(s.flops)],['片上最低读写',P.bytes(s.memoryBytes)],['计算关系',s.formulas.join('；')]].map(r=>r.map(esc)));return;}
   $('sample-content').innerHTML=rows([['Prompt / 请求正文',P.bytes(model.setup.networkBytes)],['主机 → 设备的 ID',`${P.num(model.dimensions.B)} × ${P.num(model.dimensions.T)} × 4 = ${P.bytes(model.setup.inputBytes)}`],['设备 → 主机的 logits',`${P.num(model.dimensions.B)} × ${P.num(model.dimensions.V)} × 4 = ${P.bytes(model.setup.logitBytes)}`],['每次请求的权重传输','0 B；已部署于设备'],['模型权重总容量',P.bytes(model.capacity.weights)]].map(r=>r.map(esc)));return;
  }
  let out=toy.output,title='输出',pending=S.phase<3,equation='';
  if(toy.type==='matrix'){
   const input=toy.input.at(-1),weight=toy.weight,c=S.mac?.col<weight[0].length?S.mac.col:0;
   if(S.phase===2){out=toy.input.map(row=>weight[0].map((w,j)=>row[0]*w));pending=false;title='仅第 0 项的贡献';}
   equation=`最后示例位置，输出 ${c}：`+input.map((x,i)=>fmt(x)+'×'+fmt(weight[i][c])).join(' + ')+(S.phase>=3?' = '+fmt(toy.output.at(-1)[c]):'；完整求和在第 4 段锁存。');
   if(S.mac&&S.mac.row<input.length)equation=`选中 MAC [${S.mac.row},${c}]：${fmt(input[S.mac.row])} × ${fmt(weight[S.mac.row][c])} = ${fmt(input[S.mac.row]*weight[S.mac.row][c])}。`+equation;
  }else if(toy.type==='norm'){
   pending=false;out=toy.input.map(row=>{const squares=row.map(v=>v*v),mean=squares.reduce((a,b)=>a+b,0)/row.length;return S.phase===0?squares:S.phase===1?[mean]:S.phase===2?[1/Math.sqrt(mean+1e-5)]:row.map(v=>v/Math.sqrt(mean+1e-5));});title=['逐元素平方','每行 mean(x²)','每行 rsqrt(mean+ε)','归一化输出'][S.phase];equation='每个位置分别计算，ε = 0.00001，示例 γ = 1。归约得到同一行共用的缩放系数；数值例子只含一个 Transformer 层。';
  }else if(toy.type==='mask'){
   pending=S.phase===0;out=S.phase===1?toy.extra:toy.output;title=S.phase===1?'除以 √2 后的得分':'应用因果遮罩';equation='第 t 行只允许列 j ≤ t。上三角设为 −∞；它们在 exp 中变成 0。';
  }else if(toy.type==='cast'){
   equation='数值窗格保持同一组概率，未模拟 FP16 舍入。右侧逐项列出 FP32 读入、转换工作量和 FP16 写回。';title='FP16 输入格式的 P（示意）';
  }else if(toy.type==='softmax'){
   pending=false;out=toy.input.map(row=>{const m=Math.max(...row),e=row.map(x=>Math.exp(x-m)),z=e.reduce((a,b)=>a+b,0);return S.phase===0?[m]:S.phase===1?e:S.phase===2?[z]:e.map(v=>v/z);});title=['每行最大值 m','exp(score−m)','每行分母 Z','概率 P'][S.phase];equation=S.phase===3?'检查：每行概率总和 = 1；未来位置的概率 = 0。':'每一行单独处理。不能把不同查询位置的分母混到一起。';
  }else if(toy.type==='silu'){
   pending=S.phase===0;if(S.phase===1){out=toy.input.map(r=>r.map(v=>Math.exp(-v)));title='exp(−gate)';}if(S.phase===2){out=toy.input.map(r=>r.map(v=>1/(1+Math.exp(-v))));title='sigmoid(gate)';}equation='逐元素：SiLU(g) = g / (1 + exp(−g))。本例在 VXM 中完成非线性，随后再与 Up 相乘。';
  }else if(toy.type==='multiply'||toy.type==='add')equation=toy.input.at(-1).map((v,i)=>fmt(v)+(toy.type==='add'?'+':'×')+fmt(toy.weight.at(-1)[i])+'='+fmt(toy.output.at(-1)[i])).join('，')+'。每项对应同一个位置与通道。';
  else equation=s.formulas.join('；');
  let html='<div class="matrix-samples">'+sampleTable(toy.input,'输入')+sampleTable(toy.weight,toy.type==='multiply'?'Up 分支':toy.type==='add'?'相加的另一路':'权重 / 右操作数',{positions:['multiply','add'].includes(toy.type)})+sampleTable(out,title,{pending,output:true});if(s.id==='rope')html+=sampleTable(model.p.mode==='decode'?[toy.extra.at(-1)]:toy.extra,'旋转后的 K',{pending:S.phase<3,output:true});html+='</div><div class="sample-equation">'+esc(equation)+'</div>';$('sample-content').innerHTML=html;
 }
 function navigation(){
  requestFlow?.render({mode:model.p.mode,key:step().id});text('single-flow-title',(model.p.mode==='decode'?'Decode':'Prefill')+' 完整流程');text('single-flow-summary',window.GROQ_REQUEST_FLOW.summary(model.p.mode,model.dimensions.S,model.dimensions.T));
  const s=step(),sections=['接入','Attention','FFN','输出'];$('single-section-select').innerHTML=sections.map(name=>'<option value="'+name+'">'+name+'</option>').join('');$('single-section-select').value=s.section;$('single-operation-select').innerHTML=model.steps.map((v,i)=>v.section===s.section?'<option value="'+i+'">'+esc(v.title)+'</option>':'').join('');$('single-operation-select').value=String(S.index);$('section-tabs').innerHTML=sections.map((name,i)=>`<button data-section="${name}"${name===s.section?' aria-current="step"':''}>${['01 接入芯片','02 Attention','03 FFN','04 返回用户'][i]}</button>`).join('');
  $('operation-list').innerHTML=model.steps.map((v,i)=>v.section===s.section?`<button data-operation="${i}"${i===S.index?' aria-current="step"':''}><span>${String(i+1).padStart(2,'0')}</span>${esc(v.title)}</button>`:'').join('');
  text('operation-title',s.title);text('operation-shape',s.shape);text('step-kicker',String(S.index+1).padStart(2,'0')+' / '+model.steps.length+' · '+s.section);text('resource-badge',A.group(remap(s.where))?A.zones.find(z=>z[0]===remap(s.where))[1]:s.where==='NET'?'网络 / NIC':s.where==='PCIE'?'PCIe / DMA':'主机 CPU');text('operator-reason',s.reason);text('step-progress',(S.index+1)+' / '+model.steps.length);$('previous-operation').disabled=S.index===0;text('next-operation',S.index===model.steps.length-1?'进入下一轮 Decode →':'下一步 →');
  document.querySelectorAll('[data-mode]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.mode===model.p.mode)));text('mode-explain',model.p.mode==='prefill'?`B=${model.p.batch}；一次输入 T=S=${model.p.seq} 个位置。GQA：${model.p.heads} 个 Q 头共享 ${model.p.kvHeads} 个 KV 头。`:`每个请求仅输入 T=1；历史 ${model.p.seq-1} + 新位置 1 = S=${model.p.seq}。KV 历史保持。`);
 }
 function go(index,{autoplay=true,keepSelection=false,phase=null}={}){
  S.index=Math.max(0,Math.min(model.steps.length-1,index));if(!keepSelection){S.focus=null;S.selected=null;S.mac=null;$('selected-hardware').hidden=true;}navigation();ledger();if(autoplay&&window.scrollY>$('lab-main').offsetTop+200)$('lab-main').scrollIntoView({block:'start',behavior:reduced.matches?'auto':'smooth'});
  const ph=getPhases();$('lab-phases').innerHTML=ph.map((v,i)=>`<button data-phase="${i}"><span>0${i+1}</span>${esc(v.title)}</button>`).join('');motion.load(ph,{milliseconds:Number($('lab-speed').value),autoplay,reduce:reduced.matches});if(phase!==null)motion.seek((phase+.01)/4);text('lab-announcement',step().title+'。'+step().shape);
 }
 function next(){stop();if(S.index===model.steps.length-1){S.params.mode='decode';S.params.seq=Math.min(32768,S.params.seq+1);model=P.build(S.params);fillInputs();go(0);window.dispatchEvent(new CustomEvent('groq:model',{detail:model}));}else go(S.index+1);}
 function recalculate(raw,reset=false){
  stop();try{const nextModel=P.build(raw),id=step().id;S.params=nextModel.p;model=nextModel;S.valid=true;$('parameter-error').hidden=true;document.body.removeAttribute('aria-busy');if(document.body.dataset.workspace!=='single'){navigation();ledger();}else go(reset?0:Math.max(0,model.steps.findIndex(s=>s.id===id)),{autoplay:false});window.dispatchEvent(new CustomEvent('groq:model',{detail:model}));}
  catch(e){S.valid=false;text('parameter-error',e.message+'。账本保留上次有效参数的结果；请修正后继续。');$('parameter-error').hidden=false;document.body.setAttribute('aria-busy','true');}
 }
 function readInputs(){const raw={...S.params};document.querySelectorAll('[data-param]').forEach(el=>{raw[el.dataset.param]=el.type==='checkbox'?el.checked:el.type==='number'?Number(el.value)*Number(el.dataset.scale||1):el.value;});return raw;}
 function dialog(kicker,html){stop();text('dialog-kicker',kicker);$('lab-dialog-content').innerHTML=html;$('lab-dialog').showModal();$('lab-dialog-close').focus();}
 function compare(){const a=P.build({...S.params,mode:'prefill'}),b=P.build({...S.params,mode:'decode'}),one=(m,id)=>m.steps.find(s=>s.id===id),list=[['本轮输入位置 T',a.dimensions.T,b.dimensions.T],['QK / P 的形状',`${a.dimensions.B}×${a.dimensions.H}×${a.dimensions.S}×${a.dimensions.S}`,`${b.dimensions.B}×${b.dimensions.H}×1×${b.dimensions.S}`],['QK 矩阵运算',P.ops(one(a,'qk').flops)+' FLOPs',P.ops(one(b,'qk').flops)+' FLOPs'],['三次 FFN 投影',P.ops(['ffn_gate','ffn_up','ffn_down'].reduce((v,k)=>v+one(a,k).flops,0))+' FLOPs',P.ops(['ffn_gate','ffn_up','ffn_down'].reduce((v,k)=>v+one(b,k).flops,0))+' FLOPs'],['本轮新 KV 写入 / 层',P.bytes(one(a,'kv_write').memoryBytes),P.bytes(one(b,'kv_write').memoryBytes)],['一层算子链',range(a.layer.low,a.layer.high),range(b.layer.low,b.layer.high)],['全部模型层 FLOPs',P.ops(a.layer.flops*a.p.layers),P.ops(b.layer.flops*b.p.layers)],['整模型单片容量',a.capacity.fits?'下界可容纳':'不足',b.capacity.fits?'下界可容纳':'不足']];dialog('同参数、不同工作量','<h2>Prefill 与 Decode 为什么不一样</h2><p class="lab-dialog-note">共同使用 S='+S.params.seq+'，S 包含当前新输入。Prefill 一次处理 S 个位置；Decode 的历史为 S−1，只增加 1 个位置。</p><table class="lab-dialog-table"><tr><th>项目</th><th>Prefill</th><th>Decode</th></tr>'+list.map(r=>'<tr>'+r.map(v=>'<td>'+esc(v)+'</td>').join('')+'</tr>').join('')+'</table><p class="lab-dialog-note">上下文增加时，完整 Prefill 的 QK/PV 工作量按 S² 增长；单轮 Decode 按 S 增长。Decode 的 FFN 仍处理一个新位置，其矩阵 FLOPs 不随历史 S 增长，但历史 KV 读取会增长。以上是模型算量关系，实际延迟还受容量、利用率与编译布局影响。</p>');}
 function sources(){dialog('口径、来源与可修改假设','<h2>这里的时间是如何得到的</h2><p class="lab-dialog-note">左侧是第一代 Groq TSP 的功能结构与代表性数值窗口；右侧是参数化成本模型，没有连接真实设备采集性能。</p><h3>公开硬件资料</h3><div class="lab-dialog-links">'+P.sources.map(s=>'<a href="'+esc(s.url)+'" target="_blank" rel="noopener">'+esc(s.name)+'</a>').join('')+'</div><h3>估算采用的约定</h3><p class="lab-dialog-note">矩阵输入及权重 FP16，乘并累加按 2 FLOPs；Attention 分数和 Softmax 概率暂存 FP32，并单列转为 FP16 的步骤。矩阵累加的内部寄存器不按每次乘法重新写入 SRAM。容量按 FP16 权重、FP16 KV、共享词嵌入与输出表计算。</p><p class="lab-dialog-note">每个算子的访存按张量最低读写量计。关闭“写回”表示理想流式转发的下界；关闭 KV 复用则按查询头组重复读取。实际分块、片上流量、同步和碎片可能使执行时间与容量高于这里的估算。“串行估算”也不是实际延迟上界。</p><p class="lab-dialog-note">CPU / tokenizer、主机采样、DMA 固定时间、网络速度和有效利用率是接入示例或演算假设；不宣称 GroqCloud 内部采用同样放置。PCIe 按单向带宽计；固定单程网络传播计入首次收到，不重复加入连续输出的 TPOT。</p><h3>容量与多芯片</h3><p class="lab-dialog-note">超过单片容量时不提供整模型单片延迟。最低芯片数只由容量相除得到，还未安排分片、C2C、负载均衡与模型编译，不能用它直接推导真实集群吞吐。</p>');}
 atlas=window.HARDWARE_ATLAS.create({container:$('lab-canvas'),assets:G,onLocation:address=>text('hardware-address',address),onSelect:(id,ctx)=>{
  stop();const spec=A.specs[id];if(!spec)return;const oldPhase=S.phase;S.selected=id;S.mac=null;const m=id.match(/__M(\d)(\d)$/),tile=id.match(/R(\d+)(?:C(\d+))?$/);
  if(tile&&spec.kind==='tile'){S.sl=Number(tile[1]);S.slice=Number(tile[2]||0);}
  if(A.group(spec.owner)==='mxm'){S.plane=spec.owner;if(m){const candidate={row:Number(m[1]),col:Number(m[2])};if(L.macro(model,step(),oldPhase,candidate))S.mac=candidate;}}
  S.focus=A.group(spec.owner)?spec.owner:null;S.collapsed=false;$('collapse-hardware').setAttribute('aria-pressed','false');go(S.index,{autoplay:false,keepSelection:true,phase:oldPhase});atlas.select(id);text('collapse-hardware','收起展开');$('selected-hardware').hidden=false;text('selected-hardware-title',atlas.address(id));text('selected-hardware-detail',S.mac?'这个 MAC 的输入、权重、乘积与部分和已在同一 MXM 区域内展开。下方数值窗格可检查完整点积。':'已暂停并保留所选硬件位置。右侧仍是当前算子的整体成本；点击“跟随运算”回到本片段的执行资源。');
 }});
 requestFlow=window.GROQ_REQUEST_FLOW.create({container:$('single-request-overview'),assets:G,onSelect:group=>{stop();const keys=window.GROQ_REQUEST_FLOW.groups[group].keys,target=group===6?'layers':keys.find(key=>model.steps.some(s=>s.id===key));go(model.steps.findIndex(s=>s.id===target));}});
 softwareFlow=window.GROQ_SOFTWARE_FLOW.create({container:$('single-software-flow'),assets:G,compact:true,onSelect:index=>{stop();S.focus=null;motion.seek((index+.01)/getPhases().length);motion.play();}});
 motion=E.create({container:$('lab-canvas'),assets:G,graph:()=> 'atlas',resolveNode:id=>atlas.node(id,'lab'),resolvePoint:id=>atlas.point(id,'lab'),route:p=>atlas.route(p),paint:(phase,index)=>{
  S.phase=index;S.flowSettled=false;paintHardware(phase);softwareFlow.render(getPhases(),index);text('phase-index',(index+1)+' / 4');text('phase-title',phase.title);text('phase-explain',phase.explain);text('route-source',nameList(phase.packets.length?phase.packets.map(p=>p.from):phase.focus));text('route-target',phase.packets.length?nameList(phase.packets.map(p=>p.to)):'观察亮边单元的状态');document.querySelectorAll('[data-phase]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.phase)===index)));sample();text('lab-answer',step().id==='send'&&index===3?'芯片':model.p.mode==='decode'?'上轮片段已送达，等待本轮':'尚未收到新片段');
 },onTime:({ratio,local})=>{document.querySelector('#lab-main .live-progress').value=ratio*100;const settled=local>=.9;if(S.flowSettled!==settled){S.flowSettled=settled;softwareFlow.render(getPhases(),S.phase,settled);}$('phase-range').value=Math.round(ratio*1000);text('phase-percent',Math.round(ratio*100)+'%');text('cumulative-time',model.total.valid?P.time(step().startLow+step().low*ratio)+'（估算）':'超出单片容量，累计未启用');},onStatus:running=>{text('pause-step',running?'暂停动画':'继续动画');$('pause-step').setAttribute('aria-pressed',String(running));document.body.classList.toggle('motion-paused',!running);},onEnd:()=>{if(S.auto&&model.steps[S.index+1]?.section===step().section)S.timer=setTimeout(()=>go(S.index+1),500);else{S.auto=false;text('auto-operations','自动运行本章节');$('auto-operations').setAttribute('aria-pressed','false');}}});
 $('single-section-select').addEventListener('change',e=>{stop();go(model.steps.findIndex(v=>v.section===e.target.value));});$('single-operation-select').addEventListener('change',e=>{stop();go(Number(e.target.value));});$('section-tabs').addEventListener('click',e=>{const b=e.target.closest('[data-section]');if(b){stop();go(model.steps.findIndex(s=>s.section===b.dataset.section));}});$('operation-list').addEventListener('click',e=>{const b=e.target.closest('[data-operation]');if(b){stop();go(Number(b.dataset.operation));}});
 $('lab-phases').addEventListener('click',e=>{const b=e.target.closest('[data-phase]');if(b){stop();S.focus=null;motion.seek((Number(b.dataset.phase)+.01)/4);}});$('phase-range').addEventListener('input',e=>{stop();S.focus=null;motion.seek(Number(e.target.value)/1000);});$('pause-step').addEventListener('click',()=>{if(motion.running)stop();else if(S.valid)motion.play();});$('replay-step').addEventListener('click',()=>{stop();S.focus=null;if(S.valid)motion.restart();});$('lab-speed').addEventListener('change',()=>motion.setDuration(Number($('lab-speed').value)));
 $('previous-operation').addEventListener('click',()=>{stop();if(S.valid)go(S.index-1);});$('next-operation').addEventListener('click',()=>{if(S.valid)next();});$('auto-operations').addEventListener('click',()=>{if(S.auto){stop();return;}if(!S.valid)return;S.auto=true;S.focus=null;text('auto-operations','暂停连续演示');$('auto-operations').setAttribute('aria-pressed','true');motion.restart();});
 $('collapse-hardware').addEventListener('click',()=>{stop();S.collapsed=!S.collapsed;S.mac=null;$('collapse-hardware').setAttribute('aria-pressed',String(S.collapsed));text('collapse-hardware',S.collapsed?'展开当前硬件':'收起展开');paintHardware(getPhases()[S.phase]);});$('follow-hardware').addEventListener('click',()=>{stop();S.overview=false;S.zoom=1;S.focus=null;S.selected=null;S.mac=null;S.collapsed=false;$('selected-hardware').hidden=true;$('collapse-hardware').setAttribute('aria-pressed','false');text('collapse-hardware','收起展开');paintHardware(getPhases()[S.phase]);});$('zoom-more').addEventListener('click',()=>{S.overview=false;S.zoom=Math.min(2.4,S.zoom+.2);zoom();});$('zoom-less').addEventListener('click',()=>{S.overview=false;S.zoom=Math.max(.6,S.zoom-.2);zoom();});$('fit-hardware').addEventListener('click',()=>{S.overview=true;S.zoom=1;zoom();});window.addEventListener('resize',zoom);
 document.querySelectorAll('[data-mode]').forEach(b=>b.addEventListener('click',()=>{recalculate({...readInputs(),mode:b.dataset.mode});}));$('preset').addEventListener('change',()=>{const mode=S.params.mode;recalculate({...P.presets[$('preset').value],mode},true);fillInputs();});$('restore-parameters').addEventListener('click',()=>{recalculate(P.defaults,true);$('preset').value='small';fillInputs();});$('lab-reset').addEventListener('click',e=>{e.preventDefault();stop();if(document.body.dataset.workspace==='cycle')window.dispatchEvent(new Event('groq:cycle-reset'));else if(document.body.dataset.workspace==='cluster')window.dispatchEvent(new Event('groq:cluster-reset'));else go(0);});
 $('parameter-form').addEventListener('submit',e=>e.preventDefault());$('parameter-form').addEventListener('input',()=>{clearTimeout(editTimer);stop();editTimer=setTimeout(()=>recalculate(readInputs()),300);});$('compare-button').addEventListener('click',()=>{if(document.body.dataset.workspace==='cluster')window.dispatchEvent(new Event('groq:cluster-compare'));else if(S.valid)compare();});$('sources-button').addEventListener('click',()=>{if(document.body.dataset.workspace==='cycle')window.dispatchEvent(new Event('groq:cycle-sources'));else if(document.body.dataset.workspace==='cluster')window.dispatchEvent(new Event('groq:cluster-sources'));else sources();});$('lab-dialog-close').addEventListener('click',()=>$('lab-dialog').close());document.addEventListener('visibilitychange',()=>{if(document.hidden)stop();});
 document.addEventListener('keydown',e=>{if(document.body.dataset.workspace!=='single'||$('cycle-dialog')?.open||$('lab-dialog').open||$('detail-drawer').open||e.ctrlKey||e.metaKey||e.altKey||e.target.closest('input,textarea,select,button,a,[data-interactive=true]'))return;if(e.key==='ArrowRight'){e.preventDefault();if(S.valid)next();}if(e.key==='ArrowLeft'){e.preventDefault();stop();if(S.valid)go(S.index-1);}if(e.code==='Space'){e.preventDefault();if(motion.running)stop();else if(S.valid)motion.play();}});
 // 在后续多芯片脚本启动前提供共享接口；进入下一轮时保持同一个接口对象。
 window.GROQ_LAB={
  getModel:()=>model,
  stop,
  apply:patch=>{recalculate({...S.params,...patch});if(!S.valid)throw Error($('parameter-error').textContent);fillInputs();return model;},
  showSingle:id=>{stop();document.body.dataset.workspace='single';go(id?Math.max(0,model.steps.findIndex(s=>s.id===id)):S.index,{autoplay:false});}
 };
 fillInputs();if(document.body.dataset.workspace!=='single'){navigation();ledger();}else go(0);
})();
