/* UTF-8 · 可复算的形状、流量与时间账本。公开上限与可编辑假设分开。 */
(function(root){
 'use strict';
 const defaults={mode:'prefill',batch:1,seq:128,dim:512,heads:8,kvHeads:2,ffn:1376,layers:6,vocab:4096,peakTflops:188,matrixUtil:.35,sramTBs:80,memoryUtil:.2,pcieGBs:31.5,pcieUtil:.75,vectorGops:1000,capacityMiB:220,operatorUs:.2,dmaUs:8,runtimeUs:5,cpuTokensPerSec:500000,cpuFixedMs:.2,samplingUs:40,rttMs:20,networkMbps:100,nicGbps:25,queueMs:0,materialize:true,skipCausal:false,reuseKV:true,prompt:'用一句话解释芯片。'};
 const presets={small:{...defaults},wide:{...defaults,seq:2048,dim:4096,heads:32,kvHeads:8,ffn:14336,layers:32,vocab:32000},mha:{...defaults,kvHeads:8}};
 const sources=[
  {name:'ISCA 2020 · PCIe 与 DMA、功能切片',url:'http://pkamath.com/publications/papers/tsp-isca20.pdf'},
  {name:'ASAP 2022 · Attention、FFN 与主机通信',url:'https://arxiv.org/abs/2206.11062'},
  {name:'GroqChip v1.5 · 188 TFLOP/s、80 TB/s、PCIe Gen4 x16（Groq 原文镜像）',url:'https://manuals.plus/m/3c668117454870c4f21fdd1d653ac2168bf523a305b16db5c9a800ca5a0186a1.pdf'},
  {name:'GroqCard v1.5 · 主机 PCIe 接口（BittWare 收录的 Groq 原文）',url:'https://www.bittware.com/files/GroqCard%E2%84%A2-Accelerator-Product-Brief-v1.5-.pdf'}
 ];
 const num=(n,d=3)=>Number(n.toFixed(d)).toLocaleString('zh-CN',{maximumFractionDigits:d});
 const time=ms=>ms>=1000?num(ms/1000)+' s':ms>=1?num(ms)+' ms':ms>=.001?num(ms*1000)+' μs':num(ms*1e6)+' ns';
 const bytes=n=>n>=2**30?num(n/2**30)+' GiB':n>=2**20?num(n/2**20)+' MiB':n>=1024?num(n/1024)+' KiB':num(n)+' B';
 const ops=n=>n>=1e12?num(n/1e12)+' T':n>=1e9?num(n/1e9)+' G':n>=1e6?num(n/1e6)+' M':n>=1e3?num(n/1e3)+' K':num(n);
 function validate(raw={}){
  const p={...defaults,...raw};const ranges={batch:[1,64],seq:[1,32768],dim:[8,16384],heads:[1,128],kvHeads:[1,128],ffn:[8,65536],layers:[1,128],vocab:[16,262144],peakTflops:[.01,10000],matrixUtil:[.001,1],sramTBs:[.001,1000],memoryUtil:[.001,1],pcieGBs:[.001,1000],pcieUtil:[.001,1],vectorGops:[.001,100000],capacityMiB:[1,100000],operatorUs:[0,10000],dmaUs:[0,100000],runtimeUs:[0,100000],cpuTokensPerSec:[1,100000000],cpuFixedMs:[0,10000],samplingUs:[0,100000],rttMs:[0,10000],networkMbps:[.01,1000000],nicGbps:[.01,10000],queueMs:[0,10000]};
  for(const[k,[lo,hi]]of Object.entries(ranges)){p[k]=Number(p[k]);if(!Number.isFinite(p[k])||p[k]<lo||p[k]>hi)throw new Error(k+' 的取值范围为 '+lo+'—'+hi);}
  for(const k of ['batch','seq','dim','heads','kvHeads','ffn','layers','vocab'])if(!Number.isInteger(p[k]))throw new Error(k+' 必须是整数');
  if(p.dim%p.heads)throw new Error('隐藏维 D 必须能被查询头数 H 整除');if(p.heads%p.kvHeads)throw new Error('查询头数 H 必须是 KV 头数 G 的整数倍');if((p.dim/p.heads)%2)throw new Error('RoPE 示例要求每个头的维度为偶数');if(!['prefill','decode'].includes(p.mode))throw new Error('模式应为 Prefill 或 Decode');
  for(const k of ['materialize','skipCausal','reuseKV'])p[k]=Boolean(p[k]);p.prompt=String(p.prompt);return p;
 }
 function build(raw={}){
  const p=validate(raw),B=p.batch,S=p.seq,T=p.mode==='prefill'?S:1,D=p.dim,H=p.heads,G=p.kvHeads,d=D/H,K=G*d,F=p.ffn,L=p.layers,V=p.vocab,ba=2,bw=2,bkv=2,bs=4;
  const n=B*T,a=n*D*ba,kvNew=n*K*bkv,kvFull=B*S*K*bkv,score=B*H*T*S*bs,pairs=p.mode==='prefill'&&p.skipCausal?S*(S+1)/2:T*S,scoreOps=B*H*pairs,write=p.materialize?1:0,kvReads=kvFull*(p.reuseKV?1:H/G);
  const effective={matrix:p.peakTflops*1e12*p.matrixUtil,memory:p.sramTBs*1e12*p.memoryUtil,pcie:p.pcieGBs*1e9*p.pcieUtil,vector:p.vectorGops*1e9,network:Math.min(p.networkMbps*1e6,p.nicGbps*1e9)/8};
  const dimensions={B,S,T,D,H,G,d,K,F,L,V,n,a,kvNew,kvFull,score,pairs,scoreOps};
  const weightElements=L*(2*D*D+2*D*K+3*D*F+2*D)+D*V+D;
  const capacity={weights:weightElements*bw,kv:2*B*S*K*bkv*L,workspace:2*score*write+B*T*(5*D+3*F+2*K)*ba};capacity.total=capacity.weights+capacity.kv+capacity.workspace;capacity.limit=p.capacityMiB*2**20;capacity.fits=capacity.total<=capacity.limit;capacity.minimumChips=Math.ceil(capacity.total/capacity.limit);
  const entries=(...rows)=>rows.filter(r=>r[1]>0).map(([name,value,formula])=>({name,bytes:value,formula}));
  const steps=[];
  function add(v){
   const s={flops:0,vectorOps:0,traffic:[],formulas:[],...v};s.memoryBytes=s.traffic.reduce((a,x)=>a+x.bytes,0);s.computeMs=s.flops/effective.matrix*1000+s.vectorOps/effective.vector*1000;s.memoryMs=s.memoryBytes/effective.memory*1000;s.fixedMs=s.fixedMs??p.operatorUs/1000;s.low=s.low??Math.max(s.computeMs,s.memoryMs)+s.fixedMs;s.high=s.high??s.computeMs+s.memoryMs+s.fixedMs;s.intensity=s.memoryBytes?s.flops/s.memoryBytes:0;s.bound=s.computeMs>=s.memoryMs?(s.vectorOps?'向量计算':'矩阵计算'):'片上搬运';if(!s.flops&&!s.vectorOps&&!s.memoryBytes)s.bound=s.bound==='矩阵计算'?'固定开销':s.bound;
   if(s.fixedMs>Math.max(s.computeMs,s.memoryMs))s.bound='设定固定开销';if(v.bound)s.bound=v.bound;steps.push(s);return s;
  }
  const netPayload=new TextEncoder().encode(JSON.stringify({model:'示例模型',messages:[{role:'user',content:p.prompt}],stream:true})).length;
  const requestBytes=p.mode==='prefill'?netPayload*B:0,inputBytes=B*T*4,logitBytes=B*V*4;
  const network=(amount,propagation=0)=>amount/effective.network*1000+propagation;
  const cpuMs=p.mode==='prefill'?p.cpuFixedMs+B*S/p.cpuTokensPerSec*1000:0;
  const setup={networkBytes:requestBytes,inputBytes,logitBytes,outputBytes:B*new TextEncoder().encode('data: '+JSON.stringify({text:'芯片'})+'\n\n').length};
  add({id:'request',section:'接入',title:p.mode==='prefill'?'请求从用户到服务器 NIC':'Decode 复用已建立的请求',where:'NET',kind:'network',from:['HOST__USERDEVICE'],to:['HOST__NETBUF'],shape:'UTF-8 请求正文 → NIC 接收缓冲',low:p.mode==='prefill'?network(requestBytes,p.rttMs/2)+p.queueMs:0,high:p.mode==='prefill'?network(requestBytes,p.rttMs/2)+p.queueMs:0,fixedMs:0,bound:'外部网络 / 队列',wireBytes:requestBytes,formulas:[p.mode==='prefill'?`${requestBytes} B ÷ ${num(effective.network/1e6)} MB/s + RTT/2 + 队列`:'同一流式请求中的下一轮，不重复上传整个 Prompt'],reason:'网络先到服务器网卡。文字不会通过互联网直接进入 MAC。上下文 S 是可编辑的分词后长度假设；正文大小按这里的真实 UTF-8 文本计算。'});
  add({id:'tokenize',section:'接入',title:p.mode==='prefill'?'CPU 分词，ID 写入主机 DRAM':'上轮 Token ID 已在主机侧就绪',where:'CPU',kind:'cpu',from:['HOST__NETBUF','HOST__HOSTCPU'],to:['HOST__HOSTRAM'],shape:`设定分词结果 [B,T] = [${B},${T}] 个 int32 ID`,low:cpuMs,high:cpuMs,fixedMs:0,bound:'CPU 输入准备',wireBytes:inputBytes,formulas:[p.mode==='prefill'?`${B} × ${S} ÷ ${num(p.cpuTokensPerSec)} token/s + ${p.cpuFixedMs} ms`:'只使用上轮已选择的 ID；分词成本为 0'],reason:'Token ID 是词表索引，每个按 4 B 计。页面不运行 tokenizer；CPU 速度与固定开销都是估算参数。'});
  add({id:'runtime',section:'接入',title:'运行时提交任务与 DMA 描述符',where:'CPU',kind:'cpu',from:['HOST__HOSTRAM'],to:['HOST__PROGRAM'],shape:'主机输入缓冲地址 + 已部署程序入口',low:p.runtimeUs/1000,high:p.runtimeUs/1000,fixedMs:0,bound:'运行时提交',formulas:[`运行时固定开销 = ${p.runtimeUs} μs（设定）`],reason:'运行时组织设备可访问的输入缓冲与传输任务。指令程序和模型权重已经部署，不随这条 Prompt 重新训练或编译。'});
  add({id:'pcie_in',section:'接入',title:'PCIe 传输 ID，设备 DMA 接收',where:'PCIE',kind:'pcie',from:['HOST__HOSTRAM','PCIE'],to:['DMA'],shape:`${B} × ${T} × 4 B = ${bytes(inputBytes)}`,low:p.dmaUs/1000+inputBytes/effective.pcie*1000,high:p.dmaUs/1000+inputBytes/effective.pcie*1000,fixedMs:0,bound:'PCIe / DMA',wireBytes:inputBytes,formulas:[`${B} × ${T} × 4 = ${num(inputBytes)} B`,`${num(inputBytes)} B ÷ (${p.pcieGBs} GB/s × ${num(p.pcieUtil*100)}%) + ${p.dmaUs} μs`],reason:'此接入例传入整数 ID，后面在设备上查嵌入表。这里的 PCIe 带宽按单方向计算，不把两个方向相加。DMA 描述符和 PCIe 协议开销归入固定开销与利用率。'});
  add({id:'landing',section:'接入',title:'DMA 的输入落到片上 MEM',where:'MEMW',kind:'memory',from:['DMA'],to:['MEMW__WRITE','MEMW__B0R0L0'],shape:`片上输入缓冲 [${B},${T}]`,traffic:entries(['ID 写入',inputBytes,'B × T × 4 B']),formulas:[`${num(inputBytes)} B ÷ ${num(effective.memory/1e12)} TB/s`],reason:'数据获得片上存储位置，随后由编译程序安排读出。主机 DRAM 与片上 SRAM 是不同存储；此处单独列出落地写入，实际可能与传输重叠。'});
  add({id:'embedding',section:'接入',title:'MEM 查嵌入表，得到向量 X',where:'MEMW',kind:'memory',sample:'embedding',from:['MEMW__B0R0L0','MEMW__WEIGHTS'],to:['MEMW__R0','VX__IN0'],shape:`ID [${B},${T}] → X [${B},${T},${D}]`,traffic:entries(['读取 ID',inputBytes,'B × T × 4'],['查表读取',a,'B × T × D × 2'],['X 写回',a*write,'B × T × D × 2 × 写回开关']),formulas:[`每个 ID 选择 ${D} 个 FP16 元素`,`${B} × ${T} × ${D} × 2 = ${num(a)} B 向量数据`],reason:'ID 不是向量。每个 ID 索引一行已训练好的词嵌入权重，得到 D 维激活；查表主要消耗读取带宽。'});
  const layerStart=steps.length;
  const vector=(id,title,count,traffic,formula,extra={})=>add({id,section:id.startsWith('ffn')||id==='norm2'||id==='residual2'?'FFN':'Attention',title,where:'VX',kind:'vector',from:['MEMW__R0','VX__IN0'],to:['VX__A00','VX__OUT0'],vectorOps:count,traffic,formulas:[formula],...extra});
  const mm=(id,title,m,k,out,traffic,formula,extra={})=>add({id,section:id.startsWith('ffn')?'FFN':'Attention',title,where:'ME0',kind:'matrix',from:['MEME__WEIGHTS','ME0__X0'],to:['ME0__M00','ME0__SUM0'],flops:2*m*k*out,traffic,shape:`[${num(m)},${num(k)}] × [${num(k)},${num(out)}] → [${num(m)},${num(out)}]`,formulas:[`2 × M × K × N = 2 × ${num(m)} × ${num(k)} × ${num(out)} = ${num(2*m*k*out)} FLOPs`,formula],...extra});
  vector('norm1','Attention 前 RMSNorm',8*n*D,entries(['X 读取',a*write,'B T D × 2 × 写回开关'],['γ 权重',D*bw,'D × 2'],['归一化写回',a*write,'B T D × 2 × 写回开关']),'xᵢ / √(mean(x²)+ε) × γᵢ；等效成本设为 8 × BTD',{sample:'norm1',shape:`[${B},${T},${D}] → 同形状`,reason:'VXM 先平方、归约、求倒数平方根，再缩放。8 是等效成本假设，exp / rsqrt 不能直接看成一个真实时钟周期。'});
  mm('q','Q 投影',n,D,D,entries(['输入 X',a*write,'B T D × 2 × 写回开关'],['Wq 权重',D*D*bw,'D² × 2'],['Q 写回',a*write,'B T D × 2 × 写回开关']),'Q = X Wq；Q 拆成 H 个查询头',{sample:'q',reason:'同一输入行与 Wq 的每列做点积。MXM 持有当前权重块，输入沿流通道进入并形成输出部分和。'});
  for(const id of ['k','v'])mm(id,id.toUpperCase()+' 投影',n,D,K,entries(['输入 X',a*write,'B T D × 2 × 写回开关'],['W'+id+' 权重',D*K*bw,'D × Gd × 2'],[id.toUpperCase()+' 暂存',kvNew*write,'B T Gd × 2 × 写回开关']),`${id.toUpperCase()} = X W${id}；Gd = ${G} × ${d} = ${K}`,{sample:id,reason:`GQA 的 K/V 只有 ${G} 个头，查询头有 ${H} 个。每组 ${H/G} 个查询头共享一个 KV 头，不能把 K/V 参数量直接按 D² 计算。`});
  vector('rope','RoPE：旋转 Q/K，再对齐头布局',3*n*(D+K),entries(['Q/K 读取',n*(D+K)*ba*write,'B T (D+Gd) × 2 × 写回开关'],['Q/K 写回',n*(D+K)*ba*write,'B T (D+Gd) × 2 × 写回开关']),'[a,b] → [a cosθ − b sinθ, a sinθ + b cosθ]',{sample:'rope',where:'SE',from:['ME0__READOUT','SE__IN0'],to:['SE__PERM','VX__A00'],shape:`Q[${B},${H},${T},${d}]；K[${B},${G},${T},${d}]`,reason:'SXM 负责让元素对齐，VXM 执行成对旋转。每对元素按 4 乘 + 2 加计，位置系数已准备；系数生成和实际布局需要编译器安排。'});
  add({id:'kv_write',section:'Attention',title:'向 MEM 的 KV 缓存追加本轮位置',where:'MEME',kind:'memory',sample:'kv',from:['ME0__READOUT','VX__OUT0'],to:['MEME__B0R0L0','MEME__B1R0L0'],shape:`新增 K/V [${B},${G},${T},${d}]；有效长度 ${S}`,traffic:entries(['K/V 提交写入',2*kvNew,'2 × B × T × Gd × 2 B']),formulas:[`新写入 = 2 × ${B} × ${T} × ${K} × 2 = ${num(2*kvNew)} B`,`整模型 KV = 2 × B × S × Gd × 2 × L = ${bytes(capacity.kv)}`],reason:p.mode==='decode'?`历史 ${S-1} 个位置保留，本轮只追加 1 个位置。不是把全部历史 KV 重新写一遍。`:'Prefill 一次建立输入位置的 KV。每个模型层各有缓存，KV 是中间表示，不是完整答案。'});
  add({id:'qk',section:'Attention',title:'QKᵀ：MXM 逐头计算相关得分',where:'ME0',kind:'matrix',sample:'qk',from:['MEME__B0R0L0','ME0__X0'],to:['ME0__M00','ME0__SUM0'],shape:`每头 [T,d]×[d,S]；合计 [${B},${H},${T},${S}]`,flops:2*B*H*pairs*d,traffic:entries(['读取 Q',a*write,'B T D × 2 × 写回开关'],['历史 K',kvReads,'B S Gd × 2 × KV 重读因子'],['得分写回',score*write,'B H T S × 4 × 写回开关']),formulas:[`2 × B × H × 配对数 × d = 2 × ${B} × ${H} × ${num(pairs)} × ${d}`,p.skipCausal&&p.mode==='prefill'?'配对数 = S(S+1)/2；假设跳过上三角乘加':'配对数 = T×S；因果屏蔽本身不保证减少乘加'],reason:'查询 Q 在 MXM 等待，K 从 MEM 读取。GQA 减少 KV 容量，但 H 个查询头仍各自计算得分，不能把这里的头数改成 G。'});
  vector('mask','缩放得分并应用因果遮罩',2*B*H*T*S,entries(['得分读写',2*score*write,'2 × B H T S × 4 × 写回开关']),'score = QKᵀ / √d；未来位置设为 −∞',{sample:'mask',from:['ME0__READOUT'],to:['VX__A00','VX__A10'],shape:`[${B},${H},${T},${S}]`,reason:'缩放防止点积随头维度增大而过大；因果遮罩阻止当前位置读取未来。已存储的未来 K/V 并没有被删除。'});
  vector('softmax','VXM：稳定 Softmax 的四个动作',8*scoreOps,entries(['得分读取与概率写回',2*score*write,'2 × B H T S × 4 × 写回开关']),'m=max(score)；eᵢ=exp(scoreᵢ−m)；Z=Σeᵢ；pᵢ=eᵢ/Z',{sample:'softmax',from:['ME0__READOUT','VX__IN0'],to:['VX__A00','VX__A10','VX__A20','VX__OUT0'],shape:`每个 [S] 行独立归一化；共 ${num(B*H*T)} 行`,reason:'Softmax 需要归约与非线性计算。这里用每项 8 个等效基本操作估算，不能直接用 MXM 的 188 TFLOP/s 峰值算它的真实延迟。'});
  vector('p_cast','VXM：把概率转换为矩阵输入精度',B*H*T*S,entries(['FP32 P 读取',score*write,'B H T S × 4 × 写回开关'],['FP16 P 写回',score/2*write,'B H T S × 2 × 写回开关']),'Softmax FP32 → 本估算模型的 FP16 矩阵输入',{sample:'p_cast',shape:`[${B},${H},${T},${S}]；每元素 4 B → 2 B`,reason:'右侧矩阵峰值对应 FP16 输入。这里把概率的精度转换独立列出，避免用 FP32 输入流量和 FP16 算力混算。小数值例子不模拟实际 FP16 舍入。'});
  add({id:'pv',section:'Attention',title:'PV：概率与 V 在 MXM 加权汇总',where:'ME0',kind:'matrix',sample:'pv',from:['VX__OUT0','MEME__B1R0L0'],to:['ME0__M00','ME0__SUM0'],shape:`每头 [T,S]×[S,d] → [T,d]；共 ${B}×${H} 个头`,flops:2*B*H*pairs*d,traffic:entries(['读取 FP16 P',score/2*write,'B H T S × 2 × 写回开关'],['历史 V',kvReads,'B S Gd × 2 × KV 重读因子'],['上下文输出写回',a*write,'B T D × 2 × 写回开关']),formulas:[`2 × B × H × 配对数 × d = ${num(2*B*H*pairs*d)} FLOPs`,'输出 = Σ pᵢ × Vᵢ；同组查询头复用相应 KV 头'],reason:'绿色概率从 VXM 出发，V 从 MEM 出发，相乘和求和发生在 MXM。注意力权重没有在存储格内自行完成运算。'});
  add({id:'concat',section:'Attention',title:'SXM：合并头并对齐 Wo 输入',where:'SE',kind:'reorder',sample:'concat',from:['ME0__READOUT','SE__IN0'],to:['SE__PERM','SE__OUT0'],shape:`[${B},${H},${T},${d}] → [${B},${T},${D}]`,traffic:entries(['布局读写',2*a*write,'2 × B T D × 2 × 写回开关']),formulas:['头的拼接改变布局，不增加矩阵乘法 FLOPs'],reason:'SXM 按下一算子需要的位置组织元素。理想流式布局可避免完整中间张量写回，但不意味着实际重排没有延迟。'});
  mm('wo','Wo 输出投影',n,D,D,entries(['各头输出',a*write,'B T D × 2 × 写回开关'],['Wo 权重',D*D*bw,'D² × 2'],['输出写回',a*write,'B T D × 2 × 写回开关']),'AttentionOut = Concat(heads) Wo',{sample:'wo',reason:'各头已经汇总自己的 V；Wo 再混合不同头的表示，输出仍为 D 维。'});
  vector('residual1','VXM：Attention 残差相加',n*D,entries(['两路读取与一路写入',3*a*write,'3 × B T D × 2 × 写回开关']),'Y = 原始 X + AttentionOut',{sample:'residual1',shape:`[${B},${T},${D}] + 同形状`,reason:'保留的原始输入与新的注意力输出相加。下一块 FFN 接收这个结果，而不是只接收 Softmax 概率。'});
  vector('norm2','FFN 前 RMSNorm',8*n*D,entries(['激活读取',a*write,'B T D × 2 × 写回开关'],['γ 权重',D*bw,'D × 2'],['输出写回',a*write,'B T D × 2 × 写回开关']),'x̂ = RMSNorm(Y)；等效操作数 = 8BTD',{sample:'norm2',shape:`[${B},${T},${D}]`,reason:'这一层归一化为 FFN 准备输入。它与 Attention 前的归一化使用不同的模型参数。'});
  for(const[id,title]of [['ffn_gate','Gate 投影 Wg'],['ffn_up','Up 投影 Wu']])mm(id,title,n,D,F,entries(['输入激活',a*write,'B T D × 2 × 写回开关'],[title+' 权重',D*F*bw,'D F × 2'],['F 维输出写回',n*F*ba*write,'B T F × 2 × 写回开关']),`${id==='ffn_gate'?'gate':'up'} = x̂ × ${id==='ffn_gate'?'Wg':'Wu'}`,{sample:id,reason:`FFN 在每个位置独立运算，将 D=${D} 扩到 F=${F}。Gate 和 Up 是两套不同的权重，不能合并为一次乘法的参数量。`});
  vector('ffn_silu','VXM：SiLU 激活 Gate',8*n*F,entries(['Gate 读写',2*n*F*ba*write,'2 × B T F × 2 × 写回开关']),'SiLU(g) = g × sigmoid(g) = g / (1+exp(−g))',{sample:'ffn_silu',shape:`[${B},${T},${F}] → 同形状`,reason:'SiLU 是逐元素非线性。负值不会像 ReLU 那样全部清零；指数与除法的耗时用可编辑的等效向量吞吐近似。'});
  vector('ffn_mul','VXM：门控结果逐元素乘 Up',n*F,entries(['两路输入和一路输出',3*n*F*ba*write,'3 × B T F × 2 × 写回开关']),'hidden = SiLU(gate) ⊙ up',{sample:'ffn_mul',shape:`[${B},${T},${F}] ⊙ 同形状`,reason:'⊙ 表示同一位置、同一通道的两个数相乘。这一步不是 F×F 矩阵乘法，因此基本运算量只有 BTF。'});
  mm('ffn_down','Down 投影 Wd：压回 D 维',n,F,D,entries(['F 维输入',n*F*ba*write,'B T F × 2 × 写回开关'],['Wd 权重',F*D*bw,'F D × 2'],['D 维输出',a*write,'B T D × 2 × 写回开关']),'FFNOut = hidden × Wd',{sample:'ffn_down',reason:'Wd 将每个位置的 F 维结果重新混合为 D 维，以便与残差路径相加。它同样消耗 2BTDF 次基本运算。'});
  vector('residual2','VXM：FFN 残差相加',n*D,entries(['两路输入和一路输出',3*a*write,'3 × B T D × 2 × 写回开关']),'Z = Y + FFNOut',{sample:'residual2',shape:`[${B},${T},${D}]`,reason:'完整 Transformer 层输出形成；后续层会重复自己的 Attention 和 FFN，且使用自己的权重与 KV。'});
  const layerEnd=steps.length,layerSteps=steps.slice(layerStart,layerEnd),sum=(list,k)=>list.reduce((a,x)=>a+x[k],0);
  const layer={low:sum(layerSteps,'low'),high:sum(layerSteps,'high'),flops:sum(layerSteps,'flops'),vectorOps:sum(layerSteps,'vectorOps'),memoryBytes:sum(layerSteps,'memoryBytes'),attentionLow:sum(layerSteps.filter(s=>s.section==='Attention'),'low'),ffnLow:sum(layerSteps.filter(s=>s.section==='FFN'),'low')};
  add({id:'layers',section:'输出',title:`继续其余 ${L-1} 个 Transformer 层`,where:'ME0',kind:'repeat',from:['ME0__READOUT','MEME__WEIGHTS'],to:['VX__OUT0'],shape:`每层 [${B},${T},${D}] → 同形状；L=${L}`,flops:layer.flops*(L-1),vectorOps:layer.vectorOps*(L-1),traffic:entries(['剩余层片上读写',layer.memoryBytes*(L-1),'(L−1) × 单层流量']),low:layer.low*(L-1),high:layer.high*(L-1),fixedMs:0,bound:'重复的算子链',formulas:[`其余层时间 = ${L-1} × (${time(layer.low)} — ${time(layer.high)})`],reason:'这里累计剩余层的逐算子时间，不把多个层的 FLOPs 合并后假设它们能同时运行。单芯片容量检查在右侧单独给出。'});
  add({id:'finalnorm',section:'输出',title:'取最后有效位置，执行最终 RMSNorm',sample:'finalnorm',where:'VX',kind:'vector',from:['MEMW__R0'],to:['VX__A00','VX__OUT0'],shape:`最后位置 [${B},${D}]`,vectorOps:8*B*D,traffic:entries(['最后位置读写与 γ',2*B*D*ba*write+D*bw,'2 × B D × 2 × 写回开关 + D×2']),formulas:['本次只预测下一个 Token，词表头只使用最后有效位置'],reason:'Prefill 的中间层处理全部输入位置，但生成第一个 Token 只需要最后位置的词表分数。本例不计算所有 S 个位置的输出词表。'});
  mm('lmhead','词表投影：得到每个候选的 logits',B,D,V,entries(['最后位置表示',B*D*ba*write,'B D × 2 × 写回开关'],['词表权重',D*V*bw,'D V × 2'],['FP32 logits',logitBytes,'B V × 4']),'logits = last_hidden × Wvocab',{section:'输出',reason:'词表投影仍由矩阵资源执行。本例词嵌入与词表输出共享权重，容量只计一次；执行时仍需读取权重。'});
  add({id:'pcie_out',section:'输出',title:'接入示例：logits 经 DMA / PCIe 回主机',where:'PCIE',kind:'pcie',from:['ME0__READOUT','DMA'],to:['PCIE','HOST__HOSTBUF'],shape:`${B} × ${V} × 4 B = ${bytes(logitBytes)}`,traffic:entries(['DMA 读取 logits',logitBytes,'B V × 4 B']),low:p.dmaUs/1000+Math.max(logitBytes/effective.pcie,logitBytes/effective.memory)*1000,high:p.dmaUs/1000+(logitBytes/effective.pcie+logitBytes/effective.memory)*1000,fixedMs:0,bound:'PCIe 返回',wireBytes:logitBytes,formulas:[`${num(logitBytes)} B ÷ ${num(effective.pcie/1e9)} GB/s + ${p.dmaUs} μs`],reason:'DMA 先从片上读取 logits，再传给主机。读取与 PCIe 传输可能重叠，因此分别给出重叠和串行估算。这里采用主机采样示例。若选择在设备侧完成，仅返回 ID 的流量会不同；本页不把示例位置当成 GroqCloud 的私有实现。'});
  add({id:'sample',section:'输出',title:'主机按 logits 选择 Token ID',where:'CPU',kind:'cpu',from:['HOST__HOSTBUF'],to:['HOST__SELECT','HOST__TOKEN'],shape:`每个请求 ${V} 个候选 → 1 个 ID`,low:p.samplingUs/1000,high:p.samplingUs/1000,fixedMs:0,bound:'主机采样',formulas:[`采样 / 解码预算 = ${p.samplingUs} μs（可编辑假设）`],reason:'Attention 内部的 Softmax 权重与这里的词表分布是不同对象。这里选择示例 Token“芯片”；不会运行真实语言模型。'});
  add({id:'decode_text',section:'输出',title:'增量解码，写入服务发送缓冲',where:'CPU',kind:'cpu',from:['HOST__TOKEN'],to:['HOST__BYTES','HOST__HOSTBUF'],shape:'Token ID → UTF-8 字节 / SSE 片段',low:0,high:0,fixedMs:0,bound:'已计入采样 / 解码预算',wireBytes:setup.outputBytes,formulas:[`示例 SSE 片段 = ${setup.outputBytes} B；解码时间归入上一项预算`],reason:'一个 Token 未必是完整汉字或词。这里按一个可返回片段演示；服务发送缓冲与用户已经收到是不同状态。'});
  add({id:'send',section:'输出',title:'服务器 NIC 发送，用户收到新片段',where:'NET',kind:'network',from:['HOST__HOSTBUF','HOST__NETBUF'],to:['HOST__USERBUF'],shape:`${setup.outputBytes} B 示例片段`,low:network(setup.outputBytes,p.rttMs/2),high:network(setup.outputBytes,p.rttMs/2),fixedMs:0,bound:'外部返回网络',wireBytes:setup.outputBytes,formulas:[`${setup.outputBytes} B ÷ ${num(effective.network/1e6)} MB/s + RTT/2`,'持续流式输出的固定传播项不重复加到 TPOT 中'],reason:'用户首片段等待包含网络传播。连续片段之间的稳态间隔，不会因为每个片段都要传播就反复额外增加一个单程 RTT。'});
  let low=0,high=0;for(const s of steps){s.startLow=low;s.startHigh=high;low+=s.low;high+=s.high;s.endLow=low;s.endHigh=high;}
  const total={low,high,flops:sum(steps,'flops'),memoryBytes:sum(steps,'memoryBytes'),tpLow:p.mode==='decode'?low-p.rttMs/2:null,tpHigh:p.mode==='decode'?high-p.rttMs/2:null,valid:capacity.fits};
  const deployment={bytes:capacity.weights,low:p.dmaUs/1000+capacity.weights/effective.pcie*1000,note:'模型冷部署的权重传输，不加入每次 Prompt / Token 的热路径；还未计入磁盘读取、编译和分片装载。'};
  return{p,dimensions,effective,capacity,setup,steps,layer,total,deployment,layerStart,layerEnd};
 }
 const matmul=(a,b)=>a.map(row=>b[0].map((_,c)=>row.reduce((v,x,k)=>v+x*b[k][c],0)));
 const transpose=a=>a[0].map((_,c)=>a.map(r=>r[c]));
 const norm=a=>a.map(row=>{const r=Math.sqrt(row.reduce((s,v)=>s+v*v,0)/row.length+1e-5);return row.map(v=>v/r);});
 const add=a=>(b)=>a.map((r,i)=>r.map((v,j)=>v+b[i][j]));
  const rotate=rows=>rows.map((r,pos)=>r.map((v,i)=>{const k=Math.floor(i/2)*2,angle=pos;return i%2===0?r[k]*Math.cos(angle)-r[k+1]*Math.sin(angle):r[k]*Math.sin(angle)+r[k+1]*Math.cos(angle);}));
 function sample(mode='prefill'){
  const X=[[1,0,1,0],[0,1,0,1],[1,1,0,1]],N=norm(X),Wq=[[.5,0,.25,0],[0,.5,0,.25],[.25,0,.5,0],[0,.25,0,.5]],Wk=[[.5,0],[0,.5],[.25,0],[0,.25]],Wv=[[1,.5],[.5,1],[0,.5],[.5,0]],Wo=[[.5,0,.25,0],[0,.5,0,.25],[.25,0,.5,0],[0,.25,0,.5]],Q=matmul(N,Wq),K=matmul(N,Wk),V=matmul(N,Wv),Qr=rotate(Q,2),Kr=rotate(K,1);
  const headQ=Qr.map(r=>r.slice(0,2)),raw=matmul(headQ,transpose(Kr)),scaled=raw.map(r=>r.map(v=>v/Math.sqrt(2))),masked=scaled.map((r,i)=>r.map((v,j)=>j>i?-Infinity:v));
  const soft=rows=>rows.map(r=>{const m=Math.max(...r),e=r.map(v=>Math.exp(v-m)),z=e.reduce((a,b)=>a+b,0);return e.map(v=>v/z);});
  const P=soft(masked),C=matmul(P,V),raw2=matmul(Qr.map(r=>r.slice(2)),transpose(Kr)),P2=soft(raw2.map((r,i)=>r.map((v,j)=>j>i?-Infinity:v/Math.sqrt(2)))),C2=matmul(P2,V),concat=C.map((r,i)=>r.concat(C2[i])),projected=matmul(concat,Wo),Y=add(X)(projected),N2=norm(Y);
  const Wg=Array.from({length:4},(_,r)=>Array.from({length:6},(_,c)=>(((r+1)*(c+2)%7)-3)/5)),Wu=Array.from({length:4},(_,r)=>Array.from({length:6},(_,c)=>(((r+2)*(c+1)%9)-4)/6)),Wd=Array.from({length:6},(_,r)=>Array.from({length:4},(_,c)=>(((r+1)*(c+3)%8)-3)/7)),gate=matmul(N2,Wg),up=matmul(N2,Wu),silu=gate.map(r=>r.map(v=>v/(1+Math.exp(-v)))),hidden=silu.map((r,i)=>r.map((v,j)=>v*up[i][j])),down=matmul(hidden,Wd),Z=add(Y)(down);
  const pick=a=>mode==='decode'?[a.at(-1)]:a;
  const matrix=(title,input,weight,output)=>({title,type:'matrix',input:pick(input),weight,output:pick(output)});
  return{embedding:{title:'3 个位置，每个 4 维',type:'values',output:pick(X)},norm1:{title:'RMSNorm 后的 X',type:'norm',input:pick(X),output:pick(N)},q:matrix('Q = X̂Wq',N,Wq,Q),k:matrix('K = X̂Wk',N,Wk,K),v:matrix('V = X̂Wv',N,Wv,V),rope:{title:'位置旋转后的 Q 与 K',type:'rope',input:pick(Q),output:pick(Qr),extra:Kr},kv:{title:'K 与 V 按位置保留在 MEM',type:'values',input:Kr,output:V},qk:matrix('第 0 个查询头的 QKᵀ',headQ,transpose(Kr),raw),mask:{title:'缩放后，未来位置成为 −∞',type:'mask',input:pick(raw),output:pick(masked),extra:pick(scaled)},softmax:{title:'每行只在允许的位置上归一化',type:'softmax',input:pick(masked),output:pick(P)},pv:matrix('第 0 个查询头的 P × V',P,V,C),concat:{title:'两头输出合并为 4 维',type:'values',input:pick(C),output:pick(concat)},wo:matrix('混合各头的输出',concat,Wo,projected),residual1:{title:'原始 X 加 Attention 输出',type:'add',input:pick(X),weight:pick(projected),output:pick(Y)},norm2:{title:'FFN 的归一化输入',type:'norm',input:pick(Y),output:pick(N2)},ffn_gate:matrix('Gate = X̂ Wg',N2,Wg,gate),ffn_up:matrix('Up = X̂ Wu',N2,Wu,up),ffn_silu:{title:'SiLU 保留平滑的负值响应',type:'silu',input:pick(gate),output:pick(silu)},ffn_mul:{title:'SiLU(Gate) 与 Up 逐元素相乘',type:'multiply',input:pick(silu),weight:pick(up),output:pick(hidden)},ffn_down:matrix('F=6 压回 D=4',hidden,Wd,down),residual2:{title:'本层输出 Z = Y + FFNOut',type:'add',input:pick(Y),weight:pick(down),output:pick(Z)},p_cast:{title:'概率从 FP32 转为 FP16 输入（不模拟舍入）',type:'cast',input:pick(P),output:pick(P)},finalnorm:{title:'数值例子只含一层，取其最后位置归一化',type:'norm',input:[Z.at(-1)],output:norm([Z.at(-1)])}};
 }
 const api={defaults,presets,sources,validate,build,sample,matmul,transpose,num,time,bytes,ops};root.GROQ_PERFORMANCE=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window==='undefined'?globalThis:window);
