/* UTF-8 · 在固定硬件之上显示具名对象与事件；详情层分为数据流、执行顺序、计算过程和参数依据。 */
import * as T from 'three';
import {DATA_FLOW_DIAGRAMS} from './data-flow-diagrams.mjs';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=v=>typeof v==='number'&&!Number.isInteger(v)?String(Number(v.toPrecision(4))):window.SEMANTIC_EXECUTION.num(v);
const injectStyles=()=>{if(document.getElementById('se-teaching-style'))return;const s=document.createElement('style');s.id='se-teaching-style';s.textContent=`
#spatial-lab .se-drag-handle{cursor:grab;user-select:none}.se-drag-handle.dragging{cursor:grabbing}
#spatial-lab .se-drag-tip{font:9px/1.2 Segoe UI,sans-serif;color:#82939c;white-space:nowrap}
#spatial-lab .se-teach-tabs{display:flex;gap:4px;align-items:center;border-bottom:1px solid #c7d4da;padding:2px 0 5px;margin-bottom:18px}
#spatial-lab .se-teach-tabs button{min-height:22px;padding:2px 8px;font-size:10px}#spatial-lab .se-teach-tabs button[aria-pressed=true]{background:#526f80;color:#fff;border-color:#526f80}
#spatial-lab .se-sequence{display:grid;grid-template-columns:repeat(auto-fit,minmax(115px,1fr));gap:5px;overflow:auto;min-height:0;flex:1;padding:2px 0}
#spatial-lab .se-seq-step{border:1px solid #cad5da;background:#eef2f4;padding:6px;border-radius:3px;min-width:0;color:#526975}
#spatial-lab .se-seq-step.current{background:#f1dfc8;border-color:#bc824b;color:#74481f}.se-seq-step.done{background:#e2eee7;border-color:#a8c3b1}
#spatial-lab .se-seq-step b{display:block;font-size:10px}.se-seq-step small{display:block;font-size:9px;line-height:1.35;margin-top:2px;overflow-wrap:anywhere}
#spatial-lab .se-compare{display:grid;grid-template-columns:1fr 1fr;gap:8px;flex:1;min-height:0;overflow:auto}
#spatial-lab .se-compare-card{border:1px solid #c8d4da;background:#f0f4f5;padding:8px;border-radius:4px}.se-compare-card h4{margin:0 0 5px;font-size:11px;color:#3d5969}.se-compare-card p{font-size:10px;line-height:1.55;color:#607580;margin:0}.se-compare-card code{font:10px Consolas,monospace;color:#3d6578}
#spatial-lab .se-evidence-grid{display:grid;grid-template-columns:1fr 1fr;gap:5px 8px;overflow:auto;min-height:0;flex:1;padding:1px 0}
#spatial-lab .se-evidence-row{display:grid;grid-template-columns:86px minmax(0,1fr);gap:7px;align-items:start;border:1px solid #cbd8dd;border-radius:4px;background:#f4f7f8;padding:6px 7px;font-size:10px;line-height:1.35}
#spatial-lab .se-evidence-row b{color:#456274;font-weight:700}.se-evidence-row span{color:#5e737d;overflow-wrap:anywhere}
#spatial-lab .se-chip-path{display:flex;align-items:center;gap:4px;flex-wrap:wrap;margin-top:5px;font:9px Consolas,monospace;color:#486879}.se-chip-path span{background:#e2eaee;border:1px solid #becdd4;padding:2px 5px;border-radius:3px}.se-chip-path i{font-style:normal;color:#899aa2}
`;document.head.append(s);};
const unitName=u=>({MEM:'MEM · 读写',MXM:'MXM · 矩阵乘',VXM:'VXM · 向量/归约',SXM:'SXM · 重排',CPU:'CPU · 服务/分词',NETWORK:'网络交接'}[u]||u||'控制');
const eventState=(program,event)=>{
 if(event.valid)return program.type==='tokenize'?'18 个 input_ids 已就绪':program.type==='ingress'?'Host 原文缓冲已就绪':'本步完成';
 if(event.stalled)return'背压 · 数据保持';
 if(program.type==='ingress')return event.index===0?'用户侧已准备':'Prompt 传输中';
 if(program.type==='tokenize')return event.write.some(x=>x.startsWith('results['))?'已写入 '+(event.revealed||0)+' / '+program.meta.tokens.length:'逐字片处理中';
 return'中间状态';
};
const routePoint=(anchors,...names)=>{for(const name of names)if(anchors[name])return anchors[name];return null;};
const lpuRoutes={
 router:['MEM_N','SXM_N','MXM_N','VXM','MEM_N'],
 gateup:['MEM_N','SXM_N','MXM_N','MEM_S'],
 silu:['MEM_S','SXM_S','VXM','MEM_S'],
 down:['MEM_S','SXM_S','MXM_S','MEM_N'],
 shared:['MEM_N','SXM_N','MXM_S','VXM','MEM_S'],
 combine:['C2C_NW','SXM_N','VXM','MEM_N'],
 'layer-loop':['ICU','MEM_N','SXM_N','MXM_N','MEM_S','VXM','C2C_NW','ICU']
};
const lpuLabel={MEM_N:'MEM 北 · 激活 / 权重',MEM_S:'MEM 南 · 中间结果 / 输出',SXM_N:'SXM 北 · tile 重排 / DMA',SXM_S:'SXM 南 · 向量重排 / DMA',MXM_N:'MXM 北 · MAC tile',MXM_S:'MXM 南 · 输出矩阵',VXM:'VXM · SiLU / 归约',C2C_NW:'C2C · 片间部分和',ICU:'ICU · 描述符 / barrier'};
const flowOwner=step=>{const id=step?.id||'';if(['gpu-egress','afd','tray','return','gpu-return','dispatch'].includes(id))return'transport';if(['prompt','tokenize','schedule','sample','result-handoff'].includes(id))return'host';if(step?.level==='chip'||String(step?.hardware||'').includes('LPX'))return'lpu';if(step?.level==='gpu'||String(step?.hardware||'').includes('GPU'))return'gpu';return'host';};
const ownerText=owner=>({gpu:'GPU · Attention / KV / 残差',lpu:'LPU · FFN / MoE / MXM / VXM',transport:'互联 · Ethernet / Fabric / C2C',host:'Host · Tokenizer / 调度 / 采样'})[owner]||owner;
function lpuRoute(step,ctx){
 if(ctx.level!=='chip'&&step.level!=='chip')return null;
 const ids=lpuRoutes[step.id]||(['gateup','silu','down','shared','combine','router'].includes(step.id)?lpuRoutes.gateup:null);
 if(!ids)return null;
 const anchors=ctx.hardware.anchors,nodes=ids.map((id,index)=>({id,index,point:routePoint(anchors,id,id==='MEM_N'?'MEM':id==='MEM_S'?'MEM':id==='MXM_N'?'MXM':id==='MXM_S'?'MXM':id),label:lpuLabel[id]||id})).filter(n=>n.point);
 return nodes.length>1?nodes:null;
}
function dataObjectLabel(step){return({router:'x + Wrouter → logits / Top-10',gateup:'x + Wgate + Wup → g,u',silu:'g,u → SiLU(g) ⊙ u = h',down:'h + Wdown → y',shared:'x → shared expert → yshared',combine:'y_local + y_peer → y', 'layer-loop':'layer_id + activation / KV / state'})[step.id]||step.output||step.title;}
function activeRouteIndex(event,nodes){
 const unit=String(event?.unit||'').toUpperCase();
 if(unit.includes('ICU')||unit.includes('SCHEDULER')||unit.includes('SYNC'))return 0;
 const key=unit.includes('MXM')?'MXM':unit.includes('VXM')?'VXM':unit.includes('SXM')?'SXM':unit.includes('MEM')?'MEM':unit;
 const match=nodes.findIndex(n=>String(n.id).includes(key));
 if(match<0)return Math.min(nodes.length-2,Math.max(0,event?.index||0));
 return Math.min(nodes.length-2,Math.max(0,match===0?0:match-1));
}

export class SemanticView{
 constructor({element,layer,sprite,anchor,context,onChange}){Object.assign(this,{element,layer,sprite,anchor,context,onChange});this.program=null;this.current=-1;this.markers=[];this.teachMode='detail';injectStyles();this.element.addEventListener('click',e=>{const b=e.target.closest('[data-teach-mode]');if(!b)return;e.preventDefault();e.stopPropagation();this.teachMode=b.dataset.teachMode;this.renderCurrent();});}
 load(program,step){
  this.program=program;this.step=step;this.current=-1;this.markers=[];const ctx=this.context(),anchors=ctx.hardware.anchors;
  this.readouts=[];this.links=[];this.routeNodes=lpuRoute(step,ctx);this.dataLabel=dataObjectLabel(step);this.payload=null;this.tokenSprites=[];this.promptSprite=null;this.templateSprite=null;
  const site=(key,point,label,position,meta={})=>{if(!point)return;const ring=new T.Mesh(new T.RingGeometry(.23,.31,32),new T.MeshBasicMaterial({color:0x527a90,transparent:true,opacity:.8,side:T.DoubleSide,depthTest:false}));ring.rotation.x=-Math.PI/2;ring.position.copy(point).add(new T.Vector3(0,.13,0));const pos=position||point.clone().add(new T.Vector3(0,1.3,0)),heading=this.sprite(label,'#294b5e',.5);heading.position.copy(pos);const leader=new T.Line(new T.BufferGeometry().setFromPoints([ring.position,pos.clone().add(new T.Vector3(0,-.2,0))]),new T.LineBasicMaterial({color:0x6c8b9a,transparent:true,opacity:.7,depthTest:false}));this.layer.add(ring,heading,leader);this.readouts.push({key,ring,heading,leader,position:pos,value:null,...meta});};
  if(program.type==='ingress'){
   const from=anchors.USER,to=anchors.HOST;site('source',from,'用户侧 · Prompt',from?.clone().add(new T.Vector3(-.65,1.55,0)));site('host',to,'Host · 请求接入缓冲',to?.clone().add(new T.Vector3(.65,1.55,0)));
   if(from&&to){const line=new T.Line(new T.BufferGeometry().setFromPoints([from.clone().add(new T.Vector3(0,.55,0)),to.clone().add(new T.Vector3(0,.55,0))]),new T.LineBasicMaterial({color:0x5f8597,transparent:true,opacity:.7,depthTest:false}));line.userData.ingressRoute=true;this.layer.add(line);this.links.push(line);this.payload=this.sprite(program.meta.payloadLabel,'#a35f25',.43);this.payload.userData.semanticPayload=true;this.layer.add(this.payload);}
  }else if(program.type==='tokenize'){
   const host=anchors.HOST;site('cpu',host,'Host CPU / RAM · Tokenizer',host?.clone().add(new T.Vector3(0,1.35,0)));
   if(host){this.promptSprite=this.sprite('原文缓冲 · '+program.meta.promptBytes+' B','#365f73',.34);this.promptSprite.position.copy(host).add(new T.Vector3(-3,2.02,.08));this.promptSprite.userData.semanticPrompt=true;this.layer.add(this.promptSprite);this.tokenSprites=program.meta.tokens.map((token,i)=>{const sp=this.sprite('['+i+'] '+token.text+' → '+token.id,'#9a5a24',.31);sp.position.copy(host).add(new T.Vector3(-3,2.76+i*.66,.1));sp.userData.semanticToken=i;sp.userData.baseScale=sp.scale.clone();sp.visible=false;this.layer.add(sp);return sp;});this.templateSprite=this.sprite('+ 12 个模板 Token → 18 input_ids','#32704e',.34);this.templateSprite.position.copy(host).add(new T.Vector3(-3,6.9,.1));this.templateSprite.visible=false;this.layer.add(this.templateSprite);}
  }else if(program.type==='transfer'){
   const route=program.meta.route;route.forEach((id,i)=>site(i,anchors[id],id==='NETWORK'?'Spectrum-X':id==='SLOT'?'LPX 入口':id==='CX9'?'ConnectX-9':id,anchors[id]?.clone().add(new T.Vector3(i%2?-.3:.3,1.7,0))));
   for(let i=0;i<route.length-1;i++){const a=anchors[route[i]],b=anchors[route[i+1]];if(!a||!b)continue;const line=new T.Line(new T.BufferGeometry().setFromPoints([a.clone().add(new T.Vector3(0,.55,0)),b.clone().add(new T.Vector3(0,.55,0))]),new T.LineBasicMaterial({color:0x71919d,transparent:true,opacity:.5}));line.userData.semanticRoute=true;line.userData.hop=i;this.layer.add(line);this.links.push(line);}
  }else if(this.routeNodes){
   this.routeNodes.forEach((node,i)=>site('lpu-'+i,node.point,node.label,node.point.clone().add(new T.Vector3(i%2?1.8:-1.8,1.45,0)),{routeIndex:i,routeId:node.id}));
   for(let i=0;i<this.routeNodes.length-1;i++){const a=this.routeNodes[i].point,b=this.routeNodes[i+1].point;const line=new T.Line(new T.BufferGeometry().setFromPoints([a.clone().add(new T.Vector3(0,.32,0)),b.clone().add(new T.Vector3(0,.32,0))]),new T.LineBasicMaterial({color:0x8da6ae,transparent:true,opacity:.32,depthTest:false}));line.userData.lpuRoute=true;line.userData.routeIndex=i;this.layer.add(line);this.links.push(line);}
  }else if(['gpu','chip'].includes(ctx.level)){site('memory',anchors.MEM,'存储资源 · 算例读写',new T.Vector3(-4.2,2.8,0));site('compute',anchors[program.type==='matrix'?'MXM':'VXM'],'执行资源 · 算例状态',new T.Vector3(4.2,2.8,0));
  }else if(anchors.HOST){const label={schedule:'Host · 请求调度 / 后端提交',sample:'Host · 采样 / 反分词','result-handoff':'Host · 输出响应服务'}[step.id]||'Host · 软件运行时';site('cpu',anchors.HOST,label);}
  this.show(0);
 }
 show(index){if(!this.program)return;index=Math.max(0,Math.min(this.program.events.length-1,index));if(this.current===index)return;this.current=index;this.renderCurrent();}
 renderCurrent(){if(!this.program||this.current<0)return;const p=this.program,e=p.events[this.current],ctx=this.context();this.layer.userData.semantic={type:p.type,event:this.current,count:p.events.length,valid:e.valid,revealed:e.revealed??null,received:e.received??null,total:e.total??null,stalled:!!e.stalled,instruction:e.instruction};this.syncHardware(e,ctx);this.syncDataObjects(e,ctx);this.element.innerHTML=this.flowHTML(ctx)+this.tabsHTML()+this.contentHTML(p,e,ctx);this.highlightFlow(ctx);this.element.dataset.semanticType=p.type;this.element.dataset.event=String(this.current);this.element.dataset.teachMode=this.teachMode;this.onChange?.(p,e);}
 tabsHTML(){return '<nav class="se-teach-tabs" aria-label="详情视图"><button data-teach-mode="compare" aria-pressed="'+(this.teachMode==='compare')+'">01 · 数据流</button><button data-teach-mode="sequence" aria-pressed="'+(this.teachMode==='sequence')+'">02 · 执行顺序</button><button data-teach-mode="detail" aria-pressed="'+(this.teachMode==='detail')+'">03 · 计算过程</button><button data-teach-mode="evidence" aria-pressed="'+(this.teachMode==='evidence')+'">04 · 参数 / 依据</button></nav>';}
 contentHTML(p,e,ctx){if(this.teachMode==='sequence')return this.sequenceHTML(p,e);if(this.teachMode==='compare')return this.compareHTML(p,e,ctx);if(this.teachMode==='evidence')return this.evidenceHTML(p,e,ctx);return this.detailHTML(p,e);}
 sequenceHTML(p,e){const items=p.events.map((x,i)=>'<div class="se-seq-step '+(i<e.index?'done':i===e.index?'current':'')+'"><b>'+(i+1)+'. '+esc(x.name)+'</b><small>'+esc(unitName(x.unit))+'</small><small>'+esc(x.instruction)+'</small></div>').join('');return '<section class="se-operator-pane" aria-label="执行顺序"><header class="se-header"><div><span class="se-kicker">02 · 执行顺序 · 不表示硬件 cycle</span><h3>这一步先做什么、后做什么</h3></div><strong class="se-valid '+(e.valid?'ready':'')+'">步骤 '+(e.index+1)+' / '+p.events.length+'</strong></header><div class="se-sequence">'+items+'</div><div class="se-readwrite"><span><b>当前读</b> '+esc(e.read.join('，')||'无新增读取')+'</span><span><b>当前写</b> '+esc(e.write.join('，')||'保持原状态')+'</span></div>'+this.footerHTML(p,e)+'</section>';}
 detailHTML(p,e){let prompt='';if(p.type==='tokenize')prompt='<div class="se-prompt">'+p.meta.tokens.map((t,i)=>'<span class="'+(i===e.activeToken?'active':i<(e.revealed||0)?'done':'pending')+'">'+esc(t.text)+'</span>').join('')+'</div>';const readSet=new Set(e.focus.filter(f=>f.role==='read').map(f=>f.id+':'+f.r+':'+f.c)),writeSet=new Set(e.focus.filter(f=>f.role==='write').map(f=>f.id+':'+f.r+':'+f.c)),holdSet=new Set(e.focus.filter(f=>f.role==='hold').map(f=>f.id+':'+f.r+':'+f.c));const tables=e.view.filter(id=>e.objects[id]).map(id=>{const o=e.objects[id];return '<section class="se-object"><h4>'+esc(o.label)+'</h4><table aria-label="'+esc(o.label)+'"><tbody>'+o.rows.map((r,ri)=>'<tr>'+r.map((v,ci)=>{const key=id+':'+ri+':'+ci,cls=v===null?'empty':writeSet.has(key)?'written':readSet.has(key)?'read':holdSet.has(key)?'held':'';return '<td data-object="'+esc(id)+'" data-row="'+ri+'" data-col="'+ci+'" class="'+cls+'" title="'+esc(id+'['+ri+','+ci+'] = '+(v===null?'尚未写入':String(v)))+'">'+(v===null?'·':esc(number(v)))+'</td>';}).join('')+'</tr>').join('')+'</tbody></table>'+(o.hint?'<small>'+esc(o.hint)+'</small>':'')+'</section>';}).join('');return '<section class="se-operator-pane" aria-label="当前算子"><header class="se-header"><div><span class="se-kicker">03 · 计算过程 · 事件 '+(e.index+1)+' / '+p.events.length+'</span><h3>'+esc(e.name)+'</h3></div><strong class="se-valid '+(e.valid?'ready':e.stalled?'stall':'')+'">'+esc(eventState(p,e))+'</strong></header>'+prompt+'<div class="se-equation"><code>'+esc(e.instruction)+'</code><span>'+esc(e.equation)+'</span></div><div class="se-tables">'+tables+'</div><div class="se-readwrite"><span><b>读</b> '+esc(e.read.join('，')||'无新增读取')+'</span><span><b>写</b> '+esc(e.write.join('，')||'保持原状态')+'</span></div>'+this.footerHTML(p,e)+'</section>';}
 evidenceHTML(p,e,ctx){const st=this.step||{};const rows=[['当前步骤',st.title||e.name],['算子 / 资源',st.unit||e.unit||'—'],['Tensor / 输出',st.output||'按事件表读取与写回'],['公式',st.formula||e.equation||'—'],['参考计算量',st.flops==null?'未公开':String(st.flops)+' FLOPs'],['参考数据量',st.tensorBytes==null?'未公开':String(st.tensorBytes)+' B'],['硬件落点',st.hardware||ctx.level||'—'],['执行范围',st.scope||'当前代表层；同构层由 LOOP 表示'],['参数依据',st.evidence||'模型实现或硬件公开资料未给出时保持未公开'],['边界规则',st.detail||'页面只显示可验证的事件顺序，不把演示假设当成实机规格']];return '<section class="se-operator-pane" aria-label="参数与依据"><header class="se-header"><div><span class="se-kicker">04 · 参数 / 依据</span><h3>这笔数据采用什么参数，依据是什么</h3></div><strong class="se-valid">公开 / 推演边界分开</strong></header><div class="se-evidence-grid">'+rows.map(([k,v])=>'<div class="se-evidence-row"><b>'+esc(k)+'</b><span>'+esc(v)+'</span></div>').join('')+'</div><div class="se-readwrite"><span><b>当前读</b> '+esc(e.read.join('，')||'无新增读取')+'</span><span><b>当前写</b> '+esc(e.write.join('，')||'保持原状态')+'</span></div>'+this.footerHTML(p,e)+'</section>';}
 compareHTML(p,e,ctx){let left,right,title='数据流';if(ctx.phase==='prefill'){left=['Prefill','一次处理完整输入上下文','全部模型层在 GPU 完成','建立上下文并得到首 Token'];right=['Decode','一次生成一个新 Token','复用历史状态','按层执行 GPU Attention ↔ LPX FFN'];}else if(['gateup','silu','down','router','dispatch','shared','combine'].includes(this.step.id)){left=['Attention','读取/更新历史状态','Q/K/V → QK → Softmax → PV','当前 AFD 推演中留在 GPU'];right=['FFN / MoE','主要处理当前层隐藏激活与权重','Gate/Up → 激活 → Down','当前 AFD 推演中送往 LPX'];}else if(ctx.shape.m.moe){left=['Dense FFN','每个 Token 走固定 FFN 权重','没有专家路由步骤','适合理解 27B Dense 路径'];right=['MoE','Router → Top-K → Expert → 合并','实际专家编号必须来自真实 Router','页面默认不编造专家 owner'];}else{left=['GPU','Prefill、Decode Attention、Cache/状态','这里表示公开资源类别','不推断具体 SM/HBM 地址'];right=['LPX','Decode 的 FFN / MoE 分工推演','MEM / MXM / VXM / SXM','不填造实机 cycle 或有效带宽'];}const card=a=>'<article class="se-compare-card"><h4>'+esc(a[0])+'</h4><p>'+a.slice(1).map(x=>esc(x)).join('<br>')+'</p></article>';return '<section class="se-operator-pane" aria-label="数据流"><header class="se-header"><div><span class="se-kicker">01 · 数据流</span><h3>'+title+'</h3></div><strong class="se-valid">只比较职责与数据方向</strong></header><div class="se-compare">'+card(left)+card(right)+'</div><div class="se-chip-path"><span>输入</span><i>→</i><span>'+esc(unitName(e.unit))+'</span><i>→</i><span>'+esc(eventState(p,e))+'</span></div>'+this.footerHTML(p,e)+'</section>';}
 footerHTML(p,e){return '<footer class="se-footer"><div><button data-action="micro-prev" '+(e.index===0?'disabled':'')+'>上一事件</button><button class="sl-primary" data-action="micro-next">'+(e.index===p.events.length-1?'进入下一算子':'下一事件')+' →</button></div><small>'+esc(p.basis)+'</small></footer>';}
 flowHTML(ctx){const current=flowOwner(this.step);return '<section class="se-flow-pane" aria-label="完整数据流程"><div class="se-flow-heading se-drag-handle" title="拖动移动窗口；双击恢复默认位置"><b>01 · 完整数据 flow</b><span class="se-drag-tip">拖动移动 · 双击复位</span><nav class="se-quick"><button data-stage-action="focus-token">分词</button><button data-stage-action="focus-ffn">FFN</button><button data-stage-action="focus-attn">Attention</button><button data-stage-action="focus-transfer">传输</button></nav><div class="se-window-zoom"><span>窗口</span><button data-action="float-zoom-out" aria-label="缩小悬浮窗口">−</button><button data-action="float-zoom-reset" title="恢复默认大小和位置">'+Math.round(ctx.zoom*100)+'%</button><button data-action="float-zoom-in" aria-label="放大悬浮窗口">+</button></div></div><div class="se-owner-legend"><span class="owner-gpu">GPU · Attention / KV / 残差</span><span class="owner-lpu">LPU · FFN / MoE / MXM / VXM</span><span class="owner-transport">互联 · Ethernet / Fabric / C2C</span><span class="owner-host">Host · Tokenizer / 调度 / 采样</span><strong class="se-owner-current owner-'+current+'">当前：'+esc(ownerText(current))+'</strong></div><div class="se-flow-row"><b>Prefill</b>'+DATA_FLOW_DIAGRAMS.prefill+'</div><div class="se-flow-row"><b>Decode</b>'+DATA_FLOW_DIAGRAMS.decode+'</div><div class="se-flow-caption">'+(ctx.phase==='prefill'?'Prefill · GPU 执行全部模型层':'Decode · GPU Attention / LPX FFN 分工推演')+' · L'+ctx.layer+' / '+ctx.shape.m.layers+' · T='+ctx.shape.T+' · S='+ctx.shape.S+'<span>流程节点可展开算子 · 滚轮缩放窗口</span></div></section>';}
 highlightFlow(ctx){const id=this.step.id;let active;if(ctx.phase==='prefill')active=id==='prompt'?'P0':id==='tokenize'?'P1':['embedding','schedule','expand'].includes(id)?'P2':['finalnorm','lmhead'].includes(id)?'P4':['sample','result-handoff'].includes(id)?'P5':'P3';else active=id==='schedule'?'D0':['embedding','expand'].includes(id)?'D1':['gpu-egress','afd','tray','dispatch'].includes(id)?'D3':['gateup','silu','down','router','shared','combine'].includes(id)?'D4':['return','gpu-return'].includes(id)?'D5':id==='ffnwrite'?'D6':['finalnorm','lmhead','result-handoff','sample'].includes(id)?'D7':'D2';const owners=ctx.phase==='prefill'?{P0:'host',P1:'host',P2:'gpu',P3:'gpu',P4:'gpu',P5:'host'}:{D0:'host',D1:'gpu',D2:'gpu',D3:'transport',D4:'lpu',D5:'transport',D6:'gpu',D7:'gpu'};for(const node of this.element.querySelectorAll('.se-flow-pane g.node')){const key=node.id.match(/(?:flowchart-)?([PD][0-7])-/)?.[1];if(!key)continue;node.dataset.flowNode=key;node.setAttribute('role','button');node.setAttribute('tabindex','0');node.setAttribute('aria-label','展开 '+node.textContent.trim());node.classList.toggle('flow-active',key===active);node.classList.toggle('flow-complete',ctx.phase==='decode'&&key[0]==='P');for(const owner of ['gpu','lpu','transport','host'])node.classList.toggle('owner-'+owner,owners[key]===owner);}this.element.dataset.activeFlow=active;}
 syncHardware(e,ctx){const p=this.program,active=this.routeNodes?activeRouteIndex(e,this.routeNodes):null;for(const r of this.readouts){let words='';if(p.type==='ingress')words=r.key==='source'?(e.index===0?'正文已准备 · '+p.meta.total+' B':'正文只发送这一次'):(e.valid?'已接收 '+p.meta.total+' / '+p.meta.total+' B':'接收等待');else if(p.type==='transfer'){const n=r.key,hop=e.hop||0;words=n===0?'TX 8 B · 保持':n<=hop?'已接收 8 / 8 B':n===hop+1?'RX '+(e.received||0)+' / 8 B':'等待上游';if(n===hop+1&&e.stalled)words+=' · ready=0';}else if(r.routeIndex!==undefined){const isActive=active!==null&&(r.routeIndex===active||r.routeIndex===active+1);words=isActive?this.dataLabel:'';}else if(r.key==='cpu')words=e.hardwareStatus||eventState(p,e);else if(r.key==='memory'){const reg=e.objects.reg?.rows[0];words=reg?'a='+number(reg[0])+'  b='+number(reg[1]):e.valid?'输出已提交':e.write.length?'写 '+e.write.join(', '):'输入保持';}else{const reg=e.objects.reg?.rows[0],stat=e.objects.stat?.rows[0];words=reg?'ACC = '+number(reg[3]):stat?stat.map(number).join(' / '):e.valid?'结果有效':'本地中间状态';}if(r.value){r.value.material.map.dispose();r.value.material.dispose();this.layer.remove(r.value);}r.value=this.sprite(words,e.stalled?'#9b6c2d':e.valid?'#32764d':r.routeIndex!==undefined?'#9a6b2e':'#355e75',.46);r.value.position.copy(r.position).add(new T.Vector3(0,-.58,0));this.layer.add(r.value);const showValue=r.routeIndex===undefined||r.routeIndex===active||r.routeIndex===active+1;for(const o of [r.ring,r.heading,r.leader])o.visible=ctx.follow; r.value.visible=ctx.follow&&showValue;}for(const line of this.links){line.visible=ctx.follow;if(line.userData.semanticRoute){const hop=line.userData.hop,activeHop=e.hop||0;line.material.color.set(hop===activeHop?(e.stalled?0xba873a:e.accepted?0x438662:0x46799b):0xa4b3b9);line.material.opacity=hop===activeHop?1:.35;}else if(line.userData.ingressRoute){line.material.color.set(e.valid?0x438662:e.index===1?0xc27a32:0x5f8597);line.material.opacity=e.index===1?1:.62;}else if(line.userData.lpuRoute){const hop=line.userData.routeIndex;line.material.color.set(hop===active?0xc27a32:hop<(active??-1)?0x47866c:0x8da6ae);line.material.opacity=hop===active?1:hop<(active??-1)? .7:.25;}}}
 syncDataObjects(e,ctx){
  if(this.promptSprite)this.promptSprite.visible=ctx.follow;
  if(this.tokenSprites?.length){const revealed=e.revealed||0;this.tokenSprites.forEach((sp,i)=>{sp.visible=ctx.follow&&i<revealed;sp.scale.copy(sp.userData.baseScale).multiplyScalar(i===e.activeToken?1.12:1);});if(this.templateSprite)this.templateSprite.visible=ctx.follow&&e.valid&&e.activeToken===-1;}
  if(this.payload)this.payload.visible=ctx.follow;
 }
 updateProgress(eventFloat){
  if(!this.payload||this.program?.type!=='ingress')return;const events=this.program.events,index=Math.max(0,Math.min(events.length-1,Math.floor(eventFloat))),event=events[index],local=Math.max(0,Math.min(1,eventFloat-index)),smooth=local*local*(3-2*local),from=event.routeStart??0,to=event.routeEnd??from,t=from+(to-from)*smooth,anchors=this.context().hardware.anchors,a=anchors.USER,b=anchors.HOST;if(a&&b)this.payload.position.lerpVectors(a,b,t).add(new T.Vector3(0,2.2,0));
 }
 get event(){return this.program?.events[this.current];}
 sizeLabels(camera,height){for(const r of this.readouts||[])for(const sp of [r.heading,r.value]){if(!sp)continue;const aspect=sp.scale.x/sp.scale.y,size=2*sp.position.distanceTo(camera.position)*Math.tan(T.MathUtils.degToRad(camera.fov)/2)*20/height;sp.scale.set(size*aspect,size,1);}}
}
