/* UTF-8 · 在固定硬件之上显示具名对象、整机数据流与公开 TSP 指令教学。 */
import * as T from 'three';
import {DATA_FLOW_DIAGRAMS} from './data-flow-diagrams.mjs';
import {compileTeachingInstructions,activeInstructionIndexes} from './tsp-instruction-teaching.mjs';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=v=>typeof v==='number'&&!Number.isInteger(v)?String(Number(v.toPrecision(4))):window.SEMANTIC_EXECUTION.num(v);
const injectStyles=()=>{if(document.getElementById('se-teaching-style'))return;const s=document.createElement('style');s.id='se-teaching-style';s.textContent=`
#spatial-lab .se-drag-handle{cursor:grab;user-select:none}.se-drag-handle.dragging{cursor:grabbing}
#spatial-lab .se-drag-tip{font:9px/1.2 Segoe UI,sans-serif;color:#82939c;white-space:nowrap}
#spatial-lab .se-teach-tabs{display:flex;gap:4px;align-items:center;border-bottom:1px solid #c7d4da;padding:2px 0 5px}
#spatial-lab .se-teach-tabs button{min-height:22px;padding:2px 8px;font-size:10px}#spatial-lab .se-teach-tabs button[aria-pressed=true]{background:#526f80;color:#fff;border-color:#526f80}
#spatial-lab .se-sequence{display:grid;grid-template-columns:repeat(auto-fit,minmax(115px,1fr));gap:5px;overflow:auto;min-height:0;flex:1;padding:2px 0}
#spatial-lab .se-seq-step{border:1px solid #cad5da;background:#eef2f4;padding:6px;border-radius:3px;min-width:0;color:#526975}
#spatial-lab .se-seq-step.current{background:#f1dfc8;border-color:#bc824b;color:#74481f}.se-seq-step.done{background:#e2eee7;border-color:#a8c3b1}
#spatial-lab .se-seq-step b{display:block;font-size:10px}.se-seq-step small{display:block;font-size:9px;line-height:1.35;margin-top:2px;overflow-wrap:anywhere}
#spatial-lab .se-compare{display:grid;grid-template-columns:1fr 1fr;gap:8px;flex:1;min-height:0;overflow:auto}
#spatial-lab .se-compare-card{border:1px solid #c8d4da;background:#f0f4f5;padding:8px;border-radius:4px}.se-compare-card h4{margin:0 0 5px;font-size:11px;color:#3d5969}.se-compare-card p{font-size:10px;line-height:1.55;color:#607580;margin:0}.se-compare-card code{font:10px Consolas,monospace;color:#3d6578}
#spatial-lab .se-chip-path{display:flex;align-items:center;gap:4px;flex-wrap:wrap;margin-top:5px;font:9px Consolas,monospace;color:#486879}.se-chip-path span{background:#e2eaee;border:1px solid #becdd4;padding:2px 5px;border-radius:3px}.se-chip-path i{font-style:normal;color:#899aa2}
#spatial-lab .se-instruction-pane{display:flex;flex-direction:column;min-height:0;overflow:hidden;flex:1}
#spatial-lab .se-instr-pipeline{display:grid;grid-template-columns:repeat(5,1fr);gap:4px;margin:4px 0 6px}.se-instr-pipeline div{border:1px solid #c9d4d9;background:#edf2f4;padding:5px;border-radius:3px;font-size:9px;line-height:1.35;color:#526a77}.se-instr-pipeline b{display:block;color:#355261;font-size:9px}
#spatial-lab .se-instr-list{display:grid;grid-template-columns:repeat(auto-fit,minmax(170px,1fr));gap:5px;overflow:auto;min-height:0;flex:1}.se-instr{display:grid;grid-template-columns:39px 1fr;gap:5px;border:1px solid #cad5da;background:#f1f4f5;border-radius:3px;padding:5px;min-width:0}.se-instr.active{background:#f4dfc5;border-color:#b8793e}.se-instr.done{background:#e4eee8;border-color:#a8c2b2}.se-instr .slice{font:bold 9px Consolas,monospace;color:#526d7c}.se-instr code{display:block;font:10px Consolas,monospace;color:#274e62;white-space:normal;overflow-wrap:anywhere}.se-instr small{display:block;font-size:9px;line-height:1.35;color:#71848d}.se-instr .symbol{color:#916835}
#spatial-lab .se-instr-note{font-size:9px;line-height:1.4;color:#6d8089;border-top:1px solid #d3dde1;margin-top:5px;padding-top:5px}
`;document.head.append(s);};
const unitName=u=>({MEM:'MEM · 读写',MXM:'MXM · 矩阵乘',VXM:'VXM · 向量/归约',SXM:'SXM · 重排',C2C:'C2C · 片间',CPU:'CPU · 服务/分词',NETWORK:'网络交接',GPU:'GPU'}[u]||u||'控制');
const compress=a=>a.filter((v,i)=>v&&(!i||v!==a[i-1]));

export class SemanticView{
 constructor({element,layer,sprite,anchor,context,onChange}){Object.assign(this,{element,layer,sprite,anchor,context,onChange});this.program=null;this.current=-1;this.markers=[];this.teachMode='detail';injectStyles();this.element.addEventListener('click',e=>{const b=e.target.closest('[data-teach-mode]');if(!b)return;e.preventDefault();e.stopPropagation();this.teachMode=b.dataset.teachMode;this.renderCurrent();});}
 load(program,step){
  this.program=program;this.step=step;this.current=-1;this.markers=[];const ctx=this.context(),anchors=ctx.hardware.anchors;this.readouts=[];this.links=[];this.hardwareFlow=[];this.flowPacket=null;this.instructionPacket=null;this.activityLabel=null;
  const site=(key,point,label,position)=>{if(!point)return;const ring=new T.Mesh(new T.RingGeometry(.23,.31,32),new T.MeshBasicMaterial({color:0x527a90,transparent:true,opacity:.8,side:T.DoubleSide,depthTest:false}));ring.rotation.x=-Math.PI/2;ring.position.copy(point).add(new T.Vector3(0,.13,0));const pos=position||point.clone().add(new T.Vector3(0,1.3,0)),heading=this.sprite(label,'#294b5e',.5);heading.position.copy(pos);const leader=new T.Line(new T.BufferGeometry().setFromPoints([ring.position,pos.clone().add(new T.Vector3(0,-.2,0))]),new T.LineBasicMaterial({color:0x6c8b9a,transparent:true,opacity:.7,depthTest:false}));this.layer.add(ring,heading,leader);this.readouts.push({key,ring,heading,leader,position:pos,value:null});};
  if(program.type==='transfer'){
   const route=program.meta.route;route.forEach((id,i)=>site(i,anchors[id],id==='NETWORK'?'Spectrum-X':id==='SLOT'?'LPX 入口':id==='CX9'?'ConnectX-9':id,anchors[id]?.clone().add(new T.Vector3(i%2?-.3:.3,1.7,0))));
   for(let i=0;i<route.length-1;i++){const a=anchors[route[i]],b=anchors[route[i+1]];if(!a||!b)continue;const line=new T.Line(new T.BufferGeometry().setFromPoints([a.clone().add(new T.Vector3(0,.55,0)),b.clone().add(new T.Vector3(0,.55,0))]),new T.LineBasicMaterial({color:0x71919d,transparent:true,opacity:.5}));line.userData.semanticRoute=true;line.userData.hop=i;this.layer.add(line);this.links.push(line);}
  }else if(['gpu','chip'].includes(ctx.level)){
   site('memory',anchors.MEM,'存储资源 · 数据源/落点',ctx.level==='chip'?new T.Vector3(-4.2,2.8,0):anchors.MEM?.clone().add(new T.Vector3(-1.5,1.6,0)));
   const unit=program.type==='matrix'?'MXM':program.events.some(e=>e.unit==='SXM')?'SXM':'VXM';site('compute',anchors[unit],'执行资源 · 当前算子',ctx.level==='chip'?new T.Vector3(4.2,2.8,0):anchors[unit]?.clone().add(new T.Vector3(1.5,1.6,0)));
  }else if(anchors.HOST)site('cpu',anchors.HOST,'Host / 分词服务');
  this.compiledInstructions=compileTeachingInstructions(program,step,ctx);this.buildHardwareFlow(ctx);this.show(0);
 }
 buildHardwareFlow(ctx){
  const a=ctx.hardware.anchors,p=this.program;let keys=[];
  if(ctx.level==='external')keys=p.type==='transfer'?(p.meta.route||[]):compress(['USER','HOST','GPU','CX9','NETWORK','SLOT'].filter(k=>a[k]));
  else if(ctx.level==='gpu')keys=compress([this.step.from,a[this.step.from]?this.step.from:'MEM',this.step.to,a[this.step.to]?this.step.to:(p.type==='matrix'?'MXM':'VXM')].filter(k=>a[k]));
  else if(ctx.level==='rack')keys=['NETWORK','SLOT'].filter(k=>a[k]);
  else if(['tray','fabric'].includes(ctx.level))keys=['NIC','FABRIC','LPU'].filter(k=>a[k]);
  else if(ctx.level==='chip'){
   const units=compress(p.events.map(e=>e.unit).filter(u=>['MEM','MXM','VXM','SXM','C2C'].includes(u)&&a[u]));keys=compress(['MEM',...units,'MEM']).filter(k=>a[k]);
  }
  this.flowKeys=keys;for(let i=0;i<keys.length-1;i++){const x=a[keys[i]],y=a[keys[i+1]];if(!x||!y)continue;const line=new T.Line(new T.BufferGeometry().setFromPoints([x.clone().add(new T.Vector3(0,.35,0)),y.clone().add(new T.Vector3(0,.35,0))]),new T.LineBasicMaterial({color:0x89a3ad,transparent:true,opacity:.28,depthTest:false}));line.userData.semanticHardwareFlow=true;line.userData.from=keys[i];line.userData.to=keys[i+1];this.layer.add(line);this.hardwareFlow.push(line);}
  if(keys.length){this.flowPacket=new T.Mesh(new T.SphereGeometry(.13,14,10),new T.MeshBasicMaterial({color:0x3d86a1,depthTest:false}));this.flowPacket.userData.semanticAnimated=true;this.layer.add(this.flowPacket);}
  if(ctx.level==='chip'&&a.ICU){this.instructionPacket=new T.Mesh(new T.OctahedronGeometry(.14),new T.MeshBasicMaterial({color:0x9a6eb4,depthTest:false}));this.instructionPacket.userData.semanticAnimated=true;this.layer.add(this.instructionPacket);}
 }
 show(index){if(!this.program)return;index=Math.max(0,Math.min(this.program.events.length-1,index));if(this.current===index)return;this.current=index;this.renderCurrent();}
 renderCurrent(){if(!this.program||this.current<0)return;const p=this.program,e=p.events[this.current],ctx=this.context();this.layer.userData.semantic={type:p.type,event:this.current,count:p.events.length,valid:e.valid,revealed:e.revealed??null,received:e.received??null,total:e.total??null,stalled:!!e.stalled,instruction:e.instruction};this.syncHardware(e,ctx);this.element.innerHTML=this.flowHTML(ctx)+this.tabsHTML()+this.contentHTML(p,e,ctx);this.highlightFlow(ctx);this.element.dataset.semanticType=p.type;this.element.dataset.event=String(this.current);this.element.dataset.teachMode=this.teachMode;this.onChange?.(p,e);}
 tabsHTML(){return '<nav class="se-teach-tabs" aria-label="教学视图"><button data-teach-mode="sequence" aria-pressed="'+(this.teachMode==='sequence')+'">02 · 执行顺序</button><button data-teach-mode="detail" aria-pressed="'+(this.teachMode==='detail')+'">03 · 算子深入</button><button data-teach-mode="compare" aria-pressed="'+(this.teachMode==='compare')+'">04 · 数据流对比</button><button data-teach-mode="instruction" aria-pressed="'+(this.teachMode==='instruction')+'">05 · TSP 指令流</button></nav>';}
 contentHTML(p,e,ctx){if(this.teachMode==='sequence')return this.sequenceHTML(p,e);if(this.teachMode==='compare')return this.compareHTML(p,e,ctx);if(this.teachMode==='instruction')return this.instructionHTML(p,e,ctx);return this.detailHTML(p,e);}
 sequenceHTML(p,e){const items=p.events.map((x,i)=>'<div class="se-seq-step '+(i<e.index?'done':i===e.index?'current':'')+'"><b>'+(i+1)+'. '+esc(x.name)+'</b><small>'+esc(unitName(x.unit))+'</small><small>'+esc(x.instruction)+'</small></div>').join('');return '<section class="se-operator-pane" aria-label="执行顺序"><header class="se-header"><div><span class="se-kicker">02 · 执行顺序 · 不表示硬件 cycle</span><h3>数据和算子的因果顺序</h3></div><strong class="se-valid '+(e.valid?'ready':'')+'">步骤 '+(e.index+1)+' / '+p.events.length+'</strong></header><div class="se-sequence">'+items+'</div><div class="se-readwrite"><span><b>当前读</b> '+esc(e.read.join('，')||'无新增读取')+'</span><span><b>当前写</b> '+esc(e.write.join('，')||'保持原状态')+'</span></div>'+this.footerHTML(p,e)+'</section>';}
 detailHTML(p,e){let prompt='';if(p.type==='tokenize')prompt='<div class="se-prompt">'+p.meta.tokens.map((t,i)=>'<span class="'+(i===e.activeToken?'active':i<(e.revealed||0)?'done':'pending')+'">'+esc(t.text)+'</span>').join('')+'</div>';const readSet=new Set(e.focus.filter(f=>f.role==='read').map(f=>f.id+':'+f.r+':'+f.c)),writeSet=new Set(e.focus.filter(f=>f.role==='write').map(f=>f.id+':'+f.r+':'+f.c)),holdSet=new Set(e.focus.filter(f=>f.role==='hold').map(f=>f.id+':'+f.r+':'+f.c));const tables=e.view.filter(id=>e.objects[id]).map(id=>{const o=e.objects[id];return '<section class="se-object"><h4>'+esc(o.label)+'</h4><table aria-label="'+esc(o.label)+'"><tbody>'+o.rows.map((r,ri)=>'<tr>'+r.map((v,ci)=>{const key=id+':'+ri+':'+ci,cls=v===null?'empty':writeSet.has(key)?'written':readSet.has(key)?'read':holdSet.has(key)?'held':'';return '<td data-object="'+esc(id)+'" data-row="'+ri+'" data-col="'+ci+'" class="'+cls+'" title="'+esc(id+'['+ri+','+ci+'] = '+(v===null?'尚未写入':String(v)))+'">'+(v===null?'·':esc(number(v)))+'</td>';}).join('')+'</tr>').join('')+'</tbody></table>'+(o.hint?'<small>'+esc(o.hint)+'</small>':'')+'</section>';}).join('');return '<section class="se-operator-pane" aria-label="当前算子"><header class="se-header"><div><span class="se-kicker">03 · 算子深入 · 事件 '+(e.index+1)+' / '+p.events.length+'</span><h3>'+esc(e.name)+'</h3></div><strong class="se-valid '+(e.valid?'ready':e.stalled?'stall':'')+'">'+(e.valid?'结果有效':e.stalled?'背压 · 保持':'结果未提交')+'</strong></header>'+prompt+'<div class="se-equation"><code>'+esc(e.instruction)+'</code><span>'+esc(e.equation)+'</span></div><div class="se-tables">'+tables+'</div><div class="se-readwrite"><span><b>读</b> '+esc(e.read.join('，')||'无新增读取')+'</span><span><b>写</b> '+esc(e.write.join('，')||'保持原状态')+'</span></div>'+this.footerHTML(p,e)+'</section>';}
 compareHTML(p,e,ctx){let left,right,title='数据流对比';if(ctx.phase==='prefill'){left=['Prefill','一次处理完整输入上下文','全部模型层在 GPU 完成','建立上下文并得到首 Token'];right=['Decode','一次生成一个新 Token','复用历史状态','按层执行 GPU Attention ↔ LPX FFN'];}else if(['gateup','silu','down','router','dispatch','shared','combine'].includes(this.step.id)){left=['Attention','读取/更新历史状态','Q/K/V → QK → Softmax → PV','当前 AFD 推演中留在 GPU'];right=['FFN / MoE','主要处理当前层隐藏激活与权重','Gate/Up → 激活 → Down','当前 AFD 推演中送往 LPX'];}else if(ctx.shape.m.moe){left=['Dense FFN','每个 Token 走固定 FFN 权重','没有专家路由步骤','适合理解 27B Dense 路径'];right=['MoE','Router → Top-K → Expert → 合并','实际专家编号必须来自真实 Router','页面默认不编造专家 owner'];}else{left=['GPU','Prefill、Decode Attention、Cache/状态','这里表示公开资源类别','不推断具体 SM/HBM 地址'];right=['LPX','Decode 的 FFN / MoE 分工推演','MEM / MXM / VXM / SXM','不填造实机 cycle 或有效带宽'];}const card=a=>'<article class="se-compare-card"><h4>'+esc(a[0])+'</h4><p>'+a.slice(1).map(x=>esc(x)).join('<br>')+'</p></article>';return '<section class="se-operator-pane" aria-label="数据流对比"><header class="se-header"><div><span class="se-kicker">04 · 数据流对比</span><h3>'+title+'</h3></div><strong class="se-valid">只比较职责与数据方向</strong></header><div class="se-compare">'+card(left)+card(right)+'</div><div class="se-chip-path"><span>输入</span><i>→</i><span>'+esc(unitName(e.unit))+'</span><i>→</i><span>'+esc(e.valid?'结果已提交':'当前结果未提交')+'</span></div>'+this.footerHTML(p,e)+'</section>';}
 instructionHTML(p,e,ctx){const c=this.compiledInstructions||compileTeachingInstructions(p,this.step,ctx),active=new Set(activeInstructionIndexes(c,e.index));if(c.scope==='system'){const cards=c.instructions.length?c.instructions.map((x,i)=>'<div class="se-instr '+(i<=e.index?'done':'')+'"><span class="slice">'+esc(x.slice)+'</span><div><code>'+esc(x.opcode)+' <span class="symbol">'+esc(x.operand)+'</span></code><small>'+esc(x.why)+'</small></div></div>').join(''):'<div class="se-instr"><span class="slice">SYSTEM</span><div><code>等待进入 LPU die</code><small>系统互联不是 TSP 片上 ISA。</small></div></div>';return '<section class="se-operator-pane se-instruction-pane" aria-label="TSP 指令流"><header class="se-header"><div><span class="se-kicker">05 · 指令流</span><h3>'+esc(c.title)+'</h3></div><strong class="se-valid">SYSTEM ≠ TSP ISA</strong></header><div class="se-instr-list">'+cards+'</div><div class="se-instr-note">'+esc(c.note)+'</div>'+this.footerHTML(p,e)+'</section>';}
 const rows=c.instructions.map((x,i)=>'<div class="se-instr '+(active.has(i)?'active':x.event<e.index?'done':'')+'"><span class="slice">'+esc(x.slice)+'</span><div><code>'+esc(x.opcode)+(x.operand?' <span class="symbol">'+esc(x.operand)+'</span>':'')+'</code><small>'+esc(x.why)+'</small></div></div>').join('');return '<section class="se-operator-pane se-instruction-pane" aria-label="TSP 指令流"><header class="se-header"><div><span class="se-kicker">05 · 公开 TSP ISA · 教学静态程序</span><h3>指令向 slice 分发，数据沿 stream 横向流动</h3></div><strong class="se-valid">非 Groq 3 实机 trace</strong></header><div class="se-instr-pipeline"><div><b>1 · Compiler</b>静态决定资源与逻辑时间</div><div><b>2 · ICU Ifetch</b>取指 / decode / parcel</div><div><b>3 · Slice IQ</b>MEM / MXM / VXM / SXM 各自指令流</div><div><b>4 · 指令 ∩ 数据</b>纵向 instruction 与横向 stream 相遇</div><div><b>5 · Forward / Write</b>结果继续流向下游或写回 MEM</div></div><div class="se-instr-list">'+rows+'</div><div class="se-instr-note">'+esc(c.note)+'<br>公开 opcode：ICU Ifetch/Sync/Notify · MEM Read/Write/Gather/Scatter · MXM LW/IW/ABC/ACC · SXM Shift/Permute/Rotate/Transpose · C2C Deskew/Send/Receive。</div>'+this.footerHTML(p,e)+'</section>';}
 footerHTML(p,e){return '<footer class="se-footer"><div><button data-action="micro-prev" '+(e.index===0?'disabled':'')+'>上一事件</button><button class="sl-primary" data-action="micro-next">'+(e.index===p.events.length-1?'进入下一算子':'下一事件')+' →</button></div><small>'+esc(p.basis)+'</small></footer>';}
 flowHTML(ctx){return '<section class="se-flow-pane" aria-label="完整数据流程"><div class="se-flow-heading se-drag-handle" title="拖动移动窗口；双击恢复默认位置"><b>01 · 完整数据 flow</b><span class="se-drag-tip">拖动移动 · 双击复位</span><nav class="se-quick"><button data-action="focus-token">分词</button><button data-action="focus-ffn">FFN</button><button data-action="focus-attn">Attention</button><button data-action="focus-transfer">传输</button></nav><div class="se-window-zoom"><span>窗口</span><button data-action="float-zoom-out" aria-label="缩小悬浮窗口">−</button><button data-action="float-zoom-reset" title="恢复默认大小和位置">'+Math.round(ctx.zoom*100)+'%</button><button data-action="float-zoom-in" aria-label="放大悬浮窗口">+</button></div></div><div class="se-flow-row"><b>Prefill</b>'+DATA_FLOW_DIAGRAMS.prefill+'</div><div class="se-flow-row"><b>Decode</b>'+DATA_FLOW_DIAGRAMS.decode+'</div><div class="se-flow-caption">'+(ctx.phase==='prefill'?'Prefill · GPU 执行全部模型层':'Decode · GPU Attention / LPX FFN 分工推演')+' · L'+ctx.layer+' / '+ctx.shape.m.layers+' · T='+ctx.shape.T+' · S='+ctx.shape.S+'<span>自动播放会随步骤进入 GPU / 网络 / LPX Tray / LPU die</span></div></section>';}
 highlightFlow(ctx){const id=this.step.id;let active;if(ctx.phase==='prefill')active=id==='prompt'?'P0':id==='tokenize'?'P1':['embedding','schedule','expand'].includes(id)?'P2':['finalnorm','lmhead'].includes(id)?'P4':['sample','result-handoff'].includes(id)?'P5':'P3';else active=id==='schedule'?'D0':['embedding','expand'].includes(id)?'D1':['gpu-egress','afd','tray'].includes(id)?'D3':['gateup','silu','down','router','dispatch','shared','combine'].includes(id)?'D4':['return','gpu-return'].includes(id)?'D5':id==='ffnwrite'?'D6':['finalnorm','lmhead','result-handoff','sample'].includes(id)?'D7':'D2';for(const node of this.element.querySelectorAll('.se-flow-pane g.node')){const key=node.id.match(/(?:flowchart-)?([PD][0-7])-/)?.[1];if(!key)continue;node.dataset.flowNode=key;node.setAttribute('role','button');node.setAttribute('tabindex','0');node.setAttribute('aria-label','展开 '+node.textContent.trim());node.classList.toggle('flow-active',key===active);node.classList.toggle('flow-complete',ctx.phase==='decode'&&key[0]==='P');}this.element.dataset.activeFlow=active;}
 syncHardware(e,ctx){
  const p=this.program,a=ctx.hardware.anchors;
  for(const r of this.readouts){let words='';if(p.type==='transfer'){const n=r.key,hop=e.hop||0;words=n===0?'TX 8 B · 保持':n<=hop?'已接收 8 / 8 B':n===hop+1?'RX '+(e.received||0)+' / 8 B':'等待上游';if(n===hop+1&&e.stalled)words+=' · ready=0';}else if(r.key==='cpu')words=p.type==='tokenize'?'已追加 '+(e.revealed||0)+' / 6 个 Token':e.valid?'提交完成':'结果未提交';else if(r.key==='memory'){const reg=e.objects.reg?.rows[0];words=reg?'a='+number(reg[0])+'  b='+number(reg[1]):e.valid?'输出已提交':e.write.length?'写 '+e.write.join(', '):'输入保持';}else{const reg=e.objects.reg?.rows[0],stat=e.objects.stat?.rows[0];words=reg?'ACC = '+number(reg[3]):stat?stat.map(number).join(' / '):e.valid?'结果有效':'本地状态尚未提交';}if(r.value){r.value.material.map.dispose();r.value.material.dispose();this.layer.remove(r.value);}r.value=this.sprite(words,e.stalled?'#9b6c2d':e.valid?'#32764d':'#355e75',.46);r.value.position.copy(r.position).add(new T.Vector3(0,-.58,0));this.layer.add(r.value);for(const o of [r.ring,r.heading,r.leader,r.value])o.visible=ctx.follow;}
  for(const line of this.links){line.visible=ctx.follow;line.material.color.set(line.userData.hop===(e.hop||0)?e.stalled?0xba873a:e.accepted?0x438662:0x46799b:0xa4b3b9);line.material.opacity=line.userData.hop===(e.hop||0)?1:.35;}
  const activeUnit=['MEM','MXM','VXM','SXM','C2C'].includes(e.unit)?e.unit:(e.write?.length?'MEM':null);for(const line of this.hardwareFlow){line.visible=ctx.follow;const hit=line.userData.to===activeUnit||line.userData.from===activeUnit;line.material.color.set(hit?e.stalled?0xba873a:e.valid?0x438662:0x3b7e9b:0x9eb0b7);line.material.opacity=hit?.95:.22;}
  if(this.flowPacket){let pos=null;if(p.type==='transfer'&&p.meta.route?.length){const hop=Math.min(p.meta.route.length-2,e.hop||0),x=a[p.meta.route[hop]],y=a[p.meta.route[hop+1]];if(x&&y){const q=e.total?Math.max(0,Math.min(1,(e.received||0)/e.total)):0;pos=x.clone().lerp(y,e.stalled?Math.max(.15,q*.7):Math.max(.12,q));}}if(!pos&&activeUnit&&a[activeUnit])pos=a[activeUnit].clone();if(!pos&&this.flowKeys?.length)pos=a[this.flowKeys[Math.min(this.flowKeys.length-1,Math.floor(e.index/Math.max(1,p.events.length-1)*(this.flowKeys.length-1)))]]?.clone();if(pos)this.flowPacket.position.copy(pos).add(new T.Vector3(0,.58,0));this.flowPacket.visible=!!pos&&ctx.follow;this.flowPacket.material.color.set(e.stalled?0xb9863c:e.valid?0x3f925c:0x3d86a1);}
  if(this.instructionPacket){const comp=this.compiledInstructions,inds=activeInstructionIndexes(comp,e.index),ins=comp.instructions?.[inds.at(-1)],target=ins&&a[ins.slice];if(target&&a.ICU){this.instructionPacket.position.copy(a.ICU.clone().lerp(target,.78)).add(new T.Vector3(0,.72,0));this.instructionPacket.visible=ctx.follow;}else this.instructionPacket.visible=false;}
  if(this.activityLabel){this.activityLabel.material.map.dispose();this.activityLabel.material.dispose();this.layer.remove(this.activityLabel);this.activityLabel=null;}const activity=activeUnit&&a[activeUnit];if(activity){const comp=this.compiledInstructions,inds=activeInstructionIndexes(comp,e.index),ins=comp.instructions?.[inds.at(-1)],words=(ins?ins.slice+' '+ins.opcode:unitName(activeUnit))+' · '+(e.read?.length?'READ ':e.write?.length?'WRITE ':'EXEC ');this.activityLabel=this.sprite(words,'#6e4d83',.42);this.activityLabel.position.copy(activity).add(new T.Vector3(0,1.05,0));this.activityLabel.visible=ctx.follow;this.layer.add(this.activityLabel);}
 }
 get event(){return this.program?.events[this.current];}
 sizeLabels(camera,height){for(const r of this.readouts||[])for(const sp of [r.heading,r.value]){if(!sp)continue;const aspect=sp.scale.x/sp.scale.y,size=2*sp.position.distanceTo(camera.position)*Math.tan(T.MathUtils.degToRad(camera.fov)/2)*20/height;sp.scale.set(size*aspect,size,1);}if(this.activityLabel){const sp=this.activityLabel,aspect=sp.scale.x/sp.scale.y,size=2*sp.position.distanceTo(camera.position)*Math.tan(T.MathUtils.degToRad(camera.fov)/2)*18/height;sp.scale.set(size*aspect,size,1);}}
}
