/* UTF-8 · 软件双流按可用高度分页，与硬件共用播放位置。 */
(function(root){
 'use strict';const ns='http://www.w3.org/2000/svg',slots=12;
 function instruction(phase){if(phase.instruction)return phase.instruction;if(phase.packets.some(p=>p.wire))return'C2C · Send / Receive';if(phase.focus.some(k=>k.endsWith('_ICU')))return'ICU · 指令与同步';if(phase.focus.some(k=>k.endsWith('_MAC')||/^(ME|MW)\d/.test(k)))return'MXM · 矩阵执行';if(phase.focus.some(k=>/_(ALU|SUM)$/.test(k)||k.startsWith('VX')))return'VXM · 向量执行';if(phase.focus.some(k=>/_(W|INPUT|KV|KVNEW|RX|TX)$/.test(k)))return'MEM / I/O · 读写';return'软件编排 / 等待';}
 const data=phase=>phase.dataLabel||[...new Set(phase.packets.filter(p=>p.tone!=='control').map(p=>p.label))].join(' / ')||'数据保持，等待执行';
 function pageRows(height,width,asset){if(!height||!width)return 4;const scale=width/asset.viewBox.width;for(let n=4;n>=2;n--){const b=asset.nodes['D'+(n-1)];if((b.y+b.height-asset.viewBox.y+8)*scale<=height-43)return n;}return 2;}
 function create({container,assets,onSelect,compact=false}){
  container.innerHTML='<div class="flow-diagram">'+assets.software7.svg+'</div><div class="flow-pager"><button type="button" data-flow-page="prev" aria-label="前一组动作">← 前组</button><span class="flow-page-count"></span><button type="button" data-flow-page="next" aria-label="后一组动作">后组 →</button></div>';
  const svg=container.querySelector('svg'),nodes={},prev=container.querySelector('[data-flow-page="prev"]'),next=container.querySelector('[data-flow-page="next"]'),count=container.querySelector('.flow-page-count');let currentPhases=[],currentIndex=0,isSettled=false,rows=4,start=0;
  svg.classList.add('software-flow-svg');svg.setAttribute('aria-label','当前软件操作的指令流与数据流');svg.setAttribute('preserveAspectRatio','xMidYMin meet');
  for(const el of svg.querySelectorAll('[data-hw-id]')){const key=el.dataset.hwId;nodes[key]=el;el.querySelector('.label')?.setAttribute('transform','translate(0,0)');const t=el.querySelector('text');if(t){t.setAttribute('x','0');t.setAttribute('y','0');t.setAttribute('text-anchor','middle');}if(/^[ID]\d+$/.test(key)){el.setAttribute('role','button');el.dataset.interactive='true';const pick=()=>{if(el.dataset.available==='true')onSelect(Number(el.dataset.flowIndex));};el.addEventListener('click',pick);el.addEventListener('keydown',e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();e.stopPropagation();pick();}});}}
  function label(key,value,header=false){const n=nodes[key],t=n?.querySelector('text');if(!t)return;const b=assets.software7.nodes[key],font=header?20:22,limit=(b.width-17)/font;const lines=[];let line='',width=0;for(const ch of String(value)){const w=/[\u0000-\u007f]/.test(ch)?.53:1;if(width+w>limit){lines.push(line);line='';width=0;}line+=ch;width+=w;}if(line)lines.push(line);const out=lines.slice(0,2);if(lines.length>2)out[1]=out[1].slice(0,-1)+'…';t.replaceChildren();t.style.fontSize=font+'px';out.forEach((s,i)=>{const span=document.createElementNS(ns,'tspan');span.setAttribute('x','0');span.setAttribute('y',String((i-(out.length-1)/2)*26+6));span.textContent=s;t.appendChild(span);});n.setAttribute('aria-label',value);let title=n.querySelector('title');if(!title){title=document.createElementNS(ns,'title');n.appendChild(title);}title.textContent=value;}
  function paintCompact(){
   container.classList.add('software-flow-compact');const phase=currentPhases[currentIndex];label('IH','当前指令',true);label('DH','当前数据',true);
   for(const [id,n]of Object.entries(nodes)){const visible=['IH','DH','I0','D0'].includes(id);n.style.display=visible?'':'none';if(!visible){n.setAttribute('tabindex','-1');continue;}const header=id.endsWith('H'),right=id[0]==='D',w=162,h=header?22:58,x=right?253:81,y=header?12:57;n.setAttribute('transform',`translate(${x},${y})`);const rect=n.querySelector('rect');rect.setAttribute('x',-w/2);rect.setAttribute('y',-h/2);rect.setAttribute('width',w);rect.setAttribute('height',h);if(!header){n.dataset.available='true';n.dataset.flowIndex=String(currentIndex);n.classList.toggle('flow-done',isSettled);n.classList.add('flow-current');n.setAttribute('tabindex','0');label(id,right?data(phase):instruction(phase));}}
   for(const edge of svg.querySelectorAll('path[data-edge]'))edge.style.display='none';svg.setAttribute('viewBox','-2 -2 338 94');prev.textContent='← 动作';next.textContent='动作 →';prev.disabled=currentIndex===0;next.disabled=currentIndex===currentPhases.length-1;count.textContent=(currentIndex+1)+' / '+currentPhases.length+' 动作';
  }
  function paint(){if(!currentPhases.length)return;if(compact){paintCompact();return;}rows=pageRows(container.clientHeight,container.clientWidth,assets.software7);start=Math.floor(currentIndex/rows)*rows;const size=Math.min(rows,currentPhases.length-start);
   label('IH','指令流',true);label('DH','数据流',true);
   for(let i=0;i<slots;i++){const index=start+i,p=i<size?currentPhases[index]:null;for(const kind of ['I','D']){const n=nodes[kind+i];if(!n)continue;n.dataset.available=String(Boolean(p));n.dataset.flowIndex=String(index);n.style.display=p?'':'none';n.setAttribute('tabindex',p?'0':'-1');n.classList.toggle('flow-current',Boolean(p&&index===currentIndex));n.classList.toggle('flow-done',Boolean(p&&(index<currentIndex||index===currentIndex&&isSettled)));n.setAttribute('aria-pressed',String(Boolean(p&&index===currentIndex)));if(p)label(kind+i,(index+1)+' · '+(kind==='I'?instruction(p):data(p)));}}
   const last=assets.software7.nodes['D'+(size-1)],box=assets.software7.viewBox;svg.setAttribute('viewBox',[box.x,box.y,box.width,last.y+last.height-box.y+8].join(' '));for(const edge of svg.querySelectorAll('path[data-edge]')){const m=edge.id.match(/-[ID](\d+)-[ID](\d+)$/);if(m)edge.style.display=Number(m[2])<size?'':'none';}prev.disabled=start===0;next.disabled=start+size>=currentPhases.length;count.textContent=(start+1)+'–'+(start+size)+' / '+currentPhases.length+' 动作';
  }
  prev.addEventListener('click',()=>onSelect(Math.max(0,compact?currentIndex-1:start-rows)));next.addEventListener('click',()=>onSelect(Math.min(currentPhases.length-1,compact?currentIndex+1:start+rows)));
  if(root.ResizeObserver)new root.ResizeObserver(paint).observe(container);
  return{render:(phases,current,settled=false)=>{currentPhases=phases;currentIndex=current;isSettled=settled;paint();}};
 }
 const api={create,instruction,data,pageRows,slots};root.GROQ_SOFTWARE_FLOW=api;if(typeof module!=='undefined')module.exports=api;
})(typeof window==='undefined'?globalThis:window);
