/* UTF-8 · 同页详情与窄屏切换，主画面不随内容长度滚动。 */
(function(){
 'use strict';const $=id=>document.getElementById(id),drawer=$('detail-drawer'),names={explain:'动作与硬件说明',values:'输入、计算与输出数值',formulas:'逐项计算与估算口径',parameters:'模型、硬件与链路参数',deploy:'软件部署分工',steps:'选择操作步骤'};
 function select(section){$('detail-title').textContent=names[section]||names.explain;document.querySelectorAll('[data-detail-workspace]').forEach(el=>el.hidden=el.dataset.detailWorkspace!==document.body.dataset.workspace);document.querySelectorAll('[data-detail-section]').forEach(el=>el.hidden=el.dataset.detailSection!==section);document.querySelectorAll('[data-detail-tab]').forEach(el=>el.setAttribute('aria-pressed',String(el.dataset.detailTab===section)));document.querySelectorAll('[data-mirror]').forEach(el=>el.textContent=$(el.dataset.mirror).textContent);if(section==='deploy')drawer.querySelector('.software-guide').open=true;drawer.querySelector('.drawer-content').scrollTop=0;}
 function open(section){if(document.body.dataset.workspace==='cycle'){window.GROQ_CYCLE_APP.open(section);return;}window.GROQ_LAB.stop();window.dispatchEvent(new Event('groq:pause'));select(section);if(!drawer.open)drawer.showModal();$('detail-close').focus();}
 document.addEventListener('click',e=>{const button=e.target.closest('[data-panel]');if(button)open(button.dataset.panel);const tab=e.target.closest('[data-detail-tab]');if(tab)select(tab.dataset.detailTab);const mobile=e.target.closest('[data-mobile-tab]');if(mobile){document.body.dataset.mobilePane=mobile.dataset.mobileTab;document.querySelectorAll('[data-mobile-tab]').forEach(el=>el.setAttribute('aria-pressed',String(el===mobile)));window.dispatchEvent(new Event('resize'));}if(drawer.open&&e.target.closest('[data-request-step],[data-cluster-step],[data-cluster-phase],[data-operation],[data-phase]'))drawer.close();});
 $('detail-close').addEventListener('click',()=>drawer.close());drawer.addEventListener('click',e=>{if(e.target===drawer)drawer.close();});
 $('workspace-fullscreen').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch{$('workspace-fullscreen').textContent='请使用窗口全屏';}});document.addEventListener('fullscreenchange',()=>$('workspace-fullscreen').textContent=document.fullscreenElement?'退出全屏':'全屏');
 window.GROQ_WORKSPACE_UI={open,select};
})();
