block-beta
 columns 24
RACK["四芯片教学板 · 固定物理连接，软件决定模型分工"]
HOST["主机 CPU / 运行时"]
REQUESTA["请求 A · 输入 ID"]
REQUESTB["请求 B · 独立上下文"]
TOKEN["采样后的 Token ID"]
USER["用户接收缓冲"]
C0_DIE["TSP 0"]
C0_TITLE["TSP 0 · 硬件功能区域"]
C0_MW0["MXM"]
C0_MW0SL0[" "]
C0_MW0SL1[" "]
C0_MW0SL2[" "]
C0_MW0SL3[" "]
C0_MW1["MXM"]
C0_MW1SL0[" "]
C0_MW1SL1[" "]
C0_MW1SL2[" "]
C0_MW1SL3[" "]
C0_SW["SXM"]
C0_SWSL0[" "]
C0_SWSL1[" "]
C0_SWSL2[" "]
C0_SWSL3[" "]
C0_MEMW["MEM"]
C0_MEMWSL0[" "]
C0_MEMWSL1[" "]
C0_MEMWSL2[" "]
C0_MEMWSL3[" "]
C0_VX["VXM"]
C0_VXSL0[" "]
C0_VXSL1[" "]
C0_VXSL2[" "]
C0_VXSL3[" "]
C0_MEME["MEM"]
C0_MEMESL0[" "]
C0_MEMESL1[" "]
C0_MEMESL2[" "]
C0_MEMESL3[" "]
C0_SE["SXM"]
C0_SESL0[" "]
C0_SESL1[" "]
C0_SESL2[" "]
C0_SESL3[" "]
C0_ME0["MXM"]
C0_ME0SL0[" "]
C0_ME0SL1[" "]
C0_ME0SL2[" "]
C0_ME0SL3[" "]
C0_ME1["MXM"]
C0_ME1SL0[" "]
C0_ME1SL1[" "]
C0_ME1SL2[" "]
C0_ME1SL3[" "]
C0_W["权重数据"]
C0_PROG["指令块"]
C0_INPUT["激活数据"]
C0_KV["KV 历史"]
C0_KVNEW["KV 写入"]
C0_ALU["逐元素 ALU"]
C0_SUM["归约 ALU"]
C0_MAC["MAC"]
C0_SRF["横向流寄存器 SRF"]
C0_ICU["ICU 组 · 每个功能切片有自己的指令控制"]
C0_TX["发送缓冲"]
C0_SER_TX["发送 SerDes"]
C0_SER_RX["接收 / 对齐"]
C0_RX["接收缓冲"]
C0_FIFO0["0"]
C0_FIFO1["1"]
C0_FIFO2["2"]
C0_FIFO3["3"]
C0_PCIE["PCIe / DMA"]
C0_PORTN["C2C 北口"]
C0_PORTS["C2C 南口"]
C0_PORTW["C2C"]
C0_PORTE["C2C"]
C1_DIE["TSP 1"]
C1_TITLE["TSP 1 · 硬件功能区域"]
C1_MW0["MXM"]
C1_MW0SL0[" "]
C1_MW0SL1[" "]
C1_MW0SL2[" "]
C1_MW0SL3[" "]
C1_MW1["MXM"]
C1_MW1SL0[" "]
C1_MW1SL1[" "]
C1_MW1SL2[" "]
C1_MW1SL3[" "]
C1_SW["SXM"]
C1_SWSL0[" "]
C1_SWSL1[" "]
C1_SWSL2[" "]
C1_SWSL3[" "]
C1_MEMW["MEM"]
C1_MEMWSL0[" "]
C1_MEMWSL1[" "]
C1_MEMWSL2[" "]
C1_MEMWSL3[" "]
C1_VX["VXM"]
C1_VXSL0[" "]
C1_VXSL1[" "]
C1_VXSL2[" "]
C1_VXSL3[" "]
C1_MEME["MEM"]
C1_MEMESL0[" "]
C1_MEMESL1[" "]
C1_MEMESL2[" "]
C1_MEMESL3[" "]
C1_SE["SXM"]
C1_SESL0[" "]
C1_SESL1[" "]
C1_SESL2[" "]
C1_SESL3[" "]
C1_ME0["MXM"]
C1_ME0SL0[" "]
C1_ME0SL1[" "]
C1_ME0SL2[" "]
C1_ME0SL3[" "]
C1_ME1["MXM"]
C1_ME1SL0[" "]
C1_ME1SL1[" "]
C1_ME1SL2[" "]
C1_ME1SL3[" "]
C1_W["权重数据"]
C1_PROG["指令块"]
C1_INPUT["激活数据"]
C1_KV["KV 历史"]
C1_KVNEW["KV 写入"]
C1_ALU["逐元素 ALU"]
C1_SUM["归约 ALU"]
C1_MAC["MAC"]
C1_SRF["横向流寄存器 SRF"]
C1_ICU["ICU 组 · 每个功能切片有自己的指令控制"]
C1_TX["发送缓冲"]
C1_SER_TX["发送 SerDes"]
C1_SER_RX["接收 / 对齐"]
C1_RX["接收缓冲"]
C1_FIFO0["0"]
C1_FIFO1["1"]
C1_FIFO2["2"]
C1_FIFO3["3"]
C1_PCIE["PCIe / DMA"]
C1_PORTN["C2C 北口"]
C1_PORTS["C2C 南口"]
C1_PORTW["C2C"]
C1_PORTE["C2C"]
C2_DIE["TSP 2"]
C2_TITLE["TSP 2 · 硬件功能区域"]
C2_MW0["MXM"]
C2_MW0SL0[" "]
C2_MW0SL1[" "]
C2_MW0SL2[" "]
C2_MW0SL3[" "]
C2_MW1["MXM"]
C2_MW1SL0[" "]
C2_MW1SL1[" "]
C2_MW1SL2[" "]
C2_MW1SL3[" "]
C2_SW["SXM"]
C2_SWSL0[" "]
C2_SWSL1[" "]
C2_SWSL2[" "]
C2_SWSL3[" "]
C2_MEMW["MEM"]
C2_MEMWSL0[" "]
C2_MEMWSL1[" "]
C2_MEMWSL2[" "]
C2_MEMWSL3[" "]
C2_VX["VXM"]
C2_VXSL0[" "]
C2_VXSL1[" "]
C2_VXSL2[" "]
C2_VXSL3[" "]
C2_MEME["MEM"]
C2_MEMESL0[" "]
C2_MEMESL1[" "]
C2_MEMESL2[" "]
C2_MEMESL3[" "]
C2_SE["SXM"]
C2_SESL0[" "]
C2_SESL1[" "]
C2_SESL2[" "]
C2_SESL3[" "]
C2_ME0["MXM"]
C2_ME0SL0[" "]
C2_ME0SL1[" "]
C2_ME0SL2[" "]
C2_ME0SL3[" "]
C2_ME1["MXM"]
C2_ME1SL0[" "]
C2_ME1SL1[" "]
C2_ME1SL2[" "]
C2_ME1SL3[" "]
C2_W["权重数据"]
C2_PROG["指令块"]
C2_INPUT["激活数据"]
C2_KV["KV 历史"]
C2_KVNEW["KV 写入"]
C2_ALU["逐元素 ALU"]
C2_SUM["归约 ALU"]
C2_MAC["MAC"]
C2_SRF["横向流寄存器 SRF"]
C2_ICU["ICU 组 · 每个功能切片有自己的指令控制"]
C2_TX["发送缓冲"]
C2_SER_TX["发送 SerDes"]
C2_SER_RX["接收 / 对齐"]
C2_RX["接收缓冲"]
C2_FIFO0["0"]
C2_FIFO1["1"]
C2_FIFO2["2"]
C2_FIFO3["3"]
C2_PCIE["PCIe / DMA"]
C2_PORTN["C2C 北口"]
C2_PORTS["C2C 南口"]
C2_PORTW["C2C"]
C2_PORTE["C2C"]
C3_DIE["TSP 3"]
C3_TITLE["TSP 3 · 硬件功能区域"]
C3_MW0["MXM"]
C3_MW0SL0[" "]
C3_MW0SL1[" "]
C3_MW0SL2[" "]
C3_MW0SL3[" "]
C3_MW1["MXM"]
C3_MW1SL0[" "]
C3_MW1SL1[" "]
C3_MW1SL2[" "]
C3_MW1SL3[" "]
C3_SW["SXM"]
C3_SWSL0[" "]
C3_SWSL1[" "]
C3_SWSL2[" "]
C3_SWSL3[" "]
C3_MEMW["MEM"]
C3_MEMWSL0[" "]
C3_MEMWSL1[" "]
C3_MEMWSL2[" "]
C3_MEMWSL3[" "]
C3_VX["VXM"]
C3_VXSL0[" "]
C3_VXSL1[" "]
C3_VXSL2[" "]
C3_VXSL3[" "]
C3_MEME["MEM"]
C3_MEMESL0[" "]
C3_MEMESL1[" "]
C3_MEMESL2[" "]
C3_MEMESL3[" "]
C3_SE["SXM"]
C3_SESL0[" "]
C3_SESL1[" "]
C3_SESL2[" "]
C3_SESL3[" "]
C3_ME0["MXM"]
C3_ME0SL0[" "]
C3_ME0SL1[" "]
C3_ME0SL2[" "]
C3_ME0SL3[" "]
C3_ME1["MXM"]
C3_ME1SL0[" "]
C3_ME1SL1[" "]
C3_ME1SL2[" "]
C3_ME1SL3[" "]
C3_W["权重数据"]
C3_PROG["指令块"]
C3_INPUT["激活数据"]
C3_KV["KV 历史"]
C3_KVNEW["KV 写入"]
C3_ALU["逐元素 ALU"]
C3_SUM["归约 ALU"]
C3_MAC["MAC"]
C3_SRF["横向流寄存器 SRF"]
C3_ICU["ICU 组 · 每个功能切片有自己的指令控制"]
C3_TX["发送缓冲"]
C3_SER_TX["发送 SerDes"]
C3_SER_RX["接收 / 对齐"]
C3_RX["接收缓冲"]
C3_FIFO0["0"]
C3_FIFO1["1"]
C3_FIFO2["2"]
C3_FIFO3["3"]
C3_PCIE["PCIe / DMA"]
C3_PORTN["C2C 北口"]
C3_PORTS["C2C 南口"]
C3_PORTW["C2C"]
C3_PORTE["C2C"]
TRACE336A[" "]
TRACE336B[" "]
TRACE1090A[" "]
TRACE1090B[" "]
WIRE02["0 ↔ 2 · C2C"]
WIRE13["1 ↔ 3 · C2C"]
WIRE01["0 ↔ 1 · C2C"]
WIRE23["2 ↔ 3 · C2C"]
FOOT["图中仅使用四条逻辑邻接；每条连接的物理 ×4 链路数可调。不是所有 16 个接口同时提供给单条传输。"]
class C0_MEMW,C0_MEMWSL0,C0_MEMWSL1,C0_MEMWSL2,C0_MEMWSL3,C0_MEME,C0_MEMESL0,C0_MEMESL1,C0_MEMESL2,C0_MEMESL3,C0_W,C0_KV,C0_KVNEW,C1_MEMW,C1_MEMWSL0,C1_MEMWSL1,C1_MEMWSL2,C1_MEMWSL3,C1_MEME,C1_MEMESL0,C1_MEMESL1,C1_MEMESL2,C1_MEMESL3,C1_W,C1_KV,C1_KVNEW,C2_MEMW,C2_MEMWSL0,C2_MEMWSL1,C2_MEMWSL2,C2_MEMWSL3,C2_MEME,C2_MEMESL0,C2_MEMESL1,C2_MEMESL2,C2_MEMESL3,C2_W,C2_KV,C2_KVNEW,C3_MEMW,C3_MEMWSL0,C3_MEMWSL1,C3_MEMWSL2,C3_MEMWSL3,C3_MEME,C3_MEMESL0,C3_MEMESL1,C3_MEMESL2,C3_MEMESL3,C3_W,C3_KV,C3_KVNEW mem
class C0_MW0,C0_MW0SL0,C0_MW0SL1,C0_MW0SL2,C0_MW0SL3,C0_MW1,C0_MW1SL0,C0_MW1SL1,C0_MW1SL2,C0_MW1SL3,C0_ME0,C0_ME0SL0,C0_ME0SL1,C0_ME0SL2,C0_ME0SL3,C0_ME1,C0_ME1SL0,C0_ME1SL1,C0_ME1SL2,C0_ME1SL3,C0_MAC,C1_MW0,C1_MW0SL0,C1_MW0SL1,C1_MW0SL2,C1_MW0SL3,C1_MW1,C1_MW1SL0,C1_MW1SL1,C1_MW1SL2,C1_MW1SL3,C1_ME0,C1_ME0SL0,C1_ME0SL1,C1_ME0SL2,C1_ME0SL3,C1_ME1,C1_ME1SL0,C1_ME1SL1,C1_ME1SL2,C1_ME1SL3,C1_MAC,C2_MW0,C2_MW0SL0,C2_MW0SL1,C2_MW0SL2,C2_MW0SL3,C2_MW1,C2_MW1SL0,C2_MW1SL1,C2_MW1SL2,C2_MW1SL3,C2_ME0,C2_ME0SL0,C2_ME0SL1,C2_ME0SL2,C2_ME0SL3,C2_ME1,C2_ME1SL0,C2_ME1SL1,C2_ME1SL2,C2_ME1SL3,C2_MAC,C3_MW0,C3_MW0SL0,C3_MW0SL1,C3_MW0SL2,C3_MW0SL3,C3_MW1,C3_MW1SL0,C3_MW1SL1,C3_MW1SL2,C3_MW1SL3,C3_ME0,C3_ME0SL0,C3_ME0SL1,C3_ME0SL2,C3_ME0SL3,C3_ME1,C3_ME1SL0,C3_ME1SL1,C3_ME1SL2,C3_ME1SL3,C3_MAC mxm
class C0_VX,C0_VXSL0,C0_VXSL1,C0_VXSL2,C0_VXSL3,C0_ALU,C0_SUM,C1_VX,C1_VXSL0,C1_VXSL1,C1_VXSL2,C1_VXSL3,C1_ALU,C1_SUM,C2_VX,C2_VXSL0,C2_VXSL1,C2_VXSL2,C2_VXSL3,C2_ALU,C2_SUM,C3_VX,C3_VXSL0,C3_VXSL1,C3_VXSL2,C3_VXSL3,C3_ALU,C3_SUM vxm
class C0_SW,C0_SWSL0,C0_SWSL1,C0_SWSL2,C0_SWSL3,C0_SE,C0_SESL0,C0_SESL1,C0_SESL2,C0_SESL3,C1_SW,C1_SWSL0,C1_SWSL1,C1_SWSL2,C1_SWSL3,C1_SE,C1_SESL0,C1_SESL1,C1_SESL2,C1_SESL3,C2_SW,C2_SWSL0,C2_SWSL1,C2_SWSL2,C2_SWSL3,C2_SE,C2_SESL0,C2_SESL1,C2_SESL2,C2_SESL3,C3_SW,C3_SWSL0,C3_SWSL1,C3_SWSL2,C3_SWSL3,C3_SE,C3_SESL0,C3_SESL1,C3_SESL2,C3_SESL3 sxm
class C0_PROG,C0_ICU,C1_PROG,C1_ICU,C2_PROG,C2_ICU,C3_PROG,C3_ICU icu
class C0_TX,C0_SER_TX,C0_SER_RX,C0_RX,C0_PCIE,C0_PORTN,C0_PORTS,C0_PORTW,C0_PORTE,C1_TX,C1_SER_TX,C1_SER_RX,C1_RX,C1_PCIE,C1_PORTN,C1_PORTS,C1_PORTW,C1_PORTE,C2_TX,C2_SER_TX,C2_SER_RX,C2_RX,C2_PCIE,C2_PORTN,C2_PORTS,C2_PORTW,C2_PORTE,C3_TX,C3_SER_TX,C3_SER_RX,C3_RX,C3_PCIE,C3_PORTN,C3_PORTS,C3_PORTW,C3_PORTE port
class RACK,C0_DIE,C1_DIE,C2_DIE,C3_DIE frame
class HOST,REQUESTA,REQUESTB,TOKEN,USER,C0_TITLE,C1_TITLE,C2_TITLE,C3_TITLE,FOOT host
class C0_INPUT,C0_SRF,C0_FIFO0,C0_FIFO1,C0_FIFO2,C0_FIFO3,C1_INPUT,C1_SRF,C1_FIFO0,C1_FIFO1,C1_FIFO2,C1_FIFO3,C2_INPUT,C2_SRF,C2_FIFO0,C2_FIFO1,C2_FIFO2,C2_FIFO3,C3_INPUT,C3_SRF,C3_FIFO0,C3_FIFO1,C3_FIFO2,C3_FIFO3 stream
class TRACE336A,TRACE336B,TRACE1090A,TRACE1090B,WIRE02,WIRE13,WIRE01,WIRE23 wire

classDef mem fill:#dceef8,stroke:#7896ac,color:#203c50
classDef mxm fill:#fff0d1,stroke:#7896ac,color:#203c50
classDef vxm fill:#eee5fa,stroke:#7896ac,color:#203c50
classDef sxm fill:#e0f2e9,stroke:#7896ac,color:#203c50
classDef icu fill:#e5eafb,stroke:#7896ac,color:#203c50
classDef port fill:#eaf0f6,stroke:#7896ac,color:#203c50
classDef frame fill:#ffffff,stroke:#7896ac,color:#203c50
classDef host fill:#f3f6fa,stroke:#7896ac,color:#203c50
classDef stream fill:#e0f0f5,stroke:#7896ac,color:#203c50
classDef wire fill:#dce7ef,stroke:#7896ac,color:#203c50
