block-beta
  columns 14
  NORTH["C2C · 片间连接"]:14
  block:MW0:1
    columns 1
    MW0HEAD["MXM"]:1
    MW0R19[" "]
    MW0R18[" "]
    MW0R17[" "]
    MW0R16[" "]
    MW0R15[" "]
    MW0R14[" "]
    MW0R13[" "]
    MW0R12[" "]
    MW0R11[" "]
    MW0R10[" "]
    MW0R9[" "]
    MW0R8[" "]
    MW0R7[" "]
    MW0R6[" "]
    MW0R5[" "]
    MW0R4[" "]
    MW0R3[" "]
    MW0R2[" "]
    MW0R1[" "]
    MW0R0[" "]
  end
  block:MW1:1
    columns 1
    MW1HEAD["MXM"]:1
    MW1R19[" "]
    MW1R18[" "]
    MW1R17[" "]
    MW1R16[" "]
    MW1R15[" "]
    MW1R14[" "]
    MW1R13[" "]
    MW1R12[" "]
    MW1R11[" "]
    MW1R10[" "]
    MW1R9[" "]
    MW1R8[" "]
    MW1R7[" "]
    MW1R6[" "]
    MW1R5[" "]
    MW1R4[" "]
    MW1R3[" "]
    MW1R2[" "]
    MW1R1[" "]
    MW1R0[" "]
  end
  block:SW:1
    columns 1
    SWHEAD["SXM"]:1
    SWR19[" "]
    SWR18[" "]
    SWR17[" "]
    SWR16[" "]
    SWR15[" "]
    SWR14[" "]
    SWR13[" "]
    SWR12[" "]
    SWR11[" "]
    SWR10[" "]
    SWR9[" "]
    SWR8[" "]
    SWR7[" "]
    SWR6[" "]
    SWR5[" "]
    SWR4[" "]
    SWR3[" "]
    SWR2[" "]
    SWR1[" "]
    SWR0[" "]
  end
  block:MEMW:3
    columns 8
    MEMWHEAD["西侧 SRAM"]:8
    MEMWR19C0[" "]
    MEMWR19C1[" "]
    MEMWR19C2[" "]
    MEMWR19C3[" "]
    MEMWR19C4[" "]
    MEMWR19C5[" "]
    MEMWR19C6[" "]
    MEMWR19C7[" "]
    MEMWR18C0[" "]
    MEMWR18C1[" "]
    MEMWR18C2[" "]
    MEMWR18C3[" "]
    MEMWR18C4[" "]
    MEMWR18C5[" "]
    MEMWR18C6[" "]
    MEMWR18C7[" "]
    MEMWR17C0[" "]
    MEMWR17C1[" "]
    MEMWR17C2[" "]
    MEMWR17C3[" "]
    MEMWR17C4[" "]
    MEMWR17C5[" "]
    MEMWR17C6[" "]
    MEMWR17C7[" "]
    MEMWR16C0[" "]
    MEMWR16C1[" "]
    MEMWR16C2[" "]
    MEMWR16C3[" "]
    MEMWR16C4[" "]
    MEMWR16C5[" "]
    MEMWR16C6[" "]
    MEMWR16C7[" "]
    MEMWR15C0[" "]
    MEMWR15C1[" "]
    MEMWR15C2[" "]
    MEMWR15C3[" "]
    MEMWR15C4[" "]
    MEMWR15C5[" "]
    MEMWR15C6[" "]
    MEMWR15C7[" "]
    MEMWR14C0[" "]
    MEMWR14C1[" "]
    MEMWR14C2[" "]
    MEMWR14C3[" "]
    MEMWR14C4[" "]
    MEMWR14C5[" "]
    MEMWR14C6[" "]
    MEMWR14C7[" "]
    MEMWR13C0[" "]
    MEMWR13C1[" "]
    MEMWR13C2[" "]
    MEMWR13C3[" "]
    MEMWR13C4[" "]
    MEMWR13C5[" "]
    MEMWR13C6[" "]
    MEMWR13C7[" "]
    MEMWR12C0[" "]
    MEMWR12C1[" "]
    MEMWR12C2[" "]
    MEMWR12C3[" "]
    MEMWR12C4[" "]
    MEMWR12C5[" "]
    MEMWR12C6[" "]
    MEMWR12C7[" "]
    MEMWR11C0[" "]
    MEMWR11C1[" "]
    MEMWR11C2[" "]
    MEMWR11C3[" "]
    MEMWR11C4[" "]
    MEMWR11C5[" "]
    MEMWR11C6[" "]
    MEMWR11C7[" "]
    MEMWR10C0[" "]
    MEMWR10C1[" "]
    MEMWR10C2[" "]
    MEMWR10C3[" "]
    MEMWR10C4[" "]
    MEMWR10C5[" "]
    MEMWR10C6[" "]
    MEMWR10C7[" "]
    MEMWR9C0[" "]
    MEMWR9C1[" "]
    MEMWR9C2[" "]
    MEMWR9C3[" "]
    MEMWR9C4[" "]
    MEMWR9C5[" "]
    MEMWR9C6[" "]
    MEMWR9C7[" "]
    MEMWR8C0[" "]
    MEMWR8C1[" "]
    MEMWR8C2[" "]
    MEMWR8C3[" "]
    MEMWR8C4[" "]
    MEMWR8C5[" "]
    MEMWR8C6[" "]
    MEMWR8C7[" "]
    MEMWR7C0[" "]
    MEMWR7C1[" "]
    MEMWR7C2[" "]
    MEMWR7C3[" "]
    MEMWR7C4[" "]
    MEMWR7C5[" "]
    MEMWR7C6[" "]
    MEMWR7C7[" "]
    MEMWR6C0[" "]
    MEMWR6C1[" "]
    MEMWR6C2[" "]
    MEMWR6C3[" "]
    MEMWR6C4[" "]
    MEMWR6C5[" "]
    MEMWR6C6[" "]
    MEMWR6C7[" "]
    MEMWR5C0[" "]
    MEMWR5C1[" "]
    MEMWR5C2[" "]
    MEMWR5C3[" "]
    MEMWR5C4[" "]
    MEMWR5C5[" "]
    MEMWR5C6[" "]
    MEMWR5C7[" "]
    MEMWR4C0[" "]
    MEMWR4C1[" "]
    MEMWR4C2[" "]
    MEMWR4C3[" "]
    MEMWR4C4[" "]
    MEMWR4C5[" "]
    MEMWR4C6[" "]
    MEMWR4C7[" "]
    MEMWR3C0[" "]
    MEMWR3C1[" "]
    MEMWR3C2[" "]
    MEMWR3C3[" "]
    MEMWR3C4[" "]
    MEMWR3C5[" "]
    MEMWR3C6[" "]
    MEMWR3C7[" "]
    MEMWR2C0[" "]
    MEMWR2C1[" "]
    MEMWR2C2[" "]
    MEMWR2C3[" "]
    MEMWR2C4[" "]
    MEMWR2C5[" "]
    MEMWR2C6[" "]
    MEMWR2C7[" "]
    MEMWR1C0[" "]
    MEMWR1C1[" "]
    MEMWR1C2[" "]
    MEMWR1C3[" "]
    MEMWR1C4[" "]
    MEMWR1C5[" "]
    MEMWR1C6[" "]
    MEMWR1C7[" "]
    MEMWR0C0[" "]
    MEMWR0C1[" "]
    MEMWR0C2[" "]
    MEMWR0C3[" "]
    MEMWR0C4[" "]
    MEMWR0C5[" "]
    MEMWR0C6[" "]
    MEMWR0C7[" "]
  end
  block:VX:2
    columns 1
    VXHEAD["VXM"]:1
    VXR19[" "]
    VXR18[" "]
    VXR17[" "]
    VXR16[" "]
    VXR15[" "]
    VXR14[" "]
    VXR13[" "]
    VXR12[" "]
    VXR11[" "]
    VXR10[" "]
    VXR9[" "]
    VXR8[" "]
    VXR7[" "]
    VXR6[" "]
    VXR5[" "]
    VXR4[" "]
    VXR3[" "]
    VXR2[" "]
    VXR1[" "]
    VXR0[" "]
  end
  block:MEME:3
    columns 8
    MEMEHEAD["东侧 SRAM"]:8
    MEMER19C0[" "]
    MEMER19C1[" "]
    MEMER19C2[" "]
    MEMER19C3[" "]
    MEMER19C4[" "]
    MEMER19C5[" "]
    MEMER19C6[" "]
    MEMER19C7[" "]
    MEMER18C0[" "]
    MEMER18C1[" "]
    MEMER18C2[" "]
    MEMER18C3[" "]
    MEMER18C4[" "]
    MEMER18C5[" "]
    MEMER18C6[" "]
    MEMER18C7[" "]
    MEMER17C0[" "]
    MEMER17C1[" "]
    MEMER17C2[" "]
    MEMER17C3[" "]
    MEMER17C4[" "]
    MEMER17C5[" "]
    MEMER17C6[" "]
    MEMER17C7[" "]
    MEMER16C0[" "]
    MEMER16C1[" "]
    MEMER16C2[" "]
    MEMER16C3[" "]
    MEMER16C4[" "]
    MEMER16C5[" "]
    MEMER16C6[" "]
    MEMER16C7[" "]
    MEMER15C0[" "]
    MEMER15C1[" "]
    MEMER15C2[" "]
    MEMER15C3[" "]
    MEMER15C4[" "]
    MEMER15C5[" "]
    MEMER15C6[" "]
    MEMER15C7[" "]
    MEMER14C0[" "]
    MEMER14C1[" "]
    MEMER14C2[" "]
    MEMER14C3[" "]
    MEMER14C4[" "]
    MEMER14C5[" "]
    MEMER14C6[" "]
    MEMER14C7[" "]
    MEMER13C0[" "]
    MEMER13C1[" "]
    MEMER13C2[" "]
    MEMER13C3[" "]
    MEMER13C4[" "]
    MEMER13C5[" "]
    MEMER13C6[" "]
    MEMER13C7[" "]
    MEMER12C0[" "]
    MEMER12C1[" "]
    MEMER12C2[" "]
    MEMER12C3[" "]
    MEMER12C4[" "]
    MEMER12C5[" "]
    MEMER12C6[" "]
    MEMER12C7[" "]
    MEMER11C0[" "]
    MEMER11C1[" "]
    MEMER11C2[" "]
    MEMER11C3[" "]
    MEMER11C4[" "]
    MEMER11C5[" "]
    MEMER11C6[" "]
    MEMER11C7[" "]
    MEMER10C0[" "]
    MEMER10C1[" "]
    MEMER10C2[" "]
    MEMER10C3[" "]
    MEMER10C4[" "]
    MEMER10C5[" "]
    MEMER10C6[" "]
    MEMER10C7[" "]
    MEMER9C0[" "]
    MEMER9C1[" "]
    MEMER9C2[" "]
    MEMER9C3[" "]
    MEMER9C4[" "]
    MEMER9C5[" "]
    MEMER9C6[" "]
    MEMER9C7[" "]
    MEMER8C0[" "]
    MEMER8C1[" "]
    MEMER8C2[" "]
    MEMER8C3[" "]
    MEMER8C4[" "]
    MEMER8C5[" "]
    MEMER8C6[" "]
    MEMER8C7[" "]
    MEMER7C0[" "]
    MEMER7C1[" "]
    MEMER7C2[" "]
    MEMER7C3[" "]
    MEMER7C4[" "]
    MEMER7C5[" "]
    MEMER7C6[" "]
    MEMER7C7[" "]
    MEMER6C0[" "]
    MEMER6C1[" "]
    MEMER6C2[" "]
    MEMER6C3[" "]
    MEMER6C4[" "]
    MEMER6C5[" "]
    MEMER6C6[" "]
    MEMER6C7[" "]
    MEMER5C0[" "]
    MEMER5C1[" "]
    MEMER5C2[" "]
    MEMER5C3[" "]
    MEMER5C4[" "]
    MEMER5C5[" "]
    MEMER5C6[" "]
    MEMER5C7[" "]
    MEMER4C0[" "]
    MEMER4C1[" "]
    MEMER4C2[" "]
    MEMER4C3[" "]
    MEMER4C4[" "]
    MEMER4C5[" "]
    MEMER4C6[" "]
    MEMER4C7[" "]
    MEMER3C0[" "]
    MEMER3C1[" "]
    MEMER3C2[" "]
    MEMER3C3[" "]
    MEMER3C4[" "]
    MEMER3C5[" "]
    MEMER3C6[" "]
    MEMER3C7[" "]
    MEMER2C0[" "]
    MEMER2C1[" "]
    MEMER2C2[" "]
    MEMER2C3[" "]
    MEMER2C4[" "]
    MEMER2C5[" "]
    MEMER2C6[" "]
    MEMER2C7[" "]
    MEMER1C0[" "]
    MEMER1C1[" "]
    MEMER1C2[" "]
    MEMER1C3[" "]
    MEMER1C4[" "]
    MEMER1C5[" "]
    MEMER1C6[" "]
    MEMER1C7[" "]
    MEMER0C0[" "]
    MEMER0C1[" "]
    MEMER0C2[" "]
    MEMER0C3[" "]
    MEMER0C4[" "]
    MEMER0C5[" "]
    MEMER0C6[" "]
    MEMER0C7[" "]
  end
  block:SE:1
    columns 1
    SEHEAD["SXM"]:1
    SER19[" "]
    SER18[" "]
    SER17[" "]
    SER16[" "]
    SER15[" "]
    SER14[" "]
    SER13[" "]
    SER12[" "]
    SER11[" "]
    SER10[" "]
    SER9[" "]
    SER8[" "]
    SER7[" "]
    SER6[" "]
    SER5[" "]
    SER4[" "]
    SER3[" "]
    SER2[" "]
    SER1[" "]
    SER0[" "]
  end
  block:ME0:1
    columns 1
    ME0HEAD["MXM"]:1
    ME0R19[" "]
    ME0R18[" "]
    ME0R17[" "]
    ME0R16[" "]
    ME0R15[" "]
    ME0R14[" "]
    ME0R13[" "]
    ME0R12[" "]
    ME0R11[" "]
    ME0R10[" "]
    ME0R9[" "]
    ME0R8[" "]
    ME0R7[" "]
    ME0R6[" "]
    ME0R5[" "]
    ME0R4[" "]
    ME0R3[" "]
    ME0R2[" "]
    ME0R1[" "]
    ME0R0[" "]
  end
  block:ME1:1
    columns 1
    ME1HEAD["MXM"]:1
    ME1R19[" "]
    ME1R18[" "]
    ME1R17[" "]
    ME1R16[" "]
    ME1R15[" "]
    ME1R14[" "]
    ME1R13[" "]
    ME1R12[" "]
    ME1R11[" "]
    ME1R10[" "]
    ME1R9[" "]
    ME1R8[" "]
    ME1R7[" "]
    ME1R6[" "]
    ME1R5[" "]
    ME1R4[" "]
    ME1R3[" "]
    ME1R2[" "]
    ME1R1[" "]
    ME1R0[" "]
  end
  CONTROL["ICU · 各切片的指令控制单元"]:14
  PCIE["主机接口"]:3
  SOUTH["C2C · 其他芯片"]:11
class MW0,MW0HEAD mxm
class MW0R0 mxm
class MW0R1 mxm
class MW0R2 mxm
class MW0R3 mxm
class MW0R4 mxm
class MW0R5 mxm
class MW0R6 mxm
class MW0R7 mxm
class MW0R8 mxm
class MW0R9 mxm
class MW0R10 mxm
class MW0R11 mxm
class MW0R12 mxm
class MW0R13 mxm
class MW0R14 mxm
class MW0R15 mxm
class MW0R16 mxm
class MW0R17 mxm
class MW0R18 mxm
class MW0R19 mxm
class MW1,MW1HEAD mxm
class MW1R0 mxm
class MW1R1 mxm
class MW1R2 mxm
class MW1R3 mxm
class MW1R4 mxm
class MW1R5 mxm
class MW1R6 mxm
class MW1R7 mxm
class MW1R8 mxm
class MW1R9 mxm
class MW1R10 mxm
class MW1R11 mxm
class MW1R12 mxm
class MW1R13 mxm
class MW1R14 mxm
class MW1R15 mxm
class MW1R16 mxm
class MW1R17 mxm
class MW1R18 mxm
class MW1R19 mxm
class SW,SWHEAD sxm
class SWR0 sxm
class SWR1 sxm
class SWR2 sxm
class SWR3 sxm
class SWR4 sxm
class SWR5 sxm
class SWR6 sxm
class SWR7 sxm
class SWR8 sxm
class SWR9 sxm
class SWR10 sxm
class SWR11 sxm
class SWR12 sxm
class SWR13 sxm
class SWR14 sxm
class SWR15 sxm
class SWR16 sxm
class SWR17 sxm
class SWR18 sxm
class SWR19 sxm
class MEMW,MEMWHEAD mem
class MEMWR0C0 mem
class MEMWR0C1 mem
class MEMWR0C2 mem
class MEMWR0C3 mem
class MEMWR0C4 mem
class MEMWR0C5 mem
class MEMWR0C6 mem
class MEMWR0C7 mem
class MEMWR1C0 mem
class MEMWR1C1 mem
class MEMWR1C2 mem
class MEMWR1C3 mem
class MEMWR1C4 mem
class MEMWR1C5 mem
class MEMWR1C6 mem
class MEMWR1C7 mem
class MEMWR2C0 mem
class MEMWR2C1 mem
class MEMWR2C2 mem
class MEMWR2C3 mem
class MEMWR2C4 mem
class MEMWR2C5 mem
class MEMWR2C6 mem
class MEMWR2C7 mem
class MEMWR3C0 mem
class MEMWR3C1 mem
class MEMWR3C2 mem
class MEMWR3C3 mem
class MEMWR3C4 mem
class MEMWR3C5 mem
class MEMWR3C6 mem
class MEMWR3C7 mem
class MEMWR4C0 mem
class MEMWR4C1 mem
class MEMWR4C2 mem
class MEMWR4C3 mem
class MEMWR4C4 mem
class MEMWR4C5 mem
class MEMWR4C6 mem
class MEMWR4C7 mem
class MEMWR5C0 mem
class MEMWR5C1 mem
class MEMWR5C2 mem
class MEMWR5C3 mem
class MEMWR5C4 mem
class MEMWR5C5 mem
class MEMWR5C6 mem
class MEMWR5C7 mem
class MEMWR6C0 mem
class MEMWR6C1 mem
class MEMWR6C2 mem
class MEMWR6C3 mem
class MEMWR6C4 mem
class MEMWR6C5 mem
class MEMWR6C6 mem
class MEMWR6C7 mem
class MEMWR7C0 mem
class MEMWR7C1 mem
class MEMWR7C2 mem
class MEMWR7C3 mem
class MEMWR7C4 mem
class MEMWR7C5 mem
class MEMWR7C6 mem
class MEMWR7C7 mem
class MEMWR8C0 mem
class MEMWR8C1 mem
class MEMWR8C2 mem
class MEMWR8C3 mem
class MEMWR8C4 mem
class MEMWR8C5 mem
class MEMWR8C6 mem
class MEMWR8C7 mem
class MEMWR9C0 mem
class MEMWR9C1 mem
class MEMWR9C2 mem
class MEMWR9C3 mem
class MEMWR9C4 mem
class MEMWR9C5 mem
class MEMWR9C6 mem
class MEMWR9C7 mem
class MEMWR10C0 mem
class MEMWR10C1 mem
class MEMWR10C2 mem
class MEMWR10C3 mem
class MEMWR10C4 mem
class MEMWR10C5 mem
class MEMWR10C6 mem
class MEMWR10C7 mem
class MEMWR11C0 mem
class MEMWR11C1 mem
class MEMWR11C2 mem
class MEMWR11C3 mem
class MEMWR11C4 mem
class MEMWR11C5 mem
class MEMWR11C6 mem
class MEMWR11C7 mem
class MEMWR12C0 mem
class MEMWR12C1 mem
class MEMWR12C2 mem
class MEMWR12C3 mem
class MEMWR12C4 mem
class MEMWR12C5 mem
class MEMWR12C6 mem
class MEMWR12C7 mem
class MEMWR13C0 mem
class MEMWR13C1 mem
class MEMWR13C2 mem
class MEMWR13C3 mem
class MEMWR13C4 mem
class MEMWR13C5 mem
class MEMWR13C6 mem
class MEMWR13C7 mem
class MEMWR14C0 mem
class MEMWR14C1 mem
class MEMWR14C2 mem
class MEMWR14C3 mem
class MEMWR14C4 mem
class MEMWR14C5 mem
class MEMWR14C6 mem
class MEMWR14C7 mem
class MEMWR15C0 mem
class MEMWR15C1 mem
class MEMWR15C2 mem
class MEMWR15C3 mem
class MEMWR15C4 mem
class MEMWR15C5 mem
class MEMWR15C6 mem
class MEMWR15C7 mem
class MEMWR16C0 mem
class MEMWR16C1 mem
class MEMWR16C2 mem
class MEMWR16C3 mem
class MEMWR16C4 mem
class MEMWR16C5 mem
class MEMWR16C6 mem
class MEMWR16C7 mem
class MEMWR17C0 mem
class MEMWR17C1 mem
class MEMWR17C2 mem
class MEMWR17C3 mem
class MEMWR17C4 mem
class MEMWR17C5 mem
class MEMWR17C6 mem
class MEMWR17C7 mem
class MEMWR18C0 mem
class MEMWR18C1 mem
class MEMWR18C2 mem
class MEMWR18C3 mem
class MEMWR18C4 mem
class MEMWR18C5 mem
class MEMWR18C6 mem
class MEMWR18C7 mem
class MEMWR19C0 mem
class MEMWR19C1 mem
class MEMWR19C2 mem
class MEMWR19C3 mem
class MEMWR19C4 mem
class MEMWR19C5 mem
class MEMWR19C6 mem
class MEMWR19C7 mem
class VX,VXHEAD vxm
class VXR0 vxm
class VXR1 vxm
class VXR2 vxm
class VXR3 vxm
class VXR4 vxm
class VXR5 vxm
class VXR6 vxm
class VXR7 vxm
class VXR8 vxm
class VXR9 vxm
class VXR10 vxm
class VXR11 vxm
class VXR12 vxm
class VXR13 vxm
class VXR14 vxm
class VXR15 vxm
class VXR16 vxm
class VXR17 vxm
class VXR18 vxm
class VXR19 vxm
class MEME,MEMEHEAD mem
class MEMER0C0 mem
class MEMER0C1 mem
class MEMER0C2 mem
class MEMER0C3 mem
class MEMER0C4 mem
class MEMER0C5 mem
class MEMER0C6 mem
class MEMER0C7 mem
class MEMER1C0 mem
class MEMER1C1 mem
class MEMER1C2 mem
class MEMER1C3 mem
class MEMER1C4 mem
class MEMER1C5 mem
class MEMER1C6 mem
class MEMER1C7 mem
class MEMER2C0 mem
class MEMER2C1 mem
class MEMER2C2 mem
class MEMER2C3 mem
class MEMER2C4 mem
class MEMER2C5 mem
class MEMER2C6 mem
class MEMER2C7 mem
class MEMER3C0 mem
class MEMER3C1 mem
class MEMER3C2 mem
class MEMER3C3 mem
class MEMER3C4 mem
class MEMER3C5 mem
class MEMER3C6 mem
class MEMER3C7 mem
class MEMER4C0 mem
class MEMER4C1 mem
class MEMER4C2 mem
class MEMER4C3 mem
class MEMER4C4 mem
class MEMER4C5 mem
class MEMER4C6 mem
class MEMER4C7 mem
class MEMER5C0 mem
class MEMER5C1 mem
class MEMER5C2 mem
class MEMER5C3 mem
class MEMER5C4 mem
class MEMER5C5 mem
class MEMER5C6 mem
class MEMER5C7 mem
class MEMER6C0 mem
class MEMER6C1 mem
class MEMER6C2 mem
class MEMER6C3 mem
class MEMER6C4 mem
class MEMER6C5 mem
class MEMER6C6 mem
class MEMER6C7 mem
class MEMER7C0 mem
class MEMER7C1 mem
class MEMER7C2 mem
class MEMER7C3 mem
class MEMER7C4 mem
class MEMER7C5 mem
class MEMER7C6 mem
class MEMER7C7 mem
class MEMER8C0 mem
class MEMER8C1 mem
class MEMER8C2 mem
class MEMER8C3 mem
class MEMER8C4 mem
class MEMER8C5 mem
class MEMER8C6 mem
class MEMER8C7 mem
class MEMER9C0 mem
class MEMER9C1 mem
class MEMER9C2 mem
class MEMER9C3 mem
class MEMER9C4 mem
class MEMER9C5 mem
class MEMER9C6 mem
class MEMER9C7 mem
class MEMER10C0 mem
class MEMER10C1 mem
class MEMER10C2 mem
class MEMER10C3 mem
class MEMER10C4 mem
class MEMER10C5 mem
class MEMER10C6 mem
class MEMER10C7 mem
class MEMER11C0 mem
class MEMER11C1 mem
class MEMER11C2 mem
class MEMER11C3 mem
class MEMER11C4 mem
class MEMER11C5 mem
class MEMER11C6 mem
class MEMER11C7 mem
class MEMER12C0 mem
class MEMER12C1 mem
class MEMER12C2 mem
class MEMER12C3 mem
class MEMER12C4 mem
class MEMER12C5 mem
class MEMER12C6 mem
class MEMER12C7 mem
class MEMER13C0 mem
class MEMER13C1 mem
class MEMER13C2 mem
class MEMER13C3 mem
class MEMER13C4 mem
class MEMER13C5 mem
class MEMER13C6 mem
class MEMER13C7 mem
class MEMER14C0 mem
class MEMER14C1 mem
class MEMER14C2 mem
class MEMER14C3 mem
class MEMER14C4 mem
class MEMER14C5 mem
class MEMER14C6 mem
class MEMER14C7 mem
class MEMER15C0 mem
class MEMER15C1 mem
class MEMER15C2 mem
class MEMER15C3 mem
class MEMER15C4 mem
class MEMER15C5 mem
class MEMER15C6 mem
class MEMER15C7 mem
class MEMER16C0 mem
class MEMER16C1 mem
class MEMER16C2 mem
class MEMER16C3 mem
class MEMER16C4 mem
class MEMER16C5 mem
class MEMER16C6 mem
class MEMER16C7 mem
class MEMER17C0 mem
class MEMER17C1 mem
class MEMER17C2 mem
class MEMER17C3 mem
class MEMER17C4 mem
class MEMER17C5 mem
class MEMER17C6 mem
class MEMER17C7 mem
class MEMER18C0 mem
class MEMER18C1 mem
class MEMER18C2 mem
class MEMER18C3 mem
class MEMER18C4 mem
class MEMER18C5 mem
class MEMER18C6 mem
class MEMER18C7 mem
class MEMER19C0 mem
class MEMER19C1 mem
class MEMER19C2 mem
class MEMER19C3 mem
class MEMER19C4 mem
class MEMER19C5 mem
class MEMER19C6 mem
class MEMER19C7 mem
class SE,SEHEAD sxm
class SER0 sxm
class SER1 sxm
class SER2 sxm
class SER3 sxm
class SER4 sxm
class SER5 sxm
class SER6 sxm
class SER7 sxm
class SER8 sxm
class SER9 sxm
class SER10 sxm
class SER11 sxm
class SER12 sxm
class SER13 sxm
class SER14 sxm
class SER15 sxm
class SER16 sxm
class SER17 sxm
class SER18 sxm
class SER19 sxm
class ME0,ME0HEAD mxm
class ME0R0 mxm
class ME0R1 mxm
class ME0R2 mxm
class ME0R3 mxm
class ME0R4 mxm
class ME0R5 mxm
class ME0R6 mxm
class ME0R7 mxm
class ME0R8 mxm
class ME0R9 mxm
class ME0R10 mxm
class ME0R11 mxm
class ME0R12 mxm
class ME0R13 mxm
class ME0R14 mxm
class ME0R15 mxm
class ME0R16 mxm
class ME0R17 mxm
class ME0R18 mxm
class ME0R19 mxm
class ME1,ME1HEAD mxm
class ME1R0 mxm
class ME1R1 mxm
class ME1R2 mxm
class ME1R3 mxm
class ME1R4 mxm
class ME1R5 mxm
class ME1R6 mxm
class ME1R7 mxm
class ME1R8 mxm
class ME1R9 mxm
class ME1R10 mxm
class ME1R11 mxm
class ME1R12 mxm
class ME1R13 mxm
class ME1R14 mxm
class ME1R15 mxm
class ME1R16 mxm
class ME1R17 mxm
class ME1R18 mxm
class ME1R19 mxm
class CONTROL icu
class NORTH,SOUTH,PCIE port

classDef mem fill:#dceef8,stroke:#7896ac,color:#203c50
classDef mxm fill:#fff0d1,stroke:#7896ac,color:#203c50
classDef vxm fill:#eee5fa,stroke:#7896ac,color:#203c50
classDef sxm fill:#e0f2e9,stroke:#7896ac,color:#203c50
classDef icu fill:#e5eafb,stroke:#7896ac,color:#203c50
classDef port fill:#eaf0f6,stroke:#7896ac,color:#203c50
classDef frame fill:#ffffff,stroke:#7896ac,color:#203c50
classDef host fill:#f3f6fa,stroke:#7896ac,color:#203c50
classDef stream fill:#e0f0f5,stroke:#7896ac,color:#203c50
classDef wire fill:#dce7ef,stroke:#7896ac,color:#203c50
