/* UTF-8 · 固定菜单、五层硬件、槽位/芯片选择与请求回放的实际浏览器验证。 */
'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),{pathToFileURL}=require('node:url'),{chromium}=require('playwright'),{writeReport}=require('./report.cjs'),M=require('../lpx-model.js');
const root=path.resolve(__dirname,'..'),logs=[],check=(name,value)=>{assert.ok(value,name);logs.push(name);console.log('通过：'+name);};
(async()=>{const browser=await chromium.launch({headless:true,executablePath:process.env.SPATIAL_BROWSER||'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});try{
 const p=await browser.newPage({viewport:{width:1600,height:1000}}),errors=[],requests=[];p.on('pageerror',e=>errors.push(e.message));p.on('request',r=>{if(r.url().startsWith('http'))requests.push(r.url());});const url=pathToFileURL(path.join(root,'Groq_TSP_交互讲解.html')).href;await p.goto(url,{waitUntil:'domcontentloaded'});await p.waitForFunction(()=>window.GROQ3_SPACE_APP);await p.evaluate(()=>GROQ3_SPACE_APP.activate());
 const panels=()=>p.evaluate(()=>['.g3-left','.g3-right'].map(q=>{const e=document.querySelector(q),r=e.getBoundingClientRect();return{x:r.x,y:r.y,w:r.width,h:r.height,inWorld:!!e.closest('.spatial-stage')};}));
 const initial=await p.evaluate(()=>({workspace:document.body.dataset.workspace,view:GROQ3_SPACE_APP.state.view,steps:document.querySelectorAll('[data-g3-step]').length,levels:document.querySelectorAll('[data-g3-level]').length}));
 check('兼容入口从外部 Prompt 开始，五个硬件层级与十五步请求主线同时存在',initial.workspace==='groq3'&&initial.view==='external'&&initial.steps===15&&initial.levels===5&&(await panels()).every(v=>!v.inWorld));
 fs.mkdirSync(path.join(root,'预览'),{recursive:true});
 for(const [level,step]of [['external',0],['rack',3],['tray',4],['fabric',6],['chip',9]]){await p.locator('[data-g3-step="'+step+'"]').click();await p.waitForTimeout(380);assert.equal(await p.evaluate(()=>GROQ3_SPACE_APP.state.view),level);const count=await p.evaluate(level=>level==='rack'?document.querySelectorAll('.lpx-solid.slot').length:level==='tray'||level==='fabric'?document.querySelectorAll('.lpx-solid.chip').length:level==='chip'?document.querySelectorAll('.g3-solid.region').length:1,level);assert.equal(count,level==='rack'?32:level==='tray'||level==='fabric'?8:level==='chip'?14:1);await p.screenshot({path:path.join(root,'预览/LPX_'+level+'.png')});}
 check('逐层显示 32 槽位、每托盘 8 芯片、以及官方图 3 的 14 个芯片分区',true);
 const menuBefore=await panels(),cameraBefore=await p.evaluate(()=>GROQ3_SPACE_APP.scene.camera.value.rotation),vxm=await p.locator('.g3-solid[data-region="VXM"] .g3-top').boundingBox();await p.mouse.move(vxm.x+vxm.width*.5,vxm.y+vxm.height*.5);await p.mouse.down();await p.mouse.move(vxm.x+vxm.width*.5+110,vxm.y+vxm.height*.5-55,{steps:12});await p.mouse.up();const cameraAfter=await p.evaluate(()=>GROQ3_SPACE_APP.scene.camera.value.rotation);check('旋转仅作用于中央硬件，左右菜单的位置、大小和朝向保持固定',JSON.stringify(menuBefore)===JSON.stringify(await panels())&&JSON.stringify(cameraBefore)!==JSON.stringify(cameraAfter));await p.locator('#g3-reset').click();
 await p.locator('[data-g3-level="rack"]').click();await p.waitForTimeout(380);for(let i=0;i<32;i++){await p.locator('#g3-slot').selectOption(String(i));assert.equal(await p.evaluate(()=>GROQ3_SPACE_APP.state.slot),i);}await p.locator('#g3-enter').click();assert.equal(await p.evaluate(()=>GROQ3_SPACE_APP.state.view),'tray');await p.locator('#g3-enter').click();for(let i=0;i<8;i++){await p.locator('#g3-chip').selectOption(String(i));assert.equal(await p.evaluate(()=>GROQ3_SPACE_APP.state.chip),i);}await p.locator('#g3-enter').click();await p.waitForTimeout(380);const reserve=await p.evaluate(()=>({label:document.getElementById('g3-assignment').textContent,hidden:document.querySelector('.g3-float.data').hidden,location:document.getElementById('g3-location').textContent}));
 check('所有槽位与本托盘八片均可选择，备用槽位不会显示该请求的芯片执行',reserve.label.includes('备用')&&reserve.hidden&&reserve.location.includes('255'));
 await p.locator('#g3-slot').selectOption('15');await p.locator('#g3-chip').selectOption('6');const mapping=await p.evaluate(()=>GROQ3_SPACE_APP.state);await p.locator('[data-g3-step="6"]').click();check('槽位 15 的第 6/7 片对应第 64 层 FFN，输入仍由两片共同接收',mapping.layer===64&&await p.locator('#g3-request-route').textContent().then(s=>s.includes('126 + 127')));await p.locator('#g3-layer').fill('1');
 await p.locator('[data-g3-step="9"]').click();const gate=await p.evaluate(()=>({data:document.getElementById('g3-data').textContent,read:document.getElementById('g3-bytes').textContent,time:document.getElementById('g3-time').textContent}));await p.locator('[data-g3-step="12"]').click();const reduction=await p.locator('#g3-data').textContent();check('当前数据和性能使用正确的不同口径，归约传输为 FP32 部分和',gate.data.includes('34.82 KB')&&gate.read.includes('89.13 MB')&&gate.time.includes('594.19')&&reduction.includes('20.48 KB'));
 await p.locator('[data-g3-step="0"]').click();await p.locator('#g3-prompt').fill('芯片A');const prompt=await p.locator('#g3-bytes').textContent();await p.locator('#g3-tokens').fill('16');await p.locator('[data-g3-step="1"]').click();const tokenBytes=await p.locator('#g3-bytes').textContent();await p.locator('#g3-tokens').fill('0');const invalid=await p.evaluate(()=>!document.getElementById('g3-tokens').checkValidity()&&GROQ3_SPACE_APP.state.tokens===16);await p.locator('#g3-tokens').fill('128');check('Prompt 按实际 UTF-8 字节计算，情景 Token 数可修改且非法值被拒绝',prompt==='7 B'&&tokenBytes==='64 B'&&invalid);
 await p.locator('#g3-model').selectOption('flash');await p.locator('[data-g3-step="10"]').click();const flash=await p.evaluate(()=>({weight:document.getElementById('g3-weight-total').textContent,deploy:document.getElementById('g3-deploy-name').textContent,time:document.getElementById('g3-time').textContent,data:document.getElementById('g3-data').textContent,count:document.querySelectorAll('[data-g3-step]').length,source:document.getElementById('g3-model-source').href}));check('Flash-Next 显示独立 MoE 主线、官方配置与单个专家成本',flash.weight==='180.00 GB'&&flash.deploy.includes('384 LPU')&&flash.time.includes('21.85')&&flash.data.includes('2.56 KB')&&flash.data.includes('E67')&&flash.count===16&&flash.source===M.sources.flash);
 await p.locator('#g3-precision').selectOption('2');await p.locator('#g3-layer').fill('48');await p.locator('#g3-expert').selectOption('507');await p.locator('[data-g3-step="7"]').click();const ep=await p.evaluate(()=>({state:GROQ3_SPACE_APP.state,route:{...document.querySelector('.lpx-packet.data').dataset},chips:document.querySelectorAll('.lpx-solid.chip.participating').length,deploy:document.getElementById('g3-deploy-name').textContent,weight:document.getElementById('g3-weight-total').textContent}));await p.locator('[data-g3-step="6"]').click();const rootState=await p.evaluate(()=>GROQ3_SPACE_APP.state);check('BF16 扩为 EP16，第 48 层经 spine 到机架 2 / LPU 767，路由仍在根片 752',ep.state.rack===2&&ep.state.slot===31&&ep.state.chip===7&&ep.route.from==='SPINE'&&ep.route.to==='CHIP7'&&ep.chips===5&&ep.deploy.includes('768 LPU')&&ep.weight==='360.00 GB'&&rootState.slot===30&&rootState.chip===0);
 await p.locator('#g3-layer').fill('49');const badLayer=await p.evaluate(()=>!document.getElementById('g3-layer').checkValidity()&&GROQ3_SPACE_APP.state.layer===48);await p.locator('#g3-layer').fill('1');await p.locator('#g3-expert').selectOption('3');await p.locator('[data-g3-step="13"]').click();const local=await p.locator('#g3-bytes').textContent();await p.locator('#g3-expert').selectOption('257');const remote=await p.locator('#g3-bytes').textContent();await p.locator('[data-g3-step="14"]').click();const returnState=await p.evaluate(()=>GROQ3_SPACE_APP.state);check('专家选择区分同片与远端回传，非法层数被拒绝，汇总输出回到根片托盘',badLayer&&local==='0 B'&&remote==='10.24 KB'&&returnState.slot===0&&returnState.chip===0);await p.screenshot({path:path.join(root,'预览/LPX_FlashNext.png')});await p.locator('#g3-model').selectOption('q27');await p.locator('#g3-precision').selectOption('1');
 await p.locator('[data-g3-step="4"]').click();await p.locator('#g3-data-layer').click();const dataOff=await p.locator('.lpx-packet.data').isVisible();const controlOn=await p.locator('.lpx-packet.control').isVisible();await p.locator('#g3-data-layer').click();await p.locator('#g3-instruction-layer').click();const controlOff=await p.locator('.lpx-packet.control').isVisible();await p.locator('#g3-instruction-layer').click();check('系统层的指令与数据也可独立显示，不影响硬件实体',!dataOff&&controlOn&&!controlOff);
 await p.locator('[data-g3-level="rack"]').click();await p.locator('#g3-explode').click();await p.waitForTimeout(450);const expanded=await p.evaluate(()=>getComputedStyle(GROQ3_SPACE_APP.systemScene.boxes.SLOT0.host).translate);await p.locator('#g3-enter').click();await p.locator('#g3-up').click();check('选中托盘可以向外展开，进入与返回保留所选槽位',expanded.includes('100px')&&await p.evaluate(()=>GROQ3_SPACE_APP.state.slot===0&&GROQ3_SPACE_APP.state.view==='rack'));
 await p.clock.install();await p.locator('[data-g3-step="0"]').click();await p.locator('#g3-play').click();await p.clock.runFor(4200);const advanced=await p.evaluate(()=>GROQ3_SPACE_APP.state);await p.locator('#g3-play').click();const paused=await p.evaluate(()=>GROQ3_SPACE_APP.state.elapsed);await p.clock.runFor(900);const held=await p.evaluate(()=>GROQ3_SPACE_APP.state.elapsed);await p.locator('#g3-play').click();await p.clock.fastForward(60000);const end=await p.evaluate(()=>GROQ3_SPACE_APP.state);await p.locator('#g3-replay').click();await p.clock.runFor(100);await p.locator('#show-cluster').click();const switched=await p.evaluate(()=>!GROQ3_SPACE_APP.state.running);await p.locator('#show-groq3').click();check('播放自动跨步骤、暂停冻结、结尾停止、重播恢复，切换旧视图会暂停',advanced.index===1&&advanced.elapsed>0&&paused===held&&end.index===14&&!end.running&&end.elapsed===3800&&switched);
 for(const viewport of [{width:1280,height:800},{width:760,height:780}]){await p.setViewportSize(viewport);await p.clock.runFor(100);const fit=await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth&&document.body.scrollHeight<=innerHeight&&document.querySelector('.g3-left').getBoundingClientRect().x>=0&&document.querySelector('.g3-right').getBoundingClientRect().right<=innerWidth);assert.ok(fit,'单屏布局 '+viewport.width);}check('桌面与窄屏保持固定两侧和单页布局，没有新增脚本异常',errors.length===0&&requests.every(u=>u===M.sources.chip));
 const offline=await browser.newContext({offline:true,viewport:{width:1440,height:900}}),q=await offline.newPage();await q.goto(url,{waitUntil:'domcontentloaded'});await q.waitForFunction(()=>window.GROQ3_SPACE_APP);await q.evaluate(()=>GROQ3_SPACE_APP.activate());await q.locator('[data-g3-step="9"]').click();await q.locator('#g3-play').click();await q.waitForTimeout(120);const fallback=await q.evaluate(()=>!GROQ3_SPACE_APP.scene.texture.ready&&GROQ3_SPACE_APP.state.running&&document.querySelectorAll('.g3-solid.region').length===14&&document.querySelectorAll('[data-g3-level]').length===5);check('原图纹理离线时，五层硬件和请求动画继续可用',fallback);await offline.close();
 writeReport('Groq3空间验证.md','# Groq 3 / LPX 浏览器验证\n\n'+logs.map(x=>'- 通过：'+x).join('\n')+'\n\n验证独立 HTML 的界面、状态与交互；没有执行真实 Qwen 推理或连接 Groq 硬件。\n');console.log('共 '+logs.length+' 组 LPX 浏览器检查通过。');
 }finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
