/* UTF-8 · 真实 Token、两模型分支和硬件分工检查。 */
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..'),ctx={TextEncoder};ctx.window=ctx;
for(const f of ['lpx-model.js','token-samples.js','network-model.js'])vm.runInNewContext(fs.readFileSync(path.join(root,f),'utf8'),ctx);
const N=ctx.NETWORK_MODEL,base={model:'q27',mode:'prefill',layer:1,weightBytes:1,tokenIndex:0,outputIndex:0,expert:67},checks=[];
function check(name,fn){fn();checks.push(name);console.log('通过：'+name);}
check('两份官方 tokenizer 快照均为 6 个正文 Token / 18 个模板输入',()=>{for(const s of Object.values(ctx.TOKEN_SAMPLES)){assert.equal(s.prompt,'谁是世界上最厉害的大模型？');assert.equal(s.tokens.map(t=>t.text).join(''),s.prompt);assert.equal(s.contextTokens.map(t=>t.text).join(''),s.formatted);assert.equal(s.tokens.map(t=>t.id).join(','),'121232,114314,102169,97796,103725,10992');assert.equal(s.contextIds.length,18);assert.equal(s.tokenizerSha256.length,64);}});
check('Prefill 全部 18 个位置，Decode 每轮一个新位置',()=>{assert.equal(N.shape(base).T,18);assert.equal(N.shape(base).S,18);assert.equal(N.shape({...base,mode:'decode',outputIndex:2}).T,1);assert.equal(N.shape({...base,mode:'decode',outputIndex:2}).S,21);});
check('DeltaNet 使用固定状态，完整 Attention 每四层出现一次',()=>{for(const model of ['q27','flash']){const delta=N.trace({...base,model}),full=N.trace({...base,model,layer:4});assert.ok(delta.some(s=>s.id==='deltastate'));assert.ok(!delta.some(s=>s.id==='softmax'));assert.ok(full.some(s=>s.id==='softmax'));assert.ok(!full.some(s=>s.id==='deltastate'));assert.equal(full.some(s=>s.id==='qsaindex'),model==='flash');}});
check('Flash-Next 第 2 层才注入 PLE，四路残差使用最终门控混合',()=>{for(let layer=1;layer<=48;layer++){const t=N.trace({...base,model:'flash',layer});assert.equal(t.some(s=>s.id==='ngram'),layer===2);assert.ok(t.some(s=>s.id==='expand'));assert.ok(t.find(s=>s.id==='finalnorm').formula.includes('GatedResidual'));}assert.ok(N.trace(base).find(s=>s.id==='finalnorm').formula.includes('RMSNorm'));});
check('Prefill 的 FFN 留在 GPU，Decode 的 FFN 经 LPX，返回 GPU 写残差',()=>{for(const model of ['q27','flash']){const p=N.trace({...base,model}),d=N.trace({...base,model,mode:'decode'});assert.equal(p.find(s=>s.id==='gateup').hardware,'GPU');assert.ok(!p.some(s=>s.id==='afd'));assert.equal(d.find(s=>s.id==='gateup').hardware,'LPX');assert.equal(d.find(s=>s.id==='ffnwrite').hardware,'GPU');assert.ok(d.findIndex(s=>s.id==='return')<d.findIndex(s=>s.id==='ffnwrite'));}});
check('MoE 先算 router 再 dispatch，同时包含共享专家与加权汇总',()=>{const d=N.trace({...base,model:'flash',mode:'decode'});assert.ok(d.findIndex(s=>s.id==='router')<d.findIndex(s=>s.id==='dispatch'));assert.ok(d.some(s=>s.id==='shared'));assert.ok(d.find(s=>s.id==='combine').formula.includes('pₑyₑ'));});
check('GPU 开销不套用 LPU 峰值；LPX 只给资源下界',()=>{const p=N.trace(base);assert.equal(N.cost(base,p.find(s=>s.id==='gateup')).ns,null);const dstate={...base,mode:'decode'},d=N.trace(dstate),g=d.find(s=>s.id==='gateup'),cost=N.cost(dstate,g);assert.equal(g.flops,4*5120*8704);assert.equal(cost.ns,g.weightBytes/150e12*1e9);assert.ok(cost.rule.includes('下界'));});
check('模型步骤按完整流程组顺序排列，不遗漏任何算子',()=>{for(const model of ['q27','flash'])for(const mode of ['prefill','decode'])for(const layer of [1,2,4]){const t=N.trace({...base,model,mode,layer});assert.equal(new Set(t.map(s=>s.id)).size,t.length);const group=t.map(s=>N.groups.findIndex(g=>g[0]===s.group));assert.ok(group.every((n,i)=>i===0||n>=group[i-1]));assert.ok(t.every(s=>s.formula&&s.detail&&s.output));}});
check('同片专家不产生虚构 C2C 字节，远端只按所选专家一次通信计量',()=>{for(const expert of [3,67]){const s={...base,model:'flash',mode:'decode',expert},t=N.trace(s);for(const id of ['dispatch','combine']){const c=N.cost(s,t.find(x=>x.id===id));assert.equal(c.bytes,expert===3?0:id==='dispatch'?5120:10240);assert.ok(expert===3?c.rule.includes('同片'):c.rule.includes('所选专家'));}}});
console.log('全部 '+checks.length+' 组网络与 Token 检查通过。');
