/* UTF-8 · 校验离散时钟、物理切片计划、数值与实际应用交互。图形接口用轻量替身。 */
'use strict';
const {writeReport}=require('./report.cjs');
const fs=require('node:fs'),path=require('node:path'),vm=require('node:vm'),assert=require('node:assert/strict'),C=require('../cycle-model.js'),M=require('../cycle-map.js'),{fixture,Element}=require('./check-playback.cjs');
const root=path.resolve(__dirname,'..'),read=f=>fs.readFileSync(path.join(root,f),'utf8'),logs=[],check=(name,fn)=>{fn();logs.push(name);console.log('通过：'+name);},near=(a,b,tol=1e-6)=>assert.ok(Math.abs(a-b)<tol,`${a} ≠ ${b}`);
check('六类微程序数值独立核对，Softmax 归一化且 RMSNorm 正确',()=>{
 const expected={q:[11,-1,7,10],ffn:[11,-1,7,10],rope:[2,1,4,3],sum:[10,10,10,10],transpose:[1,3,2,4],memory:[1,2,3,4],control:[1,2,3,4]};for(const [id,out]of Object.entries(expected))assert.deepEqual(C.build(id).expected,out);
 const silu=C.build('silu').expected;[1,-2,3,-4].forEach((x,i)=>near(silu[i],x/(1+Math.exp(-x))));
 const soft=C.build('softmax').expected,z=[1,2,3,4].reduce((a,b)=>a+Math.exp(b-4),0);soft.forEach((p,i)=>near(p,Math.exp(i-3)/z));near(soft.reduce((a,b)=>a+b,0),1);
 C.build('norm').expected.forEach((v,i)=>near(v,(i+1)/Math.sqrt(7.5+1e-5)));assert.equal(new Set(C.lessons.map(l=>l.family)).size,6);
});
let schedules=0;
check('810 组延迟 / 距离组合无物理 ICU 发射冲突或提前消费',()=>{for(const l of C.lessons)for(const hops of [1,3,6])for(const skew of [0,1,2])for(const read of [1,2,8])for(const vector of [1,2,8]){const m=C.build(l.id,{hops,skew,read,vector});assert.deepEqual(C.validate(m),[]);const occupied=new Set();for(const i of m.physicalProgram){const k=i.unit+':'+i.issue;assert.ok(!occupied.has(k),k);occupied.add(k);assert.equal(i.ready,i.consume+i.latency);}assert.equal(m.lastEnd,m.firstEnd+19);assert.deepEqual(C.snapshot(m,m.lastEnd,19).result,m.expected);schedules++;}});
check('SG4 从四个 MEM 切片错拍读出，字节平面在公共 SR 边界同拍对齐',()=>{
 const m=C.build('memory'),read=m.program.find(i=>i.kind==='read'),phys=m.physicalProgram.filter(i=>i.parent===read.id);assert.equal(phys.length,4);assert.deepEqual(phys.map(i=>i.issue),[0,1,2,3]);for(const i of phys)assert.equal(i.ready+(3-i.plane),read.ready);const first=C.snapshot(m,2);assert.equal(first.nowBytes,16);const last=C.snapshot(m,m.lastEnd);assert.equal(last.reads,20*4*16);assert.equal(last.writes,20*4*16);assert.equal(last.bytes,2560);
 const matrix=C.build('q');assert.equal(matrix.program.find(i=>i.kind==='read').planes,2);assert.equal(matrix.physicalProgram.filter(i=>i.kind==='read').length,10);assert.equal(C.snapshot(matrix,matrix.lastEnd).bytes,14*20*16);
});
check('每条数据流每拍只在一个公共 SR 中有效，原位置不会停留旧数据',()=>{const m=C.build('softmax');for(const r of m.routes)for(const sl of [0,9,19]){for(let hop=0;hop<=r.hops;hop++){const s=C.snapshot(m,r.start+sl+hop,sl),packets=s.streams.filter(p=>p.id===r.id);assert.equal(packets.length,1);assert.equal(packets[0].hop,hop);assert.deepEqual(packets[0].values,r.values);}assert.ok(!C.snapshot(m,r.start+sl-1,sl).streams.some(p=>p.id===r.id));assert.ok(!C.snapshot(m,r.end+sl+1,sl).streams.some(p=>p.id===r.id));}});
check('20 个 SL 保持 19 拍偏移，回退清除未来写回且重放一致',()=>{for(const l of C.lessons){const m=C.build(l.id);for(const sl of [0,1,7,19]){const c=m.firstEnd+sl;assert.equal(C.snapshot(m,c-1,sl).result,null);assert.deepEqual(C.snapshot(m,c,sl).result,m.expected);const end=JSON.stringify(C.snapshot(m,c,sl));C.snapshot(m,0,sl);assert.equal(JSON.stringify(C.snapshot(m,c,sl)),end);}assert.equal(C.snapshot(m,m.firstEnd).completed,1);assert.equal(C.snapshot(m,m.lastEnd).completed,20);}});
check('真实数据依赖会被校验，故意提前消费或让流错过一拍会报错',()=>{const m=C.build('rope');const compute=m.program.find(i=>i.kind==='compute'),old=compute.consume;compute.consume--;assert.ok(C.validate(m).some(e=>e.includes('未就绪')));compute.consume=old+1;assert.ok(C.validate(m).some(e=>e.includes('离开消费')));compute.consume=old;assert.deepEqual(C.validate(m),[]);});
check('单步事件定位严格单调，改变频率只改变 ns 而不改变周期与数据',()=>{const a=C.build('q',{ghz:.9}),b=C.build('q',{ghz:1.8});assert.deepEqual(a.program,b.program);assert.equal(a.lastEnd,b.lastEnd);near(C.snapshot(a,12).ns,C.snapshot(b,12).ns*2);assert.ok(C.build('q',{hops:6}).lastEnd>a.lastEnd);assert.ok(C.build('q',{matrix:8}).lastEnd>a.lastEnd);for(let c=0;c<a.lastEnd;c++)assert.ok(C.nextEvent(a,c,0)>c);for(let c=1;c<=a.lastEnd;c++)assert.ok(C.nextEvent(a,c,19,-1)<c);});
check('离散播放器不在两个时钟边沿之间改数，暂停 / 重播不留残余回调',()=>{
 let serial=0,ticks=[],frames=new Map();const clock=C.createClock({end:()=>5,onTick:c=>ticks.push(c),requestFrame:fn=>{frames.set(++serial,fn);return serial;},cancelFrame:id=>frames.delete(id),interval:()=>100});const tick=time=>{const fn=[...frames.values()];frames.clear();fn.forEach(f=>f(time));};clock.play();tick(0);tick(99);assert.deepEqual(ticks,[]);tick(100);assert.deepEqual(ticks,[1]);clock.stop();tick(1000);assert.deepEqual(ticks,[1]);clock.seek(0);clock.play();tick(2000);tick(2500);assert.deepEqual(ticks,[1,0,1,2,3,4,5]);assert.equal(clock.running,false);assert.equal(frames.size,0);
});
const box={window:{}};vm.runInNewContext(read('hardware-diagrams.js'),box);const G=box.window.HARDWARE_SVGS;
check('硬件全部使用 Mermaid，总览与内部窗口的节点和资源完整',()=>{assert.deepEqual(Object.keys(G.cycle9.nodes).sort(),Object.keys(M.nodes).sort());for(const [id,b]of Object.entries(M.nodes)){assert.ok(G.cycle9.nodes[id],id);assert.ok(b.x>=0&&b.y>=0&&b.x+b.w<=M.width&&b.y+b.h<=M.height,id);}for(const id of ['MAC33','ALU33','MEM_A_BANK1','MEM_B_BANK0','ICU_MXM','Y6','SL19'])assert.ok(read('hardware/cycle9.mmd').includes(id+'['));assert.ok(!G.cycle9.svg.includes('!important'),'静态调色板不能压住实时状态色');const h=read('index.html');assert.ok(h.includes('id="cycle-main"'));assert.ok(h.includes('id="cycle-live-instructions"'));assert.ok(h.includes('id="cycle-range"'));for(const f of ['cycle-app.js','cycle-scene.js','cycle-model.js','cycle-map.js','cycle.css','cycle-panel.html'])assert.ok(!new TextDecoder('utf-8',{fatal:true}).decode(fs.readFileSync(path.join(root,f))).includes('\uFFFD'));});
check('三个视图的 SL 标尺与全部功能切片同高，细节窗口不混入总览行',()=>{
 const A=require('../hardware-atlas-map.js'),K=require('../cluster-map.js'),cy=b=>b.y+b.h/2;
 for(let sl=0;sl<20;sl++)for(const [z] of M.zones){const b=M.nodes['GRID_'+z+'_'+sl];assert.equal(cy(b),cy(M.nodes['SL'+sl]));assert.equal(b.x,M.nodes['TOP_'+z].x);assert.equal(b.w,M.nodes['TOP_'+z].w);}
 for(const focusZone of [null,...A.zones.map(z=>z[0])]){const layout=A.layout(A.context({expanded:!!focusZone,focusZone}));for(let sl=0;sl<20;sl++)for(const [z]of A.zones)for(let col=0;col<(z.startsWith('MEM')?8:1);col++){const b=layout.nodes[z+'R'+sl+(z.startsWith('MEM')?'C'+col:'')];assert.equal(cy(b),cy(layout.nodes['SL'+sl]));assert.ok(b.x>layout.nodes['SL'+sl].x+layout.nodes['SL'+sl].w);}}
 for(let chip=0;chip<4;chip++)for(const sl of [0,5,10,15,19])for(const z of K.zones)assert.equal(cy(K.nodes['C'+chip+'_'+z+'SL'+sl]),cy(K.nodes['C'+chip+'_SL'+sl]));
 for(const id of ['MAC00','ALU00','MEM_A_BANK0','X0'])assert.ok(M.nodes[id].x>=M.focus.detail.x,'内部窗口独立：'+id);
 assert.equal((M.nodes.SL0.y-M.nodes.SL19.y)/19,23);
});
const f=fixture();f.env.document.body.dataset.workspace='cycle';f.els['cycle-speed'].value='125';f.env.GROQ_CYCLE=C;f.env.GROQ_CYCLE_MAP=M;f.env.HARDWARE_SVGS.cycle9=G.cycle9;
const svg=f.els['cycle-canvas'].appendChild(new Element('svg')),nodes={};for(const [id,b]of Object.entries(M.nodes)){const node=svg.appendChild(new Element('g'));node.dataset={hwId:id,kind:b.kind,owner:b.owner};node.appendChild(new Element('rect'));node.appendChild(new Element('label')).appendChild(new Element('text'));nodes[id]=node;}svg.querySelectorAll=()=>Object.values(nodes);
check('三个视图初始化：逐周期自动播放，其他两个隐藏视图不推进',()=>{f.run('performance-app.js');f.run('cluster-app.js');f.run('workspace-ui.js');f.run('cycle-scene.js');f.run('cycle-app.js');assert.ok(f.motions.every(m=>!m.engine.running));assert.equal(f.frames.size,1);assert.equal(f.env.GROQ_CYCLE_APP.getSnapshot().cycle,0);f.tick(1);f.tick(124);assert.equal(f.env.GROQ_CYCLE_APP.getSnapshot().cycle,0);f.tick(1);assert.equal(f.env.GROQ_CYCLE_APP.getSnapshot().cycle,1);assert.equal(f.els['cycle-clock'].textContent,'C 001');});
check('实际硬件渲染器同步更新有效 SR、权重和累加，回退确实抹去结果',()=>{
 const app=f.env.GROQ_CYCLE_APP,m=app.getModel(),r=m.routes.find(r=>r.bus==='W');app.seek(r.start);assert.ok(nodes.W0.classList.contains('cycle-data-valid'));assert.ok(nodes.W1.classList.contains('cycle-invalid'));app.seek(r.start+1);assert.ok(nodes.W1.classList.contains('cycle-data-valid'));const matrix=m.program.find(i=>i.kind==='matrix');app.seek(matrix.ready);assert.ok(nodes.MAC33.classList.contains('cycle-write'));assert.ok(nodes.ACC.querySelector('text').children.some(t=>t.textContent.includes('11')));app.seek(m.firstEnd);assert.ok(f.els['cycle-result'].textContent.includes('11'));app.seek(0);assert.ok(nodes.GRID_MW_0.classList.contains('cycle-instruction'));assert.ok(!nodes.GRID_MW_1.classList.contains('cycle-instruction'));app.seek(1);assert.ok(nodes.GRID_MW_1.classList.contains('cycle-instruction'));app.seek(0);assert.equal(f.els['cycle-result'].textContent,'尚未写回');assert.ok(!nodes.MAC33.classList.contains('cycle-write'));assert.equal(f.frames.size,0);
});
check('实际单拍、拖动、superlane、微程序、焦点与旧视图切换保持一个播放源',()=>{
 nodes.GRID_VX_7.dispatchEvent({type:'click'});assert.equal(f.env.GROQ_CYCLE_APP.getSnapshot().superlane,7);assert.equal(f.els['cycle-focus'].value,'detail');assert.equal(svg.getAttribute('viewBox'),[M.focus.detail.x,M.focus.detail.y,M.focus.detail.w,M.focus.detail.h].join(' '));assert.equal(nodes.SL7.getAttribute('tabindex'),'-1');f.click('cycle-fit');assert.equal(nodes.SL7.getAttribute('tabindex'),'0');
 f.click('cycle-next');assert.equal(f.env.GROQ_CYCLE_APP.getSnapshot().cycle,1);f.els['cycle-range'].value='10';f.els['cycle-range'].dispatchEvent({type:'input'});assert.equal(f.env.GROQ_CYCLE_APP.getSnapshot().cycle,10);f.els['cycle-sl'].value='19';f.els['cycle-sl'].dispatchEvent({type:'change'});assert.equal(f.env.GROQ_CYCLE_APP.getSnapshot().superlane,19);f.els['cycle-focus'].value='mxm';f.els['cycle-focus'].dispatchEvent({type:'change'});assert.equal(svg.getAttribute('viewBox'),[M.focus.mxm.x,M.focus.mxm.y,M.focus.mxm.w,M.focus.mxm.h].join(' '));f.click('cycle-fit');assert.equal(svg.getAttribute('viewBox'),'0 0 1040 650');f.els['cycle-lesson'].value='softmax';f.els['cycle-lesson'].dispatchEvent({type:'change'});assert.equal(f.env.GROQ_CYCLE_APP.getModel().lesson.id,'softmax');assert.equal(f.frames.size,1);f.click('show-cluster');assert.equal(f.env.document.body.dataset.workspace,'cluster');assert.equal(f.frames.size,0);f.click('show-single');assert.equal(f.env.document.body.dataset.workspace,'single');f.click('show-cycle');assert.equal(f.env.document.body.dataset.workspace,'cycle');f.click('cycle-play');assert.equal(f.frames.size,1);f.env.GROQ_WORKSPACE_UI.open('parameters');assert.equal(f.els['cycle-dialog'].open,true);assert.equal(f.frames.size,0);assert.ok(f.els['cycle-dialog-body'].innerHTML.includes('SG4'));f.click('cycle-dialog-close');f.click('cycle-program');assert.ok(f.els['cycle-dialog-body'].innerHTML.includes('逐个物理切片展开'));assert.ok(f.els['cycle-dialog-body'].innerHTML.includes('MEM_A3'));
});
writeReport('逐周期执行.md','# 逐周期执行检查报告\n\n'+logs.map(n=>'- '+n+'。').join('\n')+'\n\n共 '+logs.length+' 组检查，'+schedules+' 组静态计划组合。采用实际模型、播放器、场景更新器和三个视图应用脚本；界面与图形节点使用替身。未进行交互网页浏览器截图、点击或视觉验收。\n\n检验结论只支持本示例模型的自洽性，不证明与真实 Groq 编译器或硅片逐拍一致。\n');console.log('全部 '+logs.length+' 组逐周期检查通过。');
